// packages/vue/src/runtime/primitives/dialog-content.vue
<script setup lang="ts">
/**
 * DialogContent (Reka-compatible surface, RFC 0003).
 * `role="dialog"` container with Escape-to-close and shared focus trap +
 * restore when modal.
 */
import { getDialogState, isDialogDismissKey } from '@c15t/ui/primitives/dialog';
import { inject, onBeforeUnmount, onMounted, ref } from 'vue';

import { dialogContextKey } from './keys';
import { useFocusTrap } from './use-focus-trap';

const dialog = inject(dialogContextKey);
const root = ref<HTMLElement | null>(null);

const isModal = () => dialog?.modal() ?? false;
useFocusTrap(root, () => isModal() && (dialog?.open() ?? false), {
	initialFocus: 'first-tabbable',
});

const onKeydown = function onKeydown(event: KeyboardEvent) {
	if (isDialogDismissKey(event.key)) {
		event.preventDefault();
		dialog?.close();
	}
};

onMounted(() => {
	document.addEventListener('keydown', onKeydown);
});

onBeforeUnmount(() => {
	document.removeEventListener('keydown', onKeydown);
});
</script>

<template>
	<div
		ref="root"
		role="dialog"
		:aria-modal="isModal() ? 'true' : undefined"
		:data-state="getDialogState(dialog?.open() ?? true)"
		tabindex="-1"
		@keydown="onKeydown"
	>
		<slot />
	</div>
</template>

// packages/svelte/src/lib/primitives/dialog/dialog-content.svelte
<script lang="ts">
	import { getDialogState, isDialogDismissKey } from '@c15t/ui/primitives';
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';

	import { focusTrap } from '../../actions/focus-trap';
	import { scrollLock } from '../../actions/scroll-lock';
	import { getDialogRootContext } from './context';

	const dialog = getDialogRootContext();

	let node = $state<HTMLElement | null>(null);

	const open = $derived(dialog.open);
	const shouldRender = $derived(dialog.shouldRender);
	const contentId = $derived(dialog.contentId);
	const titleId = $derived(dialog.titleId);
	const descriptionId = $derived(dialog.descriptionId);
	const dataState = $derived(getDialogState(open));

	let {
		children,
		class: className,
		onkeydown,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & {
		children?: Snippet;
		class?: string;
	} = $props();

	const handleKeyDown = function handleKeyDown(
		event: KeyboardEvent & { currentTarget: EventTarget & HTMLDivElement }
	) {
		if (isDialogDismissKey(event.key)) {
			event.preventDefault();
			dialog.requestClose('escape');
		}
		onkeydown?.(event);
	};

	$effect(() => {
		if (!open || !node) {
			return;
		}

		queueMicrotask(() => {
			if (!node || !open) {
				return;
			}

			const { activeElement } = document;
			if (!activeElement || !node.contains(activeElement)) {
				const preferredFocusTarget = node.querySelector<HTMLElement>(
					'[data-c15t-dialog-focus="true"]'
				);
				(preferredFocusTarget ?? node).focus();
			}
		});
	});
</script>

{#if shouldRender}
	<div
		bind:this={node}
		id={contentId}
		role="dialog"
		tabindex={-1}
		aria-modal={dialog.trapFocus ? 'true' : undefined}
		aria-labelledby={titleId}
		aria-describedby={descriptionId}
		class={className}
		data-slot="dialog-content"
		data-state={dataState}
		use:focusTrap={{
			enabled: open && dialog.trapFocus,
			initialFocus: 'first-tabbable',
		}}
		use:scrollLock={open && dialog.preventScroll}
		{...restProps}
		onkeydown={handleKeyDown}
	>
		{@render children?.()}
	</div>
{/if}
