// packages/svelte/src/lib/components/prompt.svelte
<script lang="ts">
	import type {
		LegalLinks as LegalLinksType,
		Model,
		PromptPosition,
		PromptVariant,
	} from '@c15t/core';
	import {
		defaultTranslationConfig,
		resolveConsentPresentation,
	} from '@c15t/core';
	import type { PolicyRight } from '@c15t/schema/types';
	import styles from '@c15t/ui/styles/components/consent-banner';
	import { getTextDirection, resolveTranslations } from '@c15t/ui/utils';

	import { focusTrap } from '../actions/focus-trap';
	// Banner uses custom portal/focus-trap/scroll-lock actions (not Ark UI's built-in)
	// because the banner is not an Ark Dialog - it's a simpler container that
	// conditionally acts as a dialog. The ConsentDialog uses Ark's Dialog which
	// includes its own focus trap and scroll prevention. When transitioning from
	// banner to dialog, the banner unmounts (removing its focus trap) before
	// the dialog mounts (establishing Ark's focus trap), so they don't compete.
	import { portal } from '../actions/portal';
	import { scrollLock } from '../actions/scroll-lock';
	import { getConsentContext, getThemeContext } from '../context.svelte';
	import { useBannerVisibility } from '../use-banner-visibility.svelte';
	import { resolveComponentStyles, resolveConsentActionStyle } from '../utils';
	import ConsentButton from './action-button.svelte';
	import Branding from './branding.svelte';
	import InlineLegalLinks from './inline-legal-links.svelte';
	import Overlay from './overlay.svelte';
	import PolicyActionsRenderer from './policy-actions-renderer.svelte';

	/**
	 * Button identifiers for the consent banner layout.
	 */
	type ConsentBannerButton = 'reject' | 'accept' | 'customize' | 'dismiss';
	type ConsentBannerLayout = (ConsentBannerButton | ConsentBannerButton[])[];

	let {
		noStyle: localNoStyle,
		disableAnimation: localDisableAnimation,
		scrollLock: localScrollLock,
		trapFocus: localTrapFocus,
		title,
		description,
		rejectButtonText,
		customizeButtonText,
		acceptButtonText,
		dismissButtonText,
		hideBranding = false,
		legalLinks,
		layout,
		primaryButton,
		variant,
		position,
		blocking,
		models = ['opt-in', 'opt-out', 'iab'] as Model[],
		class: className,
	}: {
		noStyle?: boolean;
		disableAnimation?: boolean;
		scrollLock?: boolean;
		trapFocus?: boolean;
		title?: string;
		description?: string;
		rejectButtonText?: string;
		customizeButtonText?: string;
		acceptButtonText?: string;
		dismissButtonText?: string;
		hideBranding?: boolean;
		legalLinks?: (keyof LegalLinksType)[] | null;
		layout?: ConsentBannerLayout;
		primaryButton?: ConsentBannerButton | ConsentBannerButton[];
		/**
		 * Shape of the prompt. Overrides the host presentation.
		 * A notice defaults to `bar`, a choice prompt to `floating`.
		 */
		variant?: PromptVariant;
		/**
		 * Where the prompt sits. Must be valid for the resolved variant;
		 * an invalid value falls back to the variant default with a
		 * development diagnostic.
		 */
		position?: PromptPosition;
		/**
		 * Backdrop, scroll lock, focus trap, and no dismissal from outside,
		 * as one value. `wall` is always blocking; a notice never is.
		 */
		blocking?: boolean;
		models?: Model[];
		class?: string;
	} = $props();

	/** Corner mirror for right-to-left text when the host set no position. */
	const MIRRORED_POSITIONS: Partial<Record<PromptPosition, PromptPosition>> = {
		'bottom-left': 'bottom-right',
		'bottom-right': 'bottom-left',
		'top-left': 'top-right',
		'top-right': 'top-left',
	};

	const consent = getConsentContext();
	const theme = getThemeContext();

	const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);
	const disableAnimation = $derived(
		localDisableAnimation ?? theme.disableAnimation ?? false
	);

	// Translations
	const translations = $derived(
		resolveTranslations(
			consent.state.translationConfig,
			defaultTranslationConfig
		)
	);
	const textDirection = $derived(
		getTextDirection(consent.state.translationConfig?.defaultLanguage)
	);

	// Visibility logic
	const shouldShowBanner = $derived(
		consent.state.hasConsentUi &&
			consent.state.activeUI === 'banner' &&
			consent.snapshot.promptRequirement.kind !== 'none' &&
			models.includes(consent.state.model)
	);

	const visibility = useBannerVisibility(
		() => shouldShowBanner,
		() => disableAnimation
	);

	// Styling - per-element theme key resolution shared across framework adapters.
	const rootStyle = $derived(
		resolveComponentStyles(
			'consentBanner',
			theme.theme,
			{
				baseClassName: styles.root,
				className,
				noStyle,
			},
			noStyle
		)
	);

	const cardStyle = $derived(
		resolveComponentStyles(
			'consentBannerCard',
			theme.theme,
			{ baseClassName: styles.card, noStyle },
			noStyle
		)
	);

	const headerStyle = $derived(
		resolveComponentStyles(
			'consentBannerHeader',
			theme.theme,
			{ baseClassName: styles.header, noStyle },
			noStyle
		)
	);

	const titleStyle = $derived(
		resolveComponentStyles(
			'consentBannerTitle',
			theme.theme,
			{ baseClassName: styles.title, noStyle },
			noStyle
		)
	);

	const descriptionStyle = $derived(
		resolveComponentStyles(
			'consentBannerDescription',
			theme.theme,
			{ baseClassName: styles.description, noStyle },
			noStyle
		)
	);

	const footerStyle = $derived(
		resolveComponentStyles(
			'consentBannerFooter',
			theme.theme,
			{ baseClassName: styles.footer, noStyle },
			noStyle
		)
	);

	const footerSubGroupStyle = $derived(
		resolveComponentStyles(
			'consentBannerFooterSubGroup',
			theme.theme,
			{ noStyle },
			noStyle
		)
	);

	const rightsStyle = $derived(
		resolveComponentStyles(
			'consentBannerRights',
			theme.theme,
			{ baseClassName: styles.rights, noStyle },
			noStyle
		)
	);

	const rightLinkStyle = $derived(
		resolveComponentStyles(
			'consentBannerRightLink',
			theme.theme,
			{ baseClassName: styles.rightLink, noStyle },
			noStyle
		)
	);

	// A right control opens the preference center without recording a choice.
	const openPreferences = function openPreferences() {
		consent.state.setActiveUI('dialog');
	};

	const finalClassName = $derived(
		noStyle
			? rootStyle.className || ''
			: `${rootStyle.className || ''} ${visibility.isVisible ? `${styles.bannerVisible}${disableAnimation ? '' : ` ${styles.bannerEntering}`}` : styles.bannerHidden}`
	);

	const localPrimaryActions = $derived.by(() => {
		if (primaryButton === undefined) {
			return undefined;
		}
		return Array.isArray(primaryButton) ? primaryButton : [primaryButton];
	});
	// Button helpers
	const themedActions = $derived({
		accept: resolveConsentActionStyle(theme.theme, 'accept'),
		customize: resolveConsentActionStyle(theme.theme, 'customize'),
		dismiss: resolveConsentActionStyle(theme.theme, 'dismiss'),
		reject: resolveConsentActionStyle(theme.theme, 'reject'),
		save: resolveConsentActionStyle(theme.theme, 'save'),
	});
	const presentation = $derived(
		resolveConsentPresentation({
			actionAppearance: themedActions,
			override: {
				blocking,
				layout,
				position,
				primaryActions: localPrimaryActions,
				scrollLock: localScrollLock,
				trapFocus: localTrapFocus,
				variant,
			},
			policy: consent.snapshot.policyRule,
			presentation: {
				...consent.state.presentation,
				prompt: {
					scrollLock: theme.scrollLock,
					trapFocus: theme.trapFocus,
					...consent.state.presentation?.prompt,
				},
			},
			surface: 'prompt',
		})
	);
	const actionGroups = $derived(presentation.actionGroups);
	const primaryActions = $derived(presentation.primaryActions);
	// Additional buttons that open preferences, styled as underlined text.
	const preferenceControls = $derived(presentation.preferenceControls);
	// A notice offers dismiss alone; with no primary resolved it takes the lead.
	const dismissIsPrimary = $derived(
		primaryActions.length === 0 &&
			presentation.orderedActions.length === 1 &&
			presentation.orderedActions[0] === 'dismiss'
	);
	const promptKind = $derived(consent.snapshot.policyRule.prompt);
	const isNotice = $derived(promptKind === 'notice');
	const direction = $derived(presentation.direction);
	const shouldFillActions = $derived(presentation.shouldFillActions);
	const shouldTrapFocus = $derived(presentation.trapFocus);
	const shouldScrollLock = $derived(presentation.scrollLock);
	const resolvedVariant = $derived(presentation.variant);
	const isBlocking = $derived(presentation.blocking);
	// A defaulted corner follows the text direction; a host position is
	// physical and stays put.
	const resolvedPosition = $derived.by(() => {
		const { position: resolved, positionSource } = presentation;
		const corner =
			resolvedVariant === 'floating' || resolvedVariant === 'widget';
		if (textDirection === 'rtl' && positionSource === 'default' && corner) {
			return MIRRORED_POSITIONS[resolved] ?? resolved;
		}
		return resolved;
	});

	$effect(() => {
		if (
			typeof process === 'undefined' ||
			process.env?.NODE_ENV !== 'production'
		) {
			for (const diagnostic of presentation.diagnostics) {
				console.warn(diagnostic.message);
			}
		}
	});

	// Resolved texts. A notice has its own copy: it informs and points at
	// the opt-out instead of asking for permission.
	const englishTranslations = defaultTranslationConfig.translations.en;
	const resolvedTitle = $derived(
		title ??
			(isNotice
				? (translations.cookieBanner.noticeTitle ??
					englishTranslations?.cookieBanner?.noticeTitle)
				: translations.cookieBanner.title)
	);
	const resolvedDescription = $derived(
		description ??
			(isNotice
				? (translations.cookieBanner.noticeDescription ??
					englishTranslations?.cookieBanner?.noticeDescription)
				: translations.cookieBanner.description)
	);
	const exemptionNotices = $derived.by(() => {
		const kinds = new Set(
			Object.values(consent.snapshot.policyRule.exemptions ?? {}).map(
				(exemption) => exemption.kind
			)
		);
		return [
			kinds.has('uk-statistics')
				? (translations.common.exemptStatisticsNotice ??
					'We use service statistics to improve this service without asking for consent. You can turn this off in privacy settings.')
				: undefined,
			kinds.has('uk-appearance')
				? (translations.common.exemptAppearanceNotice ??
					'We use your appearance preferences without asking for consent. You can turn this off in privacy settings.')
				: undefined,
		].filter((notice) => notice !== undefined);
	});
	// Acknowledgement records no category choice.
	const resolvedDismissText = $derived(
		dismissButtonText ??
			translations.common.acknowledge ??
			translations.common.dismiss ??
			englishTranslations?.common?.acknowledge
	);
	const rightLabels = $derived<
		Partial<Record<PolicyRight, string | undefined>>
	>({
		'opt-out':
			translations.rights?.optOut ?? englishTranslations?.rights?.optOut,
		preferences:
			translations.rights?.preferences ??
			englishTranslations?.rights?.preferences,
	});
	const resolvedRejectText = $derived(
		rejectButtonText ?? translations.common.rejectAll
	);
	const resolvedAcceptText = $derived(
		acceptButtonText ?? translations.common.acceptAll
	);
	const resolvedCustomizeText = $derived(
		customizeButtonText ?? translations.common.customize
	);
</script>

{#if visibility.isMounted && visibility.shouldRender}
	<div use:portal>
		{#if shouldScrollLock}
			<Overlay
				{styles}
				entering={!disableAnimation}
				visible={visibility.isVisible}
			/>
		{/if}
		<div
			bind:this={visibility.bannerEl}
			class={finalClassName}
			dir={textDirection}
			data-variant={resolvedVariant}
			data-position={resolvedPosition}
			data-blocking={isBlocking ? 'true' : undefined}
			data-prompt={promptKind}
			data-model={consent.state.model}
			data-testid="consent-banner-root"
			use:scrollLock={shouldScrollLock}
		>
			<div class={noStyle ? '' : styles.cardShell || ''}>
				<Branding
					{hideBranding}
					{noStyle}
					variant="banner-tag"
					themeKey="consentBannerTag"
					data-testid="consent-banner-branding"
				/>
				<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
				<div
					class={noStyle ? '' : cardStyle.className || ''}
					data-testid="consent-banner-card"
					tabindex="-1"
					role={isBlocking ? 'dialog' : 'region'}
					aria-modal={isBlocking ? 'true' : undefined}
					aria-label={resolvedTitle}
					use:focusTrap={shouldTrapFocus}
				>
					<div
						class={noStyle ? '' : headerStyle.className || ''}
						data-testid="consent-banner-header"
					>
						<h2
							class={noStyle ? '' : titleStyle.className || ''}
							data-testid="consent-banner-title"
						>
							{resolvedTitle}
						</h2>
						<div
							class={noStyle ? '' : descriptionStyle.className || ''}
							data-context="banner"
							data-testid="consent-banner-description"
						>
							{resolvedDescription}
							{#each exemptionNotices as notice (notice)}
								<p data-testid="consent-banner-exemption-notice">{notice}</p>
							{/each}
							<InlineLegalLinks
								links={legalLinks}
								themeKey="consentBannerDescription"
								testIdPrefix="consent-banner-legal-link"
							/>
						</div>
					</div>
					<PolicyActionsRenderer
						{actionGroups}
						{primaryActions}
						{shouldFillActions}
						{direction}
						{noStyle}
						footerClassName={noStyle ? '' : footerStyle.className || ''}
						footerSubGroupClassName={noStyle
							? ''
							: footerSubGroupStyle.className || ''}
						footerTestId="consent-banner-footer"
						footerSubGroupTestId="consent-banner-footer-sub-group"
					>
						{#snippet leading()}
							{#if preferenceControls.length > 0}
								<div
									class={noStyle ? '' : rightsStyle.className || ''}
									style={rightsStyle.style
										? Object.entries(rightsStyle.style)
												.map(([key, value]) => `${key}:${value}`)
												.join(';')
										: undefined}
									data-testid="consent-banner-rights"
								>
									{#each preferenceControls as right (right)}
										<button
											type="button"
											class={noStyle ? '' : rightLinkStyle.className || ''}
											style={rightLinkStyle.style
												? Object.entries(rightLinkStyle.style)
														.map(([key, value]) => `${key}:${value}`)
														.join(';')
												: undefined}
											data-action="right"
											data-right={right}
											data-c15t-rights={consent.snapshot.policyRule.rights.join(
												' '
											)}
											data-testid={`consent-banner-right-link-${right}`}
											onclick={openPreferences}
										>
											{rightLabels[right] ?? right}
										</button>
									{/each}
								</div>
							{/if}
						{/snippet}
						{#snippet renderAction(action: string, isPrimary: boolean)}
							{#if action === 'reject'}
								<ConsentButton
									action="reject-consent"
									variant={themedActions.reject.variant ??
										(isPrimary ? 'primary' : 'neutral')}
									mode={themedActions.reject.mode ?? 'stroke'}
									closeConsentBanner
									data-action="reject"
									data-testid="consent-banner-reject-button"
								>
									{resolvedRejectText}
								</ConsentButton>
							{:else if action === 'accept'}
								<ConsentButton
									action="accept-consent"
									variant={themedActions.accept.variant ??
										(isPrimary ? 'primary' : 'neutral')}
									mode={themedActions.accept.mode ?? 'stroke'}
									closeConsentBanner
									data-action="accept"
									data-testid="consent-banner-accept-button"
								>
									{resolvedAcceptText}
								</ConsentButton>
							{:else if action === 'dismiss'}
								<ConsentButton
									action="dismiss-notice"
									variant={themedActions.dismiss.variant ??
										(isPrimary || dismissIsPrimary ? 'primary' : 'neutral')}
									mode={themedActions.dismiss.mode ?? 'stroke'}
									data-action="dismiss"
									data-testid="consent-banner-dismiss-button"
								>
									{resolvedDismissText}
								</ConsentButton>
							{:else if action === 'customize'}
								<ConsentButton
									action="open-consent-dialog"
									variant={themedActions.customize.variant ??
										(isPrimary ? 'primary' : 'neutral')}
									mode={themedActions.customize.mode ?? 'stroke'}
									data-action="customize"
									data-testid="consent-banner-customize-button"
								>
									{resolvedCustomizeText}
								</ConsentButton>
							{/if}
						{/snippet}
					</PolicyActionsRenderer>
				</div>
			</div>
		</div>
	</div>
{/if}

// packages/react/src/components/prompt/prompt.tsx
'use client';

import type * as C15tCoreTypes from '@c15t/core';
import type { PromptPosition, PromptVariant } from '@c15t/core';
/**
 * @packageDocumentation
 * Provides the main consent banner component for privacy consent management.
 * Implements an accessible, customizable banner following GDPR requirements.
 */
import actionStyles from '@c15t/ui/styles/components/consent-actions';
import styles from '@c15t/ui/styles/components/consent-banner';
import type { SurfacePresentation } from '@c15t/ui/utils';
import { Fragment } from 'react';
import type { FC, ReactNode } from 'react';

import { useHeadlessConsentUI } from '~/component-hooks/use-headless-consent-ui';
import { Box } from '~/components/shared/primitives/box';
import type { InlineLegalLinksProps } from '~/components/shared/primitives/legal-links';
import { BrandingLink } from '~/components/shared/ui/branding';
import { useComponentConfig } from '~/hooks/use-component-config';
import { useIABPolicyGuard } from '~/hooks/use-iab-policy-guard';

import { StreamedSurface } from '../shared/streamed-surface';
import { ConsentBannerRoot } from './atoms/root';
import {
	ConsentBannerAcceptButton,
	ConsentBannerCard,
	ConsentBannerCustomizeButton,
	ConsentBannerDescription,
	ConsentBannerDismissButton,
	ConsentBannerFooter,
	ConsentBannerFooterSubGroup,
	ConsentBannerHeader,
	ConsentBannerRejectButton,
	ConsentBannerRights,
	ConsentBannerTitle,
} from './components';
import { ErrorBoundary } from './error-boundary';
import { resolveBannerPrimaryActions } from './resolve-banner-primary-actions';

/**
 * Identifiers for the available buttons in the consent banner.
 * @public
 */
export type ConsentBannerButton =
	| 'reject'
	| 'accept'
	| 'customize'
	| 'dismiss'
	| 'save';

/**
 * Structure for defining the layout of buttons in the consent banner.
 * Supports nesting for grouping buttons.
 * @public
 */
export type ConsentBannerLayout = (
	| ConsentBannerButton
	| ConsentBannerButton[]
)[];

/**
 * Props for configuring and customizing the ConsentBanner component.
 *
 * @remarks
 * Provides comprehensive customization options for the consent banner's appearance
 * and behavior while maintaining compliance with privacy regulations.
 *
 * @public
 */
export interface ConsentBannerProps {
	/**
	 * When true, removes all default styling from the component
	 * @remarks Useful for implementing completely custom designs
	 * @default false
	 */
	noStyle?: boolean;

	/**
	 * Content to display as the banner's title
	 * @remarks Supports string or ReactNode for rich content
	 * @default undefined
	 */
	title?: ReactNode;

	/**
	 * Content to display as the banner's description
	 * @remarks Supports string or ReactNode for rich content
	 * @default undefined
	 */
	description?: ReactNode;

	/**
	 * Content to display on the reject button
	 * @remarks Required by GDPR for explicit consent rejection
	 * @default undefined
	 */
	rejectButtonText?: ReactNode;

	/**
	 * Content to display on the customize button
	 * @remarks Opens detailed consent preferences
	 * @default undefined
	 */
	customizeButtonText?: ReactNode;

	/**
	 * Content to display on the accept button
	 * @remarks Primary action for accepting consent preferences
	 * @default undefined
	 */
	acceptButtonText?: ReactNode;

	/**
	 * Content to display on the dismiss button
	 * @remarks Only rendered when the active policy requires a notice prompt
	 * @default undefined
	 */
	dismissButtonText?: ReactNode;

	/**
	 * Legacy setting for a blocking banner.
	 * @deprecated Use `blocking` to control focus, scroll and backdrop together.
	 */
	scrollLock?: boolean;

	/**
	 * When true, the consent banner will trap focus
	 * @remarks Useful for implementing a consent banner that traps focus
	 * @deprecated Use `blocking` to control focus, scroll and backdrop together.
	 */
	trapFocus?: boolean;

	/**
	 * When true, disables the entrance/exit animations
	 * @remarks Useful for environments where animations are not desired
	 * @default false
	 */
	disableAnimation?: boolean;

	/**
	 * Controls which legal links to display.
	 *
	 * - `undefined` (default): Shows all available legal links
	 * - `null`: Explicitly hides all legal links
	 * - Array of keys: Shows only the specified legal links
	 *
	 * @defaultValue undefined
	 *
	 * @example
	 * ```tsx
	 * // Show all links
	 * <ConsentBanner legalLinks={undefined} />
	 *
	 * // Show no links
	 * <ConsentBanner legalLinks={null} />
	 *
	 * // Show only privacy policy
	 * <ConsentBanner legalLinks={['privacyPolicy']} />
	 * ```
	 *
	 * @remarks
	 * You must set the legal links in the ConsentProvider options.
	 */
	legalLinks?: InlineLegalLinksProps['links'];

	/**
	 * When true, hides the branding tag on the banner.
	 * @default false
	 */
	hideBranding?: boolean;

	/**
	 * Defines the layout of buttons in the footer.
	 * Allows reordering and grouping of buttons.
	 *
	 * @defaultValue [['reject', 'accept'], 'customize']
	 */
	layout?: ConsentBannerLayout;

	/**
	 * Defines how footer button groups flow.
	 *
	 * @defaultValue 'row'
	 */
	direction?: SurfacePresentation['direction'];

	/**
	 * Specifies which button(s) should be highlighted as the primary action.
	 *
	 * @defaultValue 'customize'
	 */
	primaryButton?: ConsentBannerButton | ConsentBannerButton[];

	/**
	 * Which consent models this banner responds to.
	 * @default ['opt-in']
	 */
	models?: C15tCoreTypes.Model[];

	/**
	 * Override the UI source identifier sent with consent API calls.
	 * @default 'banner'
	 */
	uiSource?: string;

	/**
	 * Shape of the prompt: `floating` card, full-width `bar`, compact
	 * `widget`, or centered `wall`. Overrides `presentation.prompt.variant`.
	 * @remarks Every prompt defaults to `floating`. Notices cannot use `wall`.
	 */
	variant?: PromptVariant;

	/**
	 * Placement of the prompt. Overrides `presentation.prompt.position`.
	 * @remarks Must be valid for the resolved variant; otherwise the variant
	 * default is used and a development diagnostic is logged. Host-chosen
	 * positions are never mirrored for right-to-left text.
	 */
	position?: PromptPosition;

	/**
	 * Backdrop, scroll lock, focus trap and no outside dismissal, as one
	 * value. Overrides `presentation.prompt.blocking`.
	 * @remarks `wall` is always blocking; a notice never is.
	 */
	blocking?: boolean;
}

const ConsentBannerContent: FC<ConsentBannerProps> = ({
	noStyle: localNoStyle,
	disableAnimation: localDisableAnimation,
	scrollLock: localScrollLock,
	trapFocus: localTrapFocus,
	title,
	description,
	rejectButtonText,
	customizeButtonText,
	acceptButtonText,
	dismissButtonText,
	legalLinks,
	hideBranding = false,
	layout,
	direction,
	primaryButton,
	models,
	uiSource,
	variant,
	position,
	blocking,
}) => {
	// Outside the banner's own error boundary, which would swallow it.
	useIABPolicyGuard();
	const primaryActions =
		typeof primaryButton === 'string' ? [primaryButton] : primaryButton;
	const { banner } = useHeadlessConsentUI({
		prompt: {
			blocking,
			direction,
			layout,
			position,
			primaryActions,
			scrollLock: localScrollLock,
			trapFocus: localTrapFocus,
			variant,
		},
	});

	const resolvedScrollLock = banner.scrollLock;

	// Merge local props with global theme context
	const config = useComponentConfig({
		disableAnimation: localDisableAnimation,
		noStyle: localNoStyle,
		scrollLock: resolvedScrollLock,
		trapFocus: banner.trapFocus,
	});

	const { orderedActions } = banner;
	const allowedActions = new Set(orderedActions);
	const effectivePrimaryButton = resolveBannerPrimaryActions(
		banner.primaryActions,
		orderedActions
	);
	const resolvedLayout = banner.actionGroups;
	const resolvedDirection = banner.direction;
	const { shouldFillActions } = banner;

	const renderButton = (type: ConsentBannerButton, className?: string) => {
		if (!allowedActions.has(type)) {
			return null;
		}

		const isPrimary = effectivePrimaryButton.includes(type);

		switch (type) {
			case 'reject':
				return (
					<ConsentBannerRejectButton
						consentAction="reject"
						isPrimary={isPrimary}
						className={className}
						data-action="reject"
						data-testid="consent-banner-reject-button"
					>
						{rejectButtonText}
					</ConsentBannerRejectButton>
				);
			case 'accept':
				return (
					<ConsentBannerAcceptButton
						consentAction="accept"
						isPrimary={isPrimary}
						className={className}
						data-action="accept"
						data-testid="consent-banner-accept-button"
					>
						{acceptButtonText}
					</ConsentBannerAcceptButton>
				);
			case 'customize':
				return (
					<ConsentBannerCustomizeButton
						consentAction="customize"
						isPrimary={isPrimary}
						className={className}
						data-action="customize"
						data-testid="consent-banner-customize-button"
					>
						{customizeButtonText}
					</ConsentBannerCustomizeButton>
				);
			case 'dismiss':
				return (
					<ConsentBannerDismissButton
						consentAction="dismiss"
						isPrimary={isPrimary}
						className={className}
						data-action="dismiss"
						data-testid="consent-banner-dismiss-button"
					>
						{dismissButtonText}
					</ConsentBannerDismissButton>
				);
			case 'save':
				return null;
			default: {
				const _exhaustive: never = type;
				throw new Error(`Unhandled consent banner button type: ${_exhaustive}`);
			}
		}
	};

	return (
		<ErrorBoundary
			fallback={<div>Something went wrong with the Consent Banner.</div>}
		>
			<ConsentBannerRoot
				{...config}
				models={models}
				uiSource={uiSource}
				variant={variant}
				position={position}
				blocking={blocking}
			>
				<Box
					baseClassName={styles.cardShell}
					slotKey="banner.cardShell"
				>
					<BrandingLink
						hideBranding={hideBranding}
						variant="banner-tag"
						slotContext="banner"
						data-testid="consent-banner-branding"
					/>
					<ConsentBannerCard>
						<ConsentBannerHeader>
							<ConsentBannerTitle>{title}</ConsentBannerTitle>
							<ConsentBannerDescription legalLinks={legalLinks}>
								{description}
							</ConsentBannerDescription>
						</ConsentBannerHeader>
						<ConsentBannerFooter
							className={actionStyles.actionRoot}
							data-direction={resolvedDirection}
							data-fill={shouldFillActions ? true : undefined}
							data-split={
								resolvedLayout.length > 1 && !shouldFillActions
									? true
									: undefined
							}
						>
							<ConsentBannerRights rights={banner.preferenceControls} />
							{resolvedLayout.map((item, index) => {
								if (Array.isArray(item)) {
									const filteredItems = item.filter((subItem) =>
										allowedActions.has(subItem)
									);
									if (filteredItems.length === 0) {
										return null;
									}
									const groupKey = item.join('-');
									return (
										<ConsentBannerFooterSubGroup
											key={groupKey ? `group-${groupKey}` : `group-${index}`}
											className={actionStyles.actionGroup}
											data-direction={resolvedDirection}
											data-fill={shouldFillActions ? true : undefined}
										>
											{filteredItems.map((subItem) => (
												<Fragment key={subItem}>
													{renderButton(subItem)}
												</Fragment>
											))}
										</ConsentBannerFooterSubGroup>
									);
								}
								if (!allowedActions.has(item)) {
									return null;
								}
								return <Fragment key={item}>{renderButton(item)}</Fragment>;
							})}
						</ConsentBannerFooter>
					</ConsentBannerCard>
				</Box>
			</ConsentBannerRoot>
		</ErrorBoundary>
	);
};

/**
 * The stock banner. It reads the policy to choose its buttons, so all of
 * it renders where the server can stream it: see `StreamedSurface`.
 */
export const ConsentBanner: FC<ConsentBannerProps> = (props) => (
	<StreamedSurface>
		<ConsentBannerContent {...props} />
	</StreamedSurface>
);

/**
 * Component type definition for the ConsentBanner with its compound components.
 *
 * @remarks
 * This interface extends the base ConsentBanner component with additional sub-components
 * that can be used to compose the banner's structure. Each component is designed to be
 * fully accessible and customizable while maintaining compliance with privacy regulations.
 *
 * @public
 */
