// packages/react/src/v3/components/consent-banner/consent-banner.tsx
'use client';

/**
 * @packageDocumentation
 * Provides the main consent banner component for privacy consent management.
 * Implements an accessible, customizable banner following GDPR requirements.
 */

import styles from '@c15t/ui/styles/components/consent-banner.module.js';
import {
	type PolicyUiAction,
	type PolicyUiActionDirection,
	shouldFillPolicyActions,
} from '@c15t/ui/utils';
import { type FC, Fragment, type ReactNode } from 'react';
import type { InlineLegalLinksProps } from '~/v3/components/shared/primitives/legal-links';
import { BrandingLink } from '~/v3/components/shared/ui/branding';
import { useComponentConfig } from '~/v3/hooks/use-component-config';
import { useConsentManager } from '~/v3/hooks/use-consent-manager';
import { useHeadlessConsentUI } from '~/v3/hooks/use-headless-consent-ui';
import { useTranslations } from '~/v3/hooks/use-translations';
import { cnExt as cn } from '~/v3/utils/cn';
import { ConsentBannerRoot } from './atoms/root';
import {
	ConsentBannerAcceptButton,
	ConsentBannerCard,
	ConsentBannerCustomizeButton,
	ConsentBannerDescription,
	ConsentBannerFooter,
	ConsentBannerFooterSubGroup,
	ConsentBannerHeader,
	ConsentBannerRejectButton,
	ConsentBannerTitle,
} from './components';
import { ErrorBoundary } from './error-boundary';

/**
 * Identifiers for the available buttons in the consent banner.
 * @public
 */
export type ConsentBannerButton = 'reject' | 'accept' | 'customize';

/**
 * Structure for defining the layout of buttons in the consent banner.
 * Supports nesting for grouping buttons.
 * @public
 */
export type ConsentBannerLayout = (
	| ConsentBannerButton
	| ConsentBannerButton[]
)[];

const DEFAULT_LAYOUT: ConsentBannerLayout = [['reject', 'accept'], 'customize'];

/**
 * Props for configuring and customizing the ConsentBanner component.
 *
 * @remarks
 * Provides comprehensive customization options for the consent banner's appearance
 * and behavior while maintaining compliance with privacy regulations.
 *
 * @public
 */
export interface ConsentBannerProps {
	/**
	 * When true, removes all default styling from the component
	 * @remarks Useful for implementing completely custom designs
	 * @default false
	 */
	noStyle?: boolean;

	/**
	 * Content to display as the banner's title
	 * @remarks Supports string or ReactNode for rich content
	 * @default undefined
	 */
	title?: ReactNode;

	/**
	 * Content to display as the banner's description
	 * @remarks Supports string or ReactNode for rich content
	 * @default undefined
	 */
	description?: ReactNode;

	/**
	 * Content to display on the reject button
	 * @remarks Required by GDPR for explicit consent rejection
	 * @default undefined
	 */
	rejectButtonText?: ReactNode;

	/**
	 * Content to display on the customize button
	 * @remarks Opens detailed consent preferences
	 * @default undefined
	 */
	customizeButtonText?: ReactNode;

	/**
	 * Content to display on the accept button
	 * @remarks Primary action for accepting consent preferences
	 * @default undefined
	 */
	acceptButtonText?: ReactNode;

	/**
	 * When true, the consent banner will lock the scroll of the page
	 * @remarks Useful for implementing a consent banner that locks the scroll of the page
	 * @default false
	 */
	scrollLock?: boolean;

	/**
	 * When true, the consent banner will trap focus
	 * @remarks Useful for implementing a consent banner that traps focus
	 * @default true
	 */
	trapFocus?: boolean;

	/**
	 * When true, disables the entrance/exit animations
	 * @remarks Useful for environments where animations are not desired
	 * @default false
	 */
	disableAnimation?: boolean;

	/**
	 * Controls which legal links to display.
	 *
	 * - `undefined` (default): Shows all available legal links
	 * - `null`: Explicitly hides all legal links
	 * - Array of keys: Shows only the specified legal links
	 *
	 * @defaultValue undefined
	 *
	 * @example
	 * ```tsx
	 * // Show all links
	 * <ConsentBanner legalLinks={undefined} />
	 *
	 * // Show no links
	 * <ConsentBanner legalLinks={null} />
	 *
	 * // Show only privacy policy
	 * <ConsentBanner legalLinks={['privacyPolicy']} />
	 * ```
	 *
	 * @remarks
	 * You must set the legal links in the ConsentManagerProvider options.
	 */
	legalLinks?: InlineLegalLinksProps['links'];

	/**
	 * When true, hides the branding tag on the banner.
	 * @default false
	 */
	hideBranding?: boolean;

	/**
	 * Defines the layout of buttons in the footer.
	 * Allows reordering and grouping of buttons.
	 *
	 * @defaultValue [['reject', 'accept'], 'customize']
	 */
	layout?: ConsentBannerLayout;

	/**
	 * Defines how footer button groups flow.
	 *
	 * @defaultValue 'row'
	 */
	direction?: PolicyUiActionDirection;

	/**
	 * Specifies which button(s) should be highlighted as the primary action.
	 *
	 * @defaultValue 'customize'
	 */
	primaryButton?: ConsentBannerButton | ConsentBannerButton[];

	/**
	 * Which consent models this banner responds to.
	 * @default ['opt-in']
	 */
	models?: import('c15t').Model[];

	/**
	 * Override the UI source identifier sent with consent API calls.
	 * @default 'banner'
	 */
	uiSource?: string;
}

export const ConsentBanner: FC<ConsentBannerProps> = ({
	noStyle: localNoStyle,
	disableAnimation: localDisableAnimation,
	scrollLock: localScrollLock,
	trapFocus: localTrapFocus = true,
	title,
	description,
	rejectButtonText,
	customizeButtonText,
	acceptButtonText,
	legalLinks,
	hideBranding = false,
	layout,
	direction,
	primaryButton = 'customize',
	models,
	uiSource,
}) => {
	const { cookieBanner: consentBanner } = useTranslations();
	const { banner } = useHeadlessConsentUI();
	const { policyBanner } = useConsentManager();
	const resolvedScrollLock =
		localScrollLock ?? policyBanner.scrollLock ?? false;

	// Merge local props with global theme context
	const config = useComponentConfig({
		noStyle: localNoStyle,
		disableAnimation: localDisableAnimation,
		scrollLock: resolvedScrollLock,
		trapFocus: localTrapFocus,
	});

	const orderedActions = banner.orderedActions;
	const allowedActions = new Set(orderedActions);
	const effectivePrimaryButton =
		banner.primaryActions.length > 0 ? banner.primaryActions : primaryButton;
	const resolvedLayout: ConsentBannerLayout =
		layout ??
		((banner.layout?.length ?? 0) > 0 ? banner.actionGroups : DEFAULT_LAYOUT);
	const resolvedDirection = direction ?? banner.direction ?? 'row';
	const activeGroups = resolvedLayout
		.map((item) =>
			Array.isArray(item)
				? item.filter((action): action is PolicyUiAction =>
						allowedActions.has(action)
					)
				: allowedActions.has(item)
					? [item]
					: []
		)
		.filter((group) => group.length > 0);
	const shouldFillActions = shouldFillPolicyActions({
		uiProfile: banner.uiProfile,
		actionGroups: activeGroups,
		direction: resolvedDirection,
	});

	const renderButton = (type: ConsentBannerButton, className?: string) => {
		if (!allowedActions.has(type)) {
			return null;
		}

		const isPrimary = Array.isArray(effectivePrimaryButton)
			? effectivePrimaryButton.includes(type)
			: type === effectivePrimaryButton;

		switch (type) {
			case 'reject':
				return (
					<ConsentBannerRejectButton
						consentAction="reject"
						isPrimary={isPrimary}
						className={className}
						data-testid="consent-banner-reject-button"
					>
						{rejectButtonText}
					</ConsentBannerRejectButton>
				);
			case 'accept':
				return (
					<ConsentBannerAcceptButton
						consentAction="accept"
						isPrimary={isPrimary}
						className={className}
						data-testid="consent-banner-accept-button"
					>
						{acceptButtonText}
					</ConsentBannerAcceptButton>
				);
			case 'customize':
				return (
					<ConsentBannerCustomizeButton
						consentAction="customize"
						isPrimary={isPrimary}
						className={className}
						data-testid="consent-banner-customize-button"
					>
						{customizeButtonText}
					</ConsentBannerCustomizeButton>
				);
			default: {
				const _exhaustive: never = type;
				throw new Error(`Unhandled consent banner button type: ${_exhaustive}`);
			}
		}
	};

	return (
		<ErrorBoundary
			fallback={<div>Something went wrong with the Consent Banner.</div>}
		>
			<ConsentBannerRoot
				{...config}
				models={models}
				uiSource={uiSource}
			>
				<div className={styles.cardShell}>
					<BrandingLink
						hideBranding={hideBranding}
						variant="banner-tag"
						themeKey="consentBannerTag"
						data-testid="consent-banner-branding"
					/>
					<ConsentBannerCard aria-label={consentBanner.title}>
						<ConsentBannerHeader>
							<ConsentBannerTitle>{title}</ConsentBannerTitle>
							<ConsentBannerDescription legalLinks={legalLinks}>
								{description}
							</ConsentBannerDescription>
						</ConsentBannerHeader>
						<ConsentBannerFooter
							className={cn(
								shouldFillActions && styles.footerFill,
								resolvedDirection === 'column' && styles.footerColumn
							)}
						>
							{resolvedLayout.map((item, index) => {
								if (Array.isArray(item)) {
									const filteredItems = item.filter((subItem) =>
										allowedActions.has(subItem)
									);
									if (filteredItems.length === 0) {
										return null;
									}
									const groupKey = item.join('-');
									return (
										<ConsentBannerFooterSubGroup
											key={groupKey ? `group-${groupKey}` : `group-${index}`}
											className={cn(
												shouldFillActions && styles.footerSubGroupFill,
												resolvedDirection === 'column' &&
													styles.footerSubGroupColumn
											)}
										>
											{filteredItems.map((subItem) => (
												<Fragment key={subItem}>
													{renderButton(
														subItem,
														shouldFillActions
															? styles.actionButtonFill
															: undefined
													)}
												</Fragment>
											))}
										</ConsentBannerFooterSubGroup>
									);
								}
								if (!allowedActions.has(item)) {
									return null;
								}
								return (
									<Fragment key={item}>
										{renderButton(
											item,
											shouldFillActions ? styles.actionButtonFill : undefined
										)}
									</Fragment>
								);
							})}
						</ConsentBannerFooter>
					</ConsentBannerCard>
				</div>
			</ConsentBannerRoot>
		</ErrorBoundary>
	);
};

/**
 * Component type definition for the ConsentBanner with its compound components.
 *
 * @remarks
 * This interface extends the base ConsentBanner component with additional sub-components
 * that can be used to compose the banner's structure. Each component is designed to be
 * fully accessible and customizable while maintaining compliance with privacy regulations.
 *
 * @public
 */

// packages/svelte/src/lib/components/consent-banner.svelte
<script lang="ts">
import styles from '@c15t/ui/styles/components/consent-banner.module.js';
import {
	getTextDirection,
	resolvePolicyActionGroups,
	resolvePolicyAllowedActions,
	resolvePolicyDirection,
	resolvePolicyOrderedActions,
	resolvePolicyPrimaryActions,
	resolveTranslations,
	shouldFillPolicyActions,
} from '@c15t/ui/utils';
import type { LegalLinks as LegalLinksType, Model } from 'c15t';
import { defaultTranslationConfig } from 'c15t';
import { focusTrap } from '../actions/focus-trap';
// Banner uses custom portal/focus-trap/scroll-lock actions (not Ark UI's built-in)
// because the banner is not an Ark Dialog - it's a simpler container that
// conditionally acts as a dialog. The ConsentDialog uses Ark's Dialog which
// includes its own focus trap and scroll prevention. When transitioning from
// banner to dialog, the banner unmounts (removing its focus trap) before
// the dialog mounts (establishing Ark's focus trap), so they don't compete.
import { portal } from '../actions/portal';
import { scrollLock } from '../actions/scroll-lock';
import {
	getConsentContext,
	getThemeContext,
	setTrackingContext,
} from '../context.svelte';
import { useBannerVisibility } from '../use-banner-visibility.svelte';
import { resolveComponentStyles } from '../utils';
import Branding from './branding.svelte';
import ConsentButton from './consent-button.svelte';
import InlineLegalLinks from './inline-legal-links.svelte';
import Overlay from './overlay.svelte';
import PolicyActionsRenderer from './policy-actions-renderer.svelte';

/**
 * Button identifiers for the consent banner layout.
 */
type ConsentBannerButton = 'reject' | 'accept' | 'customize';
type ConsentBannerLayout = (ConsentBannerButton | ConsentBannerButton[])[];

const DEFAULT_LAYOUT: ConsentBannerLayout = [['reject', 'accept'], 'customize'];

let {
	noStyle: localNoStyle,
	disableAnimation: localDisableAnimation,
	scrollLock: localScrollLock,
	trapFocus: localTrapFocus = true,
	title,
	description,
	rejectButtonText,
	customizeButtonText,
	acceptButtonText,
	hideBranding = false,
	legalLinks,
	layout = DEFAULT_LAYOUT,
	primaryButton = 'customize',
	models = ['opt-in'] as Model[],
	uiSource = 'banner',
	class: className,
}: {
	noStyle?: boolean;
	disableAnimation?: boolean;
	scrollLock?: boolean;
	trapFocus?: boolean;
	title?: string;
	description?: string;
	rejectButtonText?: string;
	customizeButtonText?: string;
	acceptButtonText?: string;
	hideBranding?: boolean;
	legalLinks?: (keyof LegalLinksType)[] | null;
	layout?: ConsentBannerLayout;
	primaryButton?: ConsentBannerButton | ConsentBannerButton[];
	models?: Model[];
	uiSource?: string;
	class?: string;
} = $props();

const consent = getConsentContext();
const theme = getThemeContext();
setTrackingContext({
	get uiSource() {
		return uiSource;
	},
});

const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);
const disableAnimation = $derived(
	localDisableAnimation ?? theme.disableAnimation ?? false
);
const shouldTrapFocus = $derived(localTrapFocus ?? theme.trapFocus ?? true);
const shouldScrollLock = $derived(localScrollLock ?? theme.scrollLock ?? false);

// Translations
const translations = $derived(
	resolveTranslations(consent.state.translationConfig, defaultTranslationConfig)
);
const textDirection = $derived(
	getTextDirection(consent.state.translationConfig?.defaultLanguage)
);

// Visibility logic
const shouldShowBanner = $derived(
	consent.state.activeUI === 'banner' && models.includes(consent.state.model)
);

const visibility = useBannerVisibility(
	() => shouldShowBanner,
	() => disableAnimation
);

// Styling - per-element theme key resolution matching React
const rootStyle = $derived(
	resolveComponentStyles(
		'consentBanner',
		theme.theme,
		{
			baseClassName: [
				styles.root,
				textDirection === 'ltr' ? styles.bottomLeft : styles.bottomRight,
			],
			className,
			noStyle,
		},
		noStyle
	)
);

const cardStyle = $derived(
	resolveComponentStyles(
		'consentBannerCard',
		theme.theme,
		{ baseClassName: styles.card, noStyle },
		noStyle
	)
);

const headerStyle = $derived(
	resolveComponentStyles(
		'consentBannerHeader',
		theme.theme,
		{ baseClassName: styles.header, noStyle },
		noStyle
	)
);

const titleStyle = $derived(
	resolveComponentStyles(
		'consentBannerTitle',
		theme.theme,
		{ baseClassName: styles.title, noStyle },
		noStyle
	)
);

const descriptionStyle = $derived(
	resolveComponentStyles(
		'consentBannerDescription',
		theme.theme,
		{ baseClassName: styles.description, noStyle },
		noStyle
	)
);

const footerStyle = $derived(
	resolveComponentStyles(
		'consentBannerFooter',
		theme.theme,
		{ baseClassName: styles.footer, noStyle },
		noStyle
	)
);

const footerSubGroupStyle = $derived(
	resolveComponentStyles(
		'consentBannerFooterSubGroup',
		theme.theme,
		{ baseClassName: styles.footerSubGroup, noStyle },
		noStyle
	)
);

const finalClassName = $derived(
	noStyle
		? rootStyle.className || ''
		: `${rootStyle.className || ''} ${visibility.isVisible ? styles.bannerVisible : styles.bannerHidden}`
);

// Button helpers
const allowedActions = $derived(
	resolvePolicyAllowedActions({
		allowedActions: consent.state.policyBanner.allowedActions,
	})
);

const resolvedLayout = $derived(
	layout ??
		((consent.state.policyBanner.layout?.length ?? 0) > 0
			? consent.state.policyBanner.layout
			: DEFAULT_LAYOUT)
);

const orderedActions = $derived(
	resolvePolicyOrderedActions({
		allowedActions,
		layout: resolvedLayout,
	})
);

const actionGroups = $derived(
	resolvePolicyActionGroups({
		allowedActions,
		layout: resolvedLayout,
	})
);

const direction = $derived(
	resolvePolicyDirection(consent.state.policyBanner.direction)
);

const effectivePrimaryActions = $derived.by(() => {
	if ((consent.state.policyBanner.primaryActions?.length ?? 0) > 0) {
		return consent.state.policyBanner.primaryActions ?? [];
	}

	return Array.isArray(primaryButton) ? primaryButton : [primaryButton];
});

const primaryActions = $derived(
	resolvePolicyPrimaryActions({
		orderedActions,
		primaryActions: effectivePrimaryActions,
	})
);

const shouldFillActions = $derived(
	shouldFillPolicyActions({
		uiProfile: consent.state.policyBanner.uiProfile,
		actionGroups,
		direction,
	})
);

// Resolved texts
const resolvedTitle = $derived(title ?? translations.cookieBanner.title);
const resolvedDescription = $derived(
	description ?? translations.cookieBanner.description
);
const resolvedRejectText = $derived(
	rejectButtonText ?? translations.common.rejectAll
);
const resolvedAcceptText = $derived(
	acceptButtonText ?? translations.common.acceptAll
);
const resolvedCustomizeText = $derived(
	customizeButtonText ?? translations.common.customize
);
</script>

{#if visibility.isMounted && visibility.shouldRender}
	<div use:portal>
		{#if shouldScrollLock}
			<Overlay visible={visibility.isVisible} />
		{/if}
		<div
			bind:this={visibility.bannerEl}
			class={finalClassName}
			dir={textDirection}
			data-testid="consent-banner-root"
			use:scrollLock={shouldScrollLock}
		>
			<div class={noStyle ? '' : styles.cardShell || ''}>
				<Branding
					{hideBranding}
					{noStyle}
					variant="banner-tag"
					themeKey="consentBannerTag"
					data-testid="consent-banner-branding"
				/>
				<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
				<div
					class={noStyle ? '' : cardStyle.className || ''}
					data-testid="consent-banner-card"
					tabindex={shouldTrapFocus ? -1 : undefined}
					role={shouldTrapFocus ? 'dialog' : undefined}
					aria-modal={shouldTrapFocus ? 'true' : undefined}
					aria-label={resolvedTitle}
					use:focusTrap={shouldTrapFocus}
				>
					<div class={noStyle ? '' : headerStyle.className || ''} data-testid="consent-banner-header">
						<div class={noStyle ? '' : titleStyle.className || ''} data-testid="consent-banner-title">
							{resolvedTitle}
						</div>
						<div
							class={noStyle ? '' : descriptionStyle.className || ''}
							data-testid="consent-banner-description"
						>
							{resolvedDescription}
							<InlineLegalLinks
								links={legalLinks}
								themeKey="consentBannerDescription"
								testIdPrefix="consent-banner-legal-link"
							/>
						</div>
					</div>
					<PolicyActionsRenderer
						actionGroups={actionGroups}
						primaryActions={primaryActions}
						shouldFillActions={shouldFillActions}
						{direction}
						footerClassName={noStyle ? '' : footerStyle.className || ''}
						footerFillClassName={styles.footerFill || ''}
						footerColumnClassName={styles.footerColumn || ''}
						footerSubGroupClassName={noStyle ? '' : footerSubGroupStyle.className || ''}
						footerSubGroupFillClassName={styles.footerSubGroupFill || ''}
						footerSubGroupColumnClassName={styles.footerSubGroupColumn || ''}
						actionButtonFillClassName={styles.actionButtonFill || ''}
						footerTestId="consent-banner-footer"
						footerSubGroupTestId="consent-banner-footer-sub-group"
					>
						{#snippet renderAction(action: string, isPrimary: boolean, actionClassName?: string)}
							{#if action === 'reject'}
								<ConsentButton
									action="reject-consent"
									variant={isPrimary ? 'primary' : 'neutral'}
									closeConsentBanner
									class={actionClassName}
									data-testid="consent-banner-reject-button"
								>
									{resolvedRejectText}
								</ConsentButton>
							{:else if action === 'accept'}
								<ConsentButton
									action="accept-consent"
									variant={isPrimary ? 'primary' : 'neutral'}
									closeConsentBanner
									class={actionClassName}
									data-testid="consent-banner-accept-button"
								>
									{resolvedAcceptText}
								</ConsentButton>
							{:else if action === 'customize'}
								<ConsentButton
									action="open-consent-dialog"
									variant={isPrimary ? 'primary' : 'neutral'}
									class={actionClassName}
									data-testid="consent-banner-customize-button"
								>
									{resolvedCustomizeText}
								</ConsentButton>
							{/if}
						{/snippet}
					</PolicyActionsRenderer>
				</div>
			</div>
		</div>
	</div>
{/if}
