// packages/vue/src/runtime/components/iab-stack-item.vue
<script setup lang="ts">
import dialogStyles from '@c15t/ui/styles/components/iab-consent-dialog';
/**
 * A TCF stack: one toggle standing for the purposes it absorbed.
 *
 * Built on the same `PreferenceItem` primitive as the purpose rows, so the
 * purposes it nests stay in the DOM while it is closed — which is what
 * lets the four adapters be compared row for row.
 */
import switchStyles from '@c15t/ui/styles/components/switch';
import { computed, ref, toValue } from 'vue';

import {
	useConsentConfig,
	useConsentInit,
	useIabTranslations,
} from '#c15t/composables';

import {
	PreferenceItemContent,
	PreferenceItemControl,
	PreferenceItemHeader,
	PreferenceItemLeading,
	PreferenceItemMeta,
	PreferenceItemRoot,
	PreferenceItemTitle,
	PreferenceItemTrigger,
	SwitchRoot,
	SwitchThumb,
} from '../primitives';
import type { IabProcessedPurpose, IabVendorId } from './iab-purpose-item.vue';
import IabPurposeItem from './iab-purpose-item.vue';
import ChevronRightIcon from './icons/chevron-right-icon.vue';

export interface IabProcessedStack {
	id: number;
	name: string;
	description: string;
	purposes: IabProcessedPurpose[];
}

const props = defineProps<{
	stack: IabProcessedStack;
	consents: Record<number, boolean>;
	vendorConsents: Record<string, boolean>;
	vendorLegitimateInterests?: Record<string, boolean>;
	purposeLegitimateInterests?: Record<number, boolean>;
}>();

const emit = defineEmits<{
	toggle: [purposeId: number, value: boolean];
	vendorToggle: [vendorId: IabVendorId, value: boolean];
	vendorClick: [vendorId: IabVendorId];
	purposeLegitimateInterestToggle: [purposeId: number, value: boolean];
	vendorLegitimateInterestToggle: [vendorId: IabVendorId, value: boolean];
}>();

const isExpanded = ref(false);
const config = useConsentConfig();
const init = useConsentInit();

const iabT = useIabTranslations();

const allEnabled = computed(() =>
	props.stack.purposes.every((purpose) => props.consents[purpose.id] ?? false)
);

const someEnabled = computed(
	() =>
		props.stack.purposes.some(
			(purpose) => props.consents[purpose.id] ?? false
		) && !allEnabled.value
);

const totalVendors = computed(
	() =>
		new Set(
			props.stack.purposes.flatMap((purpose) =>
				purpose.vendors.map((vendor) => vendor.id)
			)
		).size
);

const partnerLabel = computed(() =>
	totalVendors.value === 1
		? iabT.value?.preferenceCenter?.vendorList?.partnerSingular
		: iabT.value?.preferenceCenter?.vendorList?.partnerPlural
);

const stackChecked = computed({
	get: () => allEnabled.value,
	set: (value: boolean) => {
		for (const purpose of props.stack.purposes) {
			emit('toggle', purpose.id, value);
			for (const vendor of purpose.vendors) {
				if (!vendor.usesLegitimateInterest) {
					emit('vendorToggle', vendor.id, value);
				}
			}
		}
	},
});
</script>

<template>
	<PreferenceItemRoot
		v-model:open="isExpanded"
		v-bind="config.components?.['iab-stack-item']?.root"
		:class="dialogStyles.stackItem"
		:data-testid="`stack-item-${stack.id}`"
		no-style
	>
		<div
			v-bind="config.components?.['iab-stack-item']?.header"
			:class="dialogStyles.stackHeader"
		>
			<PreferenceItemTrigger
				v-bind="config.components?.['iab-stack-item']?.trigger"
				:class="dialogStyles.stackTrigger"
			>
				<PreferenceItemLeading>
					<ChevronRightIcon
						:class="dialogStyles.purposeArrow"
						:expanded="isExpanded"
					/>
				</PreferenceItemLeading>
				<PreferenceItemHeader :class="dialogStyles.stackInfo">
					<PreferenceItemTitle :class="dialogStyles.stackName">
						{{ stack.name }}
					</PreferenceItemTitle>
					<PreferenceItemMeta :class="dialogStyles.stackMeta">
						{{ totalVendors }} {{ partnerLabel }}
					</PreferenceItemMeta>
				</PreferenceItemHeader>
			</PreferenceItemTrigger>
			<PreferenceItemControl :class="dialogStyles.stackControls">
				<template v-if="someEnabled">
					<span :class="dialogStyles.srOnly">Partially enabled</span>
					<div :class="dialogStyles.partialIndicator" />
				</template>
				<SwitchRoot
					v-model="stackChecked"
					v-bind="config.components?.switch?.root"
					:aria-label="stack.name"
					:class="switchStyles.root"
					data-size="medium"
				>
					<span
						v-bind="config.components?.switch?.track"
						data-slot="switch-track"
						:class="switchStyles.track"
					>
						<SwitchThumb
							v-bind="config.components?.switch?.thumb"
							:class="switchStyles.thumb"
						/>
					</span>
				</SwitchRoot>
			</PreferenceItemControl>
		</div>

		<PreferenceItemContent>
			<div :class="dialogStyles.stackDescription">
				<p>{{ stack.description }}</p>
			</div>
			<div
				v-bind="config.components?.['iab-stack-item']?.content"
				:class="dialogStyles.stackContent"
			>
				<IabPurposeItem
					v-for="purpose in stack.purposes"
					:key="purpose.id"
					:purpose="purpose"
					:is-enabled="consents[purpose.id] ?? false"
					:vendor-consents="vendorConsents"
					:vendor-legitimate-interests="vendorLegitimateInterests"
					:purpose-legitimate-interests="purposeLegitimateInterests"
					@toggle="(value) => emit('toggle', purpose.id, value)"
					@vendor-toggle="
						(vendorId, value) => emit('vendorToggle', vendorId, value)
					"
					@vendor-click="(vendorId) => emit('vendorClick', vendorId)"
					@vendor-legitimate-interest-toggle="
						(vendorId, value) =>
							emit('vendorLegitimateInterestToggle', vendorId, value)
					"
					@purpose-legitimate-interest-toggle="
						(value) =>
							emit('purposeLegitimateInterestToggle', purpose.id, value)
					"
				/>
			</div>
		</PreferenceItemContent>
	</PreferenceItemRoot>
</template>

// packages/svelte/src/lib/components/iab-stack-item.svelte
<script lang="ts">
	import styles from '@c15t/ui/styles/components/iab-consent-dialog.module.js';
	import { switchVariants } from '@c15t/ui/styles/primitives';
	import type { IABTranslations } from '../iab-translations';
	import type { ProcessedStack, VendorId } from '../iab-types';
	import { PreferenceItem, Switch } from '../primitives';
	import IABPurposeItem from './iab-purpose-item.svelte';
	import ChevronRightIcon from './icons/chevron-right-icon.svelte';

	const sw = switchVariants();

	let {
		stack,
		consents,
		onToggle,
		vendorConsents,
		onVendorToggle,
		onVendorClick,
		vendorLegitimateInterests = {},
		onVendorLegitimateInterestToggle,
		purposeLegitimateInterests = {},
		onPurposeLegitimateInterestToggle,
		noStyle = false,
		iabT,
	}: {
		stack: ProcessedStack;
		consents: Record<number, boolean>;
		onToggle: (purposeId: number, value: boolean) => void;
		vendorConsents: Record<string, boolean>;
		onVendorToggle: (vendorId: VendorId, value: boolean) => void;
		onVendorClick: (vendorId: VendorId) => void;
		vendorLegitimateInterests?: Record<string, boolean>;
		onVendorLegitimateInterestToggle?: (
			vendorId: VendorId,
			value: boolean
		) => void;
		purposeLegitimateInterests?: Record<number, boolean>;
		onPurposeLegitimateInterestToggle?: (
			purposeId: number,
			value: boolean
		) => void;
		noStyle?: boolean;
		iabT: IABTranslations;
	} = $props();

	let isExpanded = $state(false);
	let stackChecked = $state(false);

	const allEnabled = $derived(
		stack.purposes.every((p) => consents[p.id] ?? false)
	);
	const someEnabled = $derived(
		stack.purposes.some((p) => consents[p.id] ?? false) && !allEnabled
	);

	$effect(() => {
		stackChecked = allEnabled;
	});

	function handleStackToggle(value: boolean) {
		for (const purpose of stack.purposes) {
			onToggle(purpose.id, value);
			for (const vendor of purpose.vendors) {
				if (!vendor.usesLegitimateInterest) {
					onVendorToggle(vendor.id, value);
				}
			}
		}
	}

	const totalVendors = $derived(
		new Set(stack.purposes.flatMap((p) => p.vendors.map((v) => v.id))).size
	);
</script>

<PreferenceItem.Root
	bind:open={isExpanded}
	class={noStyle ? '' : styles.stackItem || ''}
	data-testid={`stack-item-${stack.id}`}
	noStyle
>
	<div class={noStyle ? '' : styles.stackHeader || ''}>
		<PreferenceItem.Trigger class={noStyle ? '' : styles.stackTrigger || ''}>
			<PreferenceItem.Leading class={noStyle ? '' : styles.purposeArrow || ''}>
				<ChevronRightIcon />
			</PreferenceItem.Leading>
			<PreferenceItem.Header class={noStyle ? '' : styles.stackInfo || ''}>
				<PreferenceItem.Title class={noStyle ? '' : styles.stackName || ''}>
					{stack.name}
				</PreferenceItem.Title>
				{#if !isExpanded}
					<PreferenceItem.Meta class={noStyle ? '' : styles.stackMeta || ''}>
						{totalVendors}
						{totalVendors === 1
							? iabT.preferenceCenter.vendorList.partnerSingular
							: iabT.preferenceCenter.vendorList.partnerPlural}
					</PreferenceItem.Meta>
				{/if}
			</PreferenceItem.Header>
		</PreferenceItem.Trigger>
		<PreferenceItem.Control class={noStyle ? '' : styles.stackControls || ''}>
			{#if someEnabled}
				<span class="sr-only">Partially enabled</span>
				<div class={noStyle ? '' : styles.partialIndicator || ''}></div>
			{/if}
			<Switch.Root
				aria-label={stack.name}
				bind:checked={stackChecked}
				onclick={() => handleStackToggle(stackChecked)}
				class={noStyle ? '' : sw.root()}
			>
				<Switch.Control class={noStyle ? '' : sw.track()}>
					<Switch.Thumb class={noStyle ? '' : sw.thumb()} />
				</Switch.Control>
			</Switch.Root>
		</PreferenceItem.Control>
	</div>

	<PreferenceItem.Content>
		<div class={noStyle ? '' : styles.stackDescription || ''}>
			<p>{stack.description}</p>
			<p class={noStyle ? '' : styles.stackMeta || ''}>
				{totalVendors}
				{totalVendors === 1
					? iabT.preferenceCenter.vendorList.partnerSingular
					: iabT.preferenceCenter.vendorList.partnerPlural}
			</p>
		</div>
		<div class={noStyle ? '' : styles.stackContent || ''}>
			{#each stack.purposes as purpose (purpose.id)}
				<IABPurposeItem
					{purpose}
					isEnabled={consents[purpose.id] ?? false}
					onToggle={(value) => onToggle(purpose.id, value)}
					{vendorConsents}
					{onVendorToggle}
					{onVendorClick}
					{vendorLegitimateInterests}
					{onVendorLegitimateInterestToggle}
					{purposeLegitimateInterests}
					{onPurposeLegitimateInterestToggle}
					{noStyle}
					{iabT}
				/>
			{/each}
		</div>
	</PreferenceItem.Content>
</PreferenceItem.Root>
