// packages/react/src/v3/components/iab-consent-banner/iab-consent-banner.tsx
'use client';

/**
 * @packageDocumentation
 * Provides the IAB TCF 2.3 compliant cookie banner component.
 * Implements an accessible, pre-built banner following IAB requirements.
 */

import actionStyles from '@c15t/ui/styles/v3/consent-actions';
import styles from '@c15t/ui/styles/v3/iab-consent-banner';
import { type FC, type RefObject, useRef } from 'react';
import { useHeadlessIABConsentUI } from '~/v3/component-hooks/use-headless-iab-consent-ui';
import { Box } from '~/v3/components/shared/primitives/box';
import { BrandingLink } from '~/v3/components/shared/ui/branding';
import * as Button from '~/v3/components/shared/ui/button';
import { useComponentConfig } from '~/v3/hooks/use-component-config';
import { useFocusTrap } from '~/v3/hooks/use-focus-trap';
import { useIABConsentManager } from '~/v3/hooks/use-iab-consent-manager';
import { useIABTranslations } from '../iab-consent-dialog/use-iab-translations';
import { IABConsentBannerRoot } from './atoms/root';

/**
 * Props for the IABConsentBanner component.
 * @public
 */
export interface IABConsentBannerProps {
	/**
	 * When true, removes all default styling from the component.
	 * @default false
	 */
	noStyle?: boolean;

	/**
	 * When true, disables entrance/exit animations.
	 * @default false
	 */
	disableAnimation?: boolean;

	/**
	 * When true, locks page scroll when the banner is visible.
	 * @default true
	 */
	scrollLock?: boolean;

	/**
	 * When true, traps keyboard focus within the banner.
	 * @default true
	 */
	trapFocus?: boolean;

	/**
	 * Specifies which button should be highlighted as primary.
	 * @default 'customize'
	 */
	primaryButton?: 'reject' | 'accept' | 'customize';

	/**
	 * Which consent models this banner responds to.
	 * @default ['iab']
	 */
	models?: import('c15t').Model[];

	/**
	 * Override the UI source identifier sent with consent API calls.
	 * @default 'iab_banner'
	 */
	uiSource?: string;
}

/**
 * IAB TCF 2.3 compliant cookie consent banner.
 *
 * @remarks
 * This component implements the required IAB TCF 2.3 UI elements:
 * - Partner count disclosure
 * - Purpose summary
 * - Legitimate interest notice
 * - Accept All / Reject All / Customize buttons
 *
 * The banner only renders when IAB mode is enabled in the consent manager.
 *
 * @example
 * ```tsx
 * <ConsentManagerProvider options={{ iab: { enabled: true, cmpId: 000, vendors: [1, 2, 10] } }}>
 *   <IABConsentBanner />
 * </ConsentManagerProvider>
 * ```
 *
 * @public
 */
export const IABConsentBanner: FC<IABConsentBannerProps> = ({
	noStyle: localNoStyle,
	disableAnimation: localDisableAnimation,
	scrollLock: localScrollLock,
	trapFocus: localTrapFocus = true,
	primaryButton = 'customize',
	models,
	uiSource,
}) => {
	const iabT = useIABTranslations();
	const {
		iab: iabState,
		banner,
		openVendorsDialog,
		performBannerAction,
	} = useHeadlessIABConsentUI();
	const { policyBanner } = useIABConsentManager();
	const resolvedScrollLock = localScrollLock ?? policyBanner.scrollLock ?? true;

	const cardRef = useRef<HTMLDivElement>(null);

	// Merge local props with global theme context
	const config = useComponentConfig({
		noStyle: localNoStyle,
		disableAnimation: localDisableAnimation,
		scrollLock: resolvedScrollLock,
		trapFocus: localTrapFocus,
	});

	// Handle button actions
	const handleAcceptAll = () => {
		void performBannerAction('accept');
	};

	const handleRejectAll = () => {
		void performBannerAction('reject');
	};

	const handleCustomize = () => {
		void performBannerAction('customize');
	};

	const handleViewVendors = () => {
		openVendorsDialog();
	};

	// Focus trap
	useFocusTrap(Boolean(config.trapFocus), cardRef as RefObject<HTMLElement>);

	const isPrimary = (button: 'reject' | 'accept' | 'customize') =>
		button === primaryButton;

	// Don't render if IAB is disabled (e.g., server returned null GVL) or calculations not complete
	if (!iabState?.config.enabled || !banner.isReady) {
		return null;
	}

	// Replace {partnerCount} placeholder in description
	const descriptionText = iabT.banner.description.replace(
		'{partnerCount}',
		String(banner.vendorCount)
	);

	// Replace {count} placeholder in partners link
	const partnersLinkText = iabT.banner.partnersLink.replace(
		'{count}',
		String(banner.vendorCount)
	);

	const scopeNotice = iabT.banner.scopeServiceSpecific;

	return (
		<IABConsentBannerRoot
			{...config}
			models={models}
			uiSource={uiSource}
		>
			<Box baseClassName={styles.cardShell}>
				<BrandingLink
					hideBranding={false}
					variant="banner-tag"
					themeKey="iabConsentBannerTag"
					data-testid="iab-consent-banner-branding"
				/>
				<Box
					ref={cardRef}
					baseClassName={styles.card}
					themeKey="iabConsentBannerCard"
					tabIndex={0}
					role="dialog"
					aria-modal={config.trapFocus ? 'true' : undefined}
					aria-label={iabT.banner.title}
					data-testid="iab-consent-banner-card"
				>
					{/* Header */}
					<Box
						baseClassName={styles.header}
						themeKey="iabConsentBannerHeader"
						data-testid="iab-consent-banner-header"
					>
						<h2 className={styles.title}>{iabT.banner.title}</h2>
						<p className={styles.description}>
							{descriptionText.split(partnersLinkText)[0]}
							<button
								type="button"
								className={styles.partnersLink}
								onClick={handleViewVendors}
								onMouseEnter={() => {
									// Prefetch vendor list on hover
								}}
							>
								{partnersLinkText}
							</button>
							{descriptionText.split(partnersLinkText)[1]}
						</p>
						<ul className={styles.purposeList}>
							{banner.displayItems.map((name, index) => (
								<li key={index}>{name}</li>
							))}
							{banner.remainingCount > 0 && (
								<li className={styles.purposeMore}>
									{iabT.banner.andMore.replace(
										'{count}',
										String(banner.remainingCount)
									)}
								</li>
							)}
						</ul>
						<p className={styles.legitimateInterestNotice}>
							{iabT.banner.legitimateInterestNotice} {scopeNotice}
						</p>
					</Box>

					{/* Footer with buttons */}
					<Box
						baseClassName={styles.footer}
						className={actionStyles.actionRoot}
						data-direction="row"
						data-split={true}
						themeKey="iabConsentBannerFooter"
						data-testid="iab-consent-banner-footer"
					>
						<div
							className={actionStyles.actionGroup}
							data-direction="row"
						>
							<Button.Root
								variant={isPrimary('reject') ? 'primary' : 'neutral'}
								mode="stroke"
								size="small"
								onClick={handleRejectAll}
								data-action="reject"
								data-testid="iab-consent-banner-reject-button"
							>
								{iabT.common.rejectAll}
							</Button.Root>
							<Button.Root
								variant={isPrimary('accept') ? 'primary' : 'neutral'}
								mode={isPrimary('accept') ? 'filled' : 'stroke'}
								size="small"
								onClick={handleAcceptAll}
								data-action="accept"
								data-testid="iab-consent-banner-accept-button"
							>
								{iabT.common.acceptAll}
							</Button.Root>
						</div>
						<Button.Root
							variant={isPrimary('customize') ? 'primary' : 'neutral'}
							mode={isPrimary('customize') ? 'filled' : 'stroke'}
							size="small"
							onClick={handleCustomize}
							data-action="customize"
							data-testid="iab-consent-banner-customize-button"
						>
							{iabT.common.customize}
						</Button.Root>
					</Box>
				</Box>
			</Box>
		</IABConsentBannerRoot>
	);
};

// packages/svelte/src/lib/components/iab-consent-banner.svelte
<script lang="ts">
	import type { Model } from '@c15t/core';
	import actionStyles from '@c15t/ui/styles/components/consent-actions';
	import styles from '@c15t/ui/styles/components/iab-consent-banner';
	import { buttonVariants } from '@c15t/ui/styles/primitives';
	import { getTextDirection } from '@c15t/ui/utils';

	import { focusTrap } from '../actions/focus-trap';
	import { portal } from '../actions/portal';
	import { scrollLock } from '../actions/scroll-lock';
	import { getConsentContext, getThemeContext } from '../context.svelte';
	import { getIABTranslations } from '../iab-translations';
	import { getIABBannerDisplayItems } from '../iab-types';
	import { useBannerVisibility } from '../use-banner-visibility.svelte';
	import { resolveComponentStyles } from '../utils';
	import Branding from './branding.svelte';
	import Overlay from './overlay.svelte';

	let {
		noStyle: localNoStyle,
		disableAnimation: localDisableAnimation,
		scrollLock: localScrollLock,
		trapFocus: localTrapFocus = true,
		hideBranding = false,
		primaryButton = 'customize' as 'reject' | 'accept' | 'customize',
		models = ['iab'] as Model[],
		class: className,
	}: {
		noStyle?: boolean;
		disableAnimation?: boolean;
		scrollLock?: boolean;
		trapFocus?: boolean;
		hideBranding?: boolean;
		primaryButton?: 'reject' | 'accept' | 'customize';
		models?: Model[];
		class?: string;
	} = $props();

	const consent = getConsentContext();
	const theme = getThemeContext();

	const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);
	const disableAnimation = $derived(
		localDisableAnimation ?? theme.disableAnimation ?? false
	);
	const shouldTrapFocus = $derived(localTrapFocus ?? theme.trapFocus ?? true);
	const shouldScrollLock = $derived(
		localScrollLock ?? theme.scrollLock ?? false
	);

	// IAB state
	const iabState = $derived(consent.state.iab);

	// Translations
	const iabT = $derived(getIABTranslations(consent.state.translationConfig));
	const textDirection = $derived(
		getTextDirection(consent.state.translationConfig?.defaultLanguage)
	);

	// Visibility logic
	const shouldShowBanner = $derived(
		consent.state.activeUI === 'banner' &&
			models.includes(consent.state.model) &&
			iabState?.config.enabled === true
	);

	const visibility = useBannerVisibility(
		() => shouldShowBanner,
		() => disableAnimation
	);

	// Vendor count from GVL + custom vendors
	const vendorCount = $derived.by(() => {
		if (!iabState?.gvl) {
			return 0;
		}
		const gvlVendorCount = Object.keys(iabState.gvl.vendors).length;
		const customVendorCount = iabState.nonIABVendors?.length ?? 0;
		return gvlVendorCount + customVendorCount;
	});

	// Display items: stacks + purposes + special features (max 5)
	const displayItems = $derived.by(() => {
		if (!iabState?.gvl) {
			return { displayed: [] as string[], isReady: false, remainingCount: 0 };
		}
		const result = getIABBannerDisplayItems(iabState.gvl);
		return { ...result, isReady: true };
	});

	// Handlers
	const handleAcceptAll = function handleAcceptAll() {
		iabState?.acceptAll();
		iabState?.save();
		consent.state.setActiveUI('none');
	};

	const handleRejectAll = function handleRejectAll() {
		iabState?.rejectAll();
		iabState?.save();
		consent.state.setActiveUI('none');
	};

	const handleCustomize = function handleCustomize() {
		iabState?.setPreferenceCenterTab('purposes');
		consent.state.setActiveUI('dialog');
	};

	const handleViewVendors = function handleViewVendors() {
		iabState?.setPreferenceCenterTab('vendors');
		consent.state.setActiveUI('dialog');
	};

	const isPrimary = function isPrimary(
		button: 'reject' | 'accept' | 'customize'
	): boolean {
		return button === primaryButton;
	};

	const actionButtonClass = function actionButtonClass(
		button: 'reject' | 'accept' | 'customize'
	): string {
		const primary = isPrimary(button);
		return buttonVariants({
			mode: primary && button !== 'reject' ? 'filled' : 'stroke',
			size: 'small',
			variant: primary ? 'primary' : 'neutral',
		}).root();
	};

	// Styling
	const rootStyle = $derived(
		resolveComponentStyles(
			'iabConsentBanner',
			theme.theme,
			{
				baseClassName: styles.root,
				className,
				noStyle,
			},
			noStyle
		)
	);

	const finalClassName = $derived(
		noStyle
			? rootStyle.className || ''
			: `${rootStyle.className || ''} ${visibility.isVisible ? styles.bannerVisible : styles.bannerHidden}`
	);

	// Resolved texts
	const descriptionText = $derived(
		iabT.banner.description.replace('{partnerCount}', String(vendorCount))
	);
	const partnersLinkText = $derived(
		iabT.banner.partnersLink.replace('{count}', String(vendorCount))
	);
	const scopeNotice = $derived(iabT.banner.scopeServiceSpecific);

	// Split description around partners link
	const descriptionParts = $derived(descriptionText.split(partnersLinkText));
</script>

{#if visibility.isMounted && visibility.shouldRender && displayItems.isReady}
	<div use:portal>
		{#if shouldScrollLock}
			<Overlay visible={visibility.isVisible} />
		{/if}
		<div
			bind:this={visibility.bannerEl}
			class={finalClassName}
			dir={textDirection}
			data-position={textDirection === 'ltr' ? 'bottom-left' : 'bottom-right'}
			data-testid="iab-consent-banner-root"
			use:focusTrap={shouldTrapFocus}
			use:scrollLock={shouldScrollLock}
		>
			<div class={noStyle ? '' : styles.cardShell || ''}>
				<Branding
					{hideBranding}
					{noStyle}
					variant="banner-tag"
					themeKey="iabConsentBannerTag"
					data-testid="iab-consent-banner-branding"
				/>
				<div
					class={noStyle ? '' : styles.card}
					data-testid="iab-consent-banner-card"
					role={shouldTrapFocus ? 'dialog' : undefined}
					aria-modal={shouldTrapFocus ? 'true' : undefined}
					aria-label={iabT.banner.title}
				>
					<!-- Header -->
					<div
						class={noStyle ? '' : styles.header}
						data-testid="iab-consent-banner-header"
					>
						<h2 class={noStyle ? '' : styles.title}>{iabT.banner.title}</h2>
						<p class={noStyle ? '' : styles.description}>
							{descriptionParts[0]}
							<button
								type="button"
								class={noStyle ? '' : styles.partnersLink}
								onclick={handleViewVendors}
							>
								{partnersLinkText}
							</button>{descriptionParts[1] ?? ''}
						</p>
						<ul class={noStyle ? '' : styles.purposeList}>
							{#each displayItems.displayed as name (name)}
								<li>{name}</li>
							{/each}
							{#if displayItems.remainingCount > 0}
								<li class={noStyle ? '' : styles.purposeMore}>
									{iabT.banner.andMore.replace(
										'{count}',
										String(displayItems.remainingCount)
									)}
								</li>
							{/if}
						</ul>
						<p class={noStyle ? '' : styles.legitimateInterestNotice}>
							{iabT.banner.legitimateInterestNotice}
							{scopeNotice}
						</p>
					</div>

					<!-- Footer with buttons -->
					<div
						class={noStyle ? '' : `${styles.footer} ${actionStyles.actionRoot}`}
						data-testid="iab-consent-banner-footer"
						data-direction="row"
						data-split
					>
						<div
							class={noStyle ? '' : actionStyles.actionGroup}
							data-direction="row"
						>
							<button
								type="button"
								class={noStyle ? '' : actionButtonClass('reject')}
								onclick={handleRejectAll}
								data-action="reject"
								data-testid="iab-consent-banner-reject-button"
							>
								{iabT.common.rejectAll}
							</button>
							<button
								type="button"
								class={noStyle ? '' : actionButtonClass('accept')}
								onclick={handleAcceptAll}
								data-action="accept"
								data-testid="iab-consent-banner-accept-button"
							>
								{iabT.common.acceptAll}
							</button>
						</div>
						<button
							type="button"
							class={noStyle ? '' : actionButtonClass('customize')}
							onclick={handleCustomize}
							data-action="customize"
							data-testid="iab-consent-banner-customize-button"
						>
							{iabT.common.customize}
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
{/if}
