// packages/vue/src/runtime/components/iab-feature-item.vue
<script setup lang="ts">
import dialogStyles from '@c15t/ui/styles/components/iab-consent-dialog';

import '@c15t/ui/styles/components/iab-consent-dialog.css';
/**
 * One informational IAB Feature row.
 *
 * TCF Policies v5.0.b forbid showing Features next to a control that cannot
 * be disabled, so this row has no switch, no lock and no per-vendor toggles.
 * It shows the name, the description, the illustrations and the names of
 * the vendors that use the feature, with the same `PreferenceItem` structure
 * and classes as the purpose rows.
 */
import { ref } from 'vue';

import { useConsentConfig, useIabTranslations } from '#c15t/composables';

import {
	PreferenceItemContent,
	PreferenceItemHeader,
	PreferenceItemLeading,
	PreferenceItemMeta,
	PreferenceItemRoot,
	PreferenceItemTitle,
	PreferenceItemTrigger,
} from '../primitives';
import type { IabProcessedPurpose } from './iab-purpose-item.vue';
import ChevronRightIcon from './icons/chevron-right-icon.vue';

defineProps<{
	feature: IabProcessedPurpose;
	/** The row's `data-testid`, from the shared display model. */
	testId?: string;
}>();

const config = useConsentConfig();
const isExpanded = ref(false);
const showExamples = ref(false);
const showVendors = ref(false);

const iabT = useIabTranslations();

const interpolate = function interpolate(
	template: string | undefined,
	count: number
) {
	return (template ?? '').replace('{count}', String(count));
};
</script>

<template>
	<PreferenceItemRoot
		v-model:open="isExpanded"
		v-bind="config.components?.['iab-purpose-item']?.root"
		:class="dialogStyles.purposeItem"
		:data-testid="testId ?? `feature-item-${feature.id}`"
		no-style
	>
		<div
			v-bind="config.components?.['iab-purpose-item']?.header"
			:class="dialogStyles.purposeHeader"
		>
			<PreferenceItemTrigger
				v-bind="config.components?.['iab-purpose-item']?.trigger"
				:class="dialogStyles.purposeTrigger"
			>
				<PreferenceItemLeading>
					<ChevronRightIcon
						aria-hidden="true"
						:class="dialogStyles.purposeArrow"
						:expanded="isExpanded"
					/>
				</PreferenceItemLeading>
				<PreferenceItemHeader :class="dialogStyles.purposeInfo">
					<PreferenceItemTitle :class="dialogStyles.purposeName">
						{{ feature.name }}
					</PreferenceItemTitle>
					<PreferenceItemMeta :class="dialogStyles.purposeMeta">
						{{
							interpolate(
								iabT?.preferenceCenter?.purposeItem?.partners,
								feature.vendors.length
							)
						}}
					</PreferenceItemMeta>
				</PreferenceItemHeader>
			</PreferenceItemTrigger>
		</div>

		<PreferenceItemContent
			:inner-attrs="config.components?.['iab-purpose-item']?.content"
			:inner-class="dialogStyles.purposeContent"
			:no-style="false"
		>
			<p :class="dialogStyles.purposeDescription">{{ feature.description }}</p>

			<div
				v-if="feature.illustrations.length > 0"
				v-bind="config.components?.['iab-purpose-item']?.examples"
			>
				<PreferenceItemRoot
					v-model:open="showExamples"
					no-style
				>
					<PreferenceItemTrigger :class="dialogStyles.examplesToggle">
						<ChevronRightIcon
							aria-hidden="true"
							style="height: 0.75rem; width: 0.75rem"
							:expanded="showExamples"
						/>
						{{ iabT?.preferenceCenter?.purposeItem?.examples }} ({{
							feature.illustrations.length
						}})
					</PreferenceItemTrigger>
					<PreferenceItemContent :no-style="false">
						<ul :class="dialogStyles.examplesList">
							<li
								v-for="illustration in feature.illustrations"
								:key="illustration"
							>
								{{ illustration }}
							</li>
						</ul>
					</PreferenceItemContent>
				</PreferenceItemRoot>
			</div>

			<!-- Vendors using the feature: names only, no controls -->
			<div
				v-if="feature.vendors.length > 0"
				v-bind="config.components?.['iab-purpose-item']?.vendors"
			>
				<PreferenceItemRoot
					v-model:open="showVendors"
					no-style
				>
					<PreferenceItemTrigger :class="dialogStyles.vendorsToggle">
						<ChevronRightIcon
							aria-hidden="true"
							style="height: 0.75rem; width: 0.75rem"
							:expanded="showVendors"
						/>
						{{ iabT?.preferenceCenter?.vendorList?.iabVendorsHeading }} ({{
							feature.vendors.length
						}})
					</PreferenceItemTrigger>
					<PreferenceItemContent :no-style="false">
						<ul :class="dialogStyles.examplesList">
							<li
								v-for="vendor in feature.vendors"
								:key="vendor.id"
							>
								{{ vendor.name }}
							</li>
						</ul>
					</PreferenceItemContent>
				</PreferenceItemRoot>
			</div>
		</PreferenceItemContent>
	</PreferenceItemRoot>
</template>

// packages/svelte/src/lib/components/iab-feature-item.svelte
<script lang="ts">
	/**
	 * One informational IAB Feature row.
	 *
	 * TCF Policies v5.0.b forbid showing Features next to a control that
	 * cannot be disabled, so this row has no switch, no lock and no
	 * per-vendor toggles. It shows the name, the description, the
	 * illustrations and the names of the vendors that use the feature.
	 */
	import styles from '@c15t/ui/styles/components/iab-consent-dialog';

	import type { IABTranslations } from '../iab-translations';
	import type { ProcessedFeature } from '../iab-types';
	import { PreferenceItem } from '../primitives';
	import ChevronRightIcon from './icons/chevron-right-icon.svelte';

	let {
		feature,
		testId,
		noStyle = false,
		iabT,
	}: {
		feature: ProcessedFeature;
		/** The row's `data-testid`, from the shared display model. */
		testId?: string;
		noStyle?: boolean;
		iabT: IABTranslations;
	} = $props();

	let isExpanded = $state(false);
	let showExamples = $state(false);
	let showVendors = $state(false);
</script>

<PreferenceItem.Root
	bind:open={isExpanded}
	class={noStyle ? '' : styles.purposeItem || ''}
	data-testid={testId ?? `feature-item-${feature.id}`}
	noStyle
>
	<div class={noStyle ? '' : styles.purposeHeader || ''}>
		<PreferenceItem.Trigger class={noStyle ? '' : styles.purposeTrigger || ''}>
			<PreferenceItem.Leading>
				<ChevronRightIcon
					class={noStyle ? '' : styles.purposeArrow || ''}
					aria-hidden={true}
					expanded={isExpanded}
				/>
			</PreferenceItem.Leading>
			<PreferenceItem.Header class={noStyle ? '' : styles.purposeInfo || ''}>
				<PreferenceItem.Title class={noStyle ? '' : styles.purposeName || ''}>
					{feature.name}
				</PreferenceItem.Title>
				<PreferenceItem.Meta class={noStyle ? '' : styles.purposeMeta || ''}>
					{iabT.preferenceCenter.purposeItem.partners.replace(
						'{count}',
						String(feature.vendors.length)
					)}
				</PreferenceItem.Meta>
			</PreferenceItem.Header>
		</PreferenceItem.Trigger>
	</div>

	<PreferenceItem.Content
		innerClassName={noStyle ? '' : styles.purposeContent || ''}
		{noStyle}
	>
		<p class={noStyle ? '' : styles.purposeDescription || ''}>
			{feature.description}
		</p>

		<!-- Illustrations / Examples -->
		{#if feature.illustrations.length > 0}
			<div>
				<PreferenceItem.Root
					bind:open={showExamples}
					noStyle
				>
					<PreferenceItem.Trigger
						class={noStyle ? '' : styles.examplesToggle || ''}
					>
						<ChevronRightIcon
							style="height:0.75rem;width:0.75rem"
							aria-hidden={true}
							expanded={showExamples}
						/>
						{iabT.preferenceCenter.purposeItem.examples}
						({feature.illustrations.length})
					</PreferenceItem.Trigger>
					<PreferenceItem.Content {noStyle}>
						<ul class={noStyle ? '' : styles.examplesList || ''}>
							{#each feature.illustrations as illustration (illustration)}
								<li>{illustration}</li>
							{/each}
						</ul>
					</PreferenceItem.Content>
				</PreferenceItem.Root>
			</div>
		{/if}

		<!-- Vendors using the feature: names only, no controls -->
		{#if feature.vendors.length > 0}
			<div>
				<PreferenceItem.Root
					bind:open={showVendors}
					noStyle
				>
					<PreferenceItem.Trigger
						class={noStyle ? '' : styles.vendorsToggle || ''}
					>
						<ChevronRightIcon
							style="height:0.75rem;width:0.75rem"
							aria-hidden={true}
							expanded={showVendors}
						/>
						{iabT.preferenceCenter.vendorList.iabVendorsHeading}
						({feature.vendors.length})
					</PreferenceItem.Trigger>
					<PreferenceItem.Content {noStyle}>
						<ul class={noStyle ? '' : styles.examplesList || ''}>
							{#each feature.vendors as vendor (vendor.id)}
								<li>{vendor.name}</li>
							{/each}
						</ul>
					</PreferenceItem.Content>
				</PreferenceItem.Root>
			</div>
		{/if}
	</PreferenceItem.Content>
</PreferenceItem.Root>
