// packages/react/src/components/iab-prompt/iab-prompt.tsx
'use client';

import type * as C15tCoreTypes from '@c15t/core';
/**
 * @packageDocumentation
 * Provides the IAB TCF 2.4 compliant cookie banner component.
 * Implements an accessible, pre-built banner following IAB requirements.
 */
import actionStyles from '@c15t/ui/styles/components/consent-actions';
import styles from '@c15t/ui/styles/components/iab-consent-banner';
import type { FC } from 'react';

import { useHeadlessIABConsentUI } from '~/component-hooks/use-headless-iab-consent-ui';
import { Box } from '~/components/shared/primitives/box';
import { BrandingLink } from '~/components/shared/ui/branding';
import * as Button from '~/components/shared/ui/button';
import { useComponentConfig } from '~/hooks/use-component-config';
import { useIABConsentManager } from '~/hooks/use-iab-manager';
import { useUIConfig } from '~/ui-config-context';
import { mergeSlotProps } from '~/utils/merge-slot-props';

import { useIABTranslations } from '../iab-panel/use-iab-translations';
import { IABConsentBannerCard } from './atoms/card';
import { IABConsentBannerRoot } from './atoms/root';

/**
 * Props for the IABConsentBanner component.
 * @public
 */
export interface IABConsentBannerProps {
	/**
	 * When true, removes all default styling from the component.
	 * @default false
	 */
	noStyle?: boolean;

	/**
	 * When true, disables entrance/exit animations.
	 * @default false
	 */
	disableAnimation?: boolean;

	/**
	 * When true, locks page scroll when the banner is visible.
	 * @default true
	 */
	scrollLock?: boolean;

	/**
	 * When true, traps keyboard focus within the banner.
	 * @default true
	 */
	trapFocus?: boolean;

	/**
	 * Specifies which button should be highlighted as primary.
	 * @default 'customize'
	 */
	primaryButton?: 'reject' | 'accept' | 'customize';

	/**
	 * Which consent models this banner responds to.
	 * @default ['iab']
	 */
	models?: C15tCoreTypes.Model[];

	/**
	 * Override the UI source identifier sent with consent API calls.
	 * @default 'iab_banner'
	 */
	uiSource?: string;
}

/**
 * IAB TCF 2.4 compliant cookie consent banner.
 *
 * @remarks
 * This component implements the required IAB TCF 2.4 UI elements:
 * - Partner count disclosure
 * - Purpose summary
 * - Legitimate interest notice
 * - Accept All / Reject All / Customize buttons
 *
 * The banner only renders when IAB mode is enabled in the consent manager.
 *
 * @example
 * ```tsx
 * <ConsentProvider
 *   options={{
 *     mode: hosted({ url: '/api/c15t' }),
 *     iab: { cmpId: 123, vendors: [1, 2, 10] },
 *   }}
 * >
 *   <IABConsentBanner />
 * </ConsentProvider>
 * ```
 *
 * @public
 */
// oxlint-disable-next-line complexity -- Preserve established branch order and control flow.
export const IABConsentBanner: FC<IABConsentBannerProps> = ({
	noStyle: localNoStyle,
	disableAnimation: localDisableAnimation,
	scrollLock: localScrollLock,
	trapFocus: localTrapFocus,
	primaryButton = 'customize',
	models,
	uiSource,
}) => {
	const iabT = useIABTranslations();
	const {
		iab: iabState,
		banner,
		openVendorsDialog,
		performBannerAction,
	} = useHeadlessIABConsentUI();
	const { policyBanner } = useIABConsentManager({
		prompt: { scrollLock: localScrollLock, trapFocus: localTrapFocus },
	});
	const { components } = useUIConfig();
	const resolvedScrollLock = policyBanner.blocking;

	// Merge local props with global theme context
	const config = useComponentConfig({
		disableAnimation: localDisableAnimation,
		noStyle: localNoStyle,
		scrollLock: resolvedScrollLock,
		trapFocus: policyBanner.blocking,
	});

	// Handle button actions
	const handleAcceptAll = async () => {
		try {
			await performBannerAction('accept');
		} catch {
			// Keep the banner available so a failed list load or save can be retried.
		}
	};

	const handleRejectAll = async () => {
		try {
			await performBannerAction('reject');
		} catch {
			// Keep the banner available so a failed list load or save can be retried.
		}
	};

	const handleCustomize = () => {
		void performBannerAction('customize');
	};

	const handleViewVendors = () => {
		openVendorsDialog();
	};

	const isPrimary = (button: 'reject' | 'accept' | 'customize') =>
		button === primaryButton;

	// Don't render if IAB is disabled (e.g., server returned null GVL) or calculations not complete
	if (!iabState?.config.enabled || !banner.isReady) {
		return null;
	}

	// Replace {partnerCount} placeholder in description
	const descriptionText = iabT.banner.description.replace(
		'{partnerCount}',
		String(banner.vendorCount)
	);

	// Replace {count} placeholder in partners link
	const partnersLinkText = iabT.banner.partnersLink.replace(
		'{count}',
		String(banner.vendorCount)
	);

	const scopeNotice = iabT.banner.scopeServiceSpecific;
	const titleProps = mergeSlotProps(components?.['iab-banner']?.title, {
		baseClassName: styles.title,
		noStyle: config.noStyle,
	});
	const descriptionProps = mergeSlotProps(
		components?.['iab-banner']?.description,
		{
			baseClassName: styles.description,
			noStyle: config.noStyle,
		}
	);
	const partnersLinkProps = mergeSlotProps(
		components?.['iab-banner']?.partnersLink,
		{
			baseClassName: styles.partnersLink,
			noStyle: config.noStyle,
		}
	);
	const purposeListProps = mergeSlotProps(
		components?.['iab-banner']?.purposeList,
		{
			baseClassName: styles.purposeList,
			noStyle: config.noStyle,
		}
	);
	const purposeMoreProps = mergeSlotProps(
		components?.['iab-banner']?.purposeMore,
		{
			baseClassName: styles.purposeMore,
			noStyle: config.noStyle,
		}
	);
	const legitimateInterestNoticeProps = mergeSlotProps(
		components?.['iab-banner']?.legitimateInterestNotice,
		{
			baseClassName: styles.legitimateInterestNotice,
			noStyle: config.noStyle,
		}
	);
	const actionsProps = mergeSlotProps(components?.['iab-banner']?.actions, {
		baseClassName: actionStyles.actionRoot,
		'data-direction': 'row',
		'data-split': true,
		noStyle: config.noStyle,
	});
	const actionGroupProps = mergeSlotProps(
		components?.['iab-banner']?.actionGroup,
		{
			baseClassName: actionStyles.actionGroup,
			'data-direction': 'row',
			noStyle: config.noStyle,
		}
	);

	return (
		<IABConsentBannerRoot
			{...config}
			models={models}
			uiSource={uiSource}
		>
			<Box
				baseClassName={styles.cardShell}
				slotKey="iab-banner.cardShell"
			>
				<BrandingLink
					hideBranding={false}
					variant="banner-tag"
					slotContext="iab-banner"
					data-testid="iab-consent-banner-branding"
				/>
				<IABConsentBannerCard aria-label={iabT.banner.title}>
					{/* Header */}
					<Box
						baseClassName={styles.header}
						slotKey="iab-banner.header"
						data-testid="iab-consent-banner-header"
					>
						<h2 {...titleProps}>{iabT.banner.title}</h2>
						<p {...descriptionProps}>
							{descriptionText.split(partnersLinkText)[0]}
							<button
								{...partnersLinkProps}
								type="button"
								data-testid="iab-consent-banner-partners-link"
								onClick={handleViewVendors}
								onMouseEnter={() => {
									// Prefetch vendor list on hover
								}}
							>
								{partnersLinkText}
							</button>
							{descriptionText.split(partnersLinkText)[1]}
						</p>
						<ul {...purposeListProps}>
							{banner.displayItems.map((name, index) => (
								<li key={index}>{name}</li>
							))}
							{banner.remainingCount > 0 && (
								<li {...purposeMoreProps}>
									{iabT.banner.andMore.replace(
										'{count}',
										String(banner.remainingCount)
									)}
								</li>
							)}
						</ul>
						<p {...legitimateInterestNoticeProps}>
							{`${iabT.banner.legitimateInterestNotice} ${scopeNotice}`}
						</p>
					</Box>

					{/* Footer with buttons */}
					<Box
						baseClassName={styles.footer}
						slotKey="iab-banner.footer"
						data-testid="iab-consent-banner-footer"
						{...actionsProps}
					>
						<div {...actionGroupProps}>
							<Button.Root
								variant={isPrimary('reject') ? 'primary' : 'neutral'}
								mode="stroke"
								size="small"
								onClick={handleRejectAll}
								data-action="reject"
								data-testid="iab-consent-banner-reject-button"
							>
								{iabT.common.rejectAll}
							</Button.Root>
							<Button.Root
								variant={isPrimary('accept') ? 'primary' : 'neutral'}
								mode={isPrimary('accept') ? 'filled' : 'stroke'}
								size="small"
								onClick={handleAcceptAll}
								data-action="accept"
								data-testid="iab-consent-banner-accept-button"
							>
								{iabT.common.acceptAll}
							</Button.Root>
						</div>
						<div {...actionGroupProps}>
							<Button.Root
								variant={isPrimary('customize') ? 'primary' : 'neutral'}
								mode={isPrimary('customize') ? 'filled' : 'stroke'}
								size="small"
								onClick={handleCustomize}
								data-action="customize"
								data-testid="iab-consent-banner-customize-button"
							>
								{iabT.common.customize}
							</Button.Root>
						</div>
					</Box>
				</IABConsentBannerCard>
			</Box>
		</IABConsentBannerRoot>
	);
};

// packages/svelte/src/lib/components/iab-prompt.svelte
<script lang="ts">
	import {
		resolveIABBannerSummary,
		resolveConsentPresentation,
	} from '@c15t/core';
	import type { Model } from '@c15t/core';
	import buttonStyles from '@c15t/ui/styles/components/button';
	import actionStyles from '@c15t/ui/styles/components/consent-actions';
	import styles from '@c15t/ui/styles/components/iab-consent-banner';
	import { getTextDirection } from '@c15t/ui/utils';

	import { focusTrap } from '../actions/focus-trap';
	import { portal } from '../actions/portal';
	import { scrollLock } from '../actions/scroll-lock';
	import { getConsentContext, getThemeContext } from '../context.svelte';
	import { getIABTranslations } from '../iab-translations';
	import { useBannerVisibility } from '../use-banner-visibility.svelte';
	import { resolveComponentStyles } from '../utils';
	import Branding from './branding.svelte';
	import Overlay from './overlay.svelte';

	let {
		noStyle: localNoStyle,
		disableAnimation: localDisableAnimation,
		scrollLock: localScrollLock,
		trapFocus: localTrapFocus,
		hideBranding = false,
		primaryButton = 'customize' as 'reject' | 'accept' | 'customize',
		models = ['iab'] as Model[],
		class: className,
	}: {
		noStyle?: boolean;
		disableAnimation?: boolean;
		scrollLock?: boolean;
		trapFocus?: boolean;
		hideBranding?: boolean;
		primaryButton?: 'reject' | 'accept' | 'customize';
		models?: Model[];
		class?: string;
	} = $props();

	const consent = getConsentContext();
	const theme = getThemeContext();

	const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);
	const disableAnimation = $derived(
		localDisableAnimation ?? theme.disableAnimation ?? false
	);
	const presentation = $derived(
		resolveConsentPresentation({
			override: { scrollLock: localScrollLock, trapFocus: localTrapFocus },
			policy: consent.snapshot.policyRule,
			presentation: {
				prompt: {
					scrollLock: theme.scrollLock,
					trapFocus: theme.trapFocus,
					...consent.state.presentation?.prompt,
				},
			},
			surface: 'prompt',
		})
	);
	const shouldTrapFocus = $derived(presentation.blocking);
	const shouldScrollLock = $derived(presentation.blocking);

	// IAB state
	const iabState = $derived(consent.state.iab);

	// Translations
	const iabT = $derived(getIABTranslations(consent.state.translationConfig));
	const textDirection = $derived(
		getTextDirection(consent.state.translationConfig?.defaultLanguage)
	);

	// Visibility logic
	const shouldShowBanner = $derived(
		consent.state.hasConsentUi &&
			consent.state.activeUI === 'banner' &&
			models.includes(consent.state.model) &&
			iabState?.config.enabled === true
	);

	const visibility = useBannerVisibility(
		() => shouldShowBanner,
		() => disableAnimation
	);

	const summary = $derived(resolveIABBannerSummary(iabState));
	const vendorCount = $derived(summary.vendorCount);
	const displayItems = $derived({
		displayed: summary.displayItems,
		isReady: summary.isReady,
		remainingCount: summary.remainingCount,
	});

	// Handlers
	const handleSave = async function handleSave() {
		if (!iabState) {
			return;
		}
		try {
			await iabState.save();
			consent.state.setActiveUI('none');
		} catch {
			// Keep the prompt available so a later action can retry the failed load/save.
		}
	};

	const handleAcceptAll = function handleAcceptAll() {
		iabState?.acceptAll();
		return handleSave();
	};

	const handleRejectAll = function handleRejectAll() {
		iabState?.rejectAll();
		return handleSave();
	};

	const handleCustomize = function handleCustomize() {
		iabState?.setPreferenceCenterTab('purposes');
		consent.state.setActiveUI('dialog');
	};

	const handleViewVendors = function handleViewVendors() {
		iabState?.setPreferenceCenterTab('vendors');
		consent.state.setActiveUI('dialog');
	};

	const isPrimary = function isPrimary(
		button: 'reject' | 'accept' | 'customize'
	): boolean {
		return button === primaryButton;
	};

	/**
	 * The shared button stylesheet keys its variants off `data-*`, the way
	 * every other consent button in the repo does. Emitting the same
	 * attributes keeps the IAB banner's controls identical to React's.
	 */
	const actionButtonAttrs = function actionButtonAttrs(
		button: 'reject' | 'accept' | 'customize'
	) {
		const primary = isPrimary(button);
		return {
			'data-mode': primary && button !== 'reject' ? 'filled' : 'stroke',
			'data-size': 'small',
			'data-variant': primary ? 'primary' : 'neutral',
		} as const;
	};

	// Styling
	const rootStyle = $derived(
		resolveComponentStyles(
			'iabConsentBanner',
			theme.theme,
			{
				baseClassName: styles.root,
				className,
				noStyle,
			},
			noStyle
		)
	);

	const finalClassName = $derived(
		noStyle
			? rootStyle.className || ''
			: `${rootStyle.className || ''} ${visibility.isVisible ? styles.bannerVisible : styles.bannerHidden}`
	);

	// Resolved texts
	const descriptionText = $derived(
		iabT.banner.description.replace('{partnerCount}', String(vendorCount))
	);
	const partnersLinkText = $derived(
		iabT.banner.partnersLink.replace('{count}', String(vendorCount))
	);
	const scopeNotice = $derived(iabT.banner.scopeServiceSpecific);

	// Split description around partners link
	const descriptionParts = $derived(descriptionText.split(partnersLinkText));
</script>

{#if visibility.isMounted && visibility.shouldRender && displayItems.isReady}
	<div use:portal>
		{#if shouldScrollLock}
			<Overlay
				variant="iab-banner"
				visible={visibility.isVisible}
			/>
		{/if}
		<div
			bind:this={visibility.bannerEl}
			class={finalClassName}
			dir={textDirection}
			data-position={textDirection === 'ltr' ? 'bottom-left' : 'bottom-right'}
			data-testid="iab-consent-banner-root"
			tabindex="-1"
			use:scrollLock={shouldScrollLock}
		>
			<div class={noStyle ? '' : styles.cardShell || ''}>
				<Branding
					{hideBranding}
					{noStyle}
					variant="banner-tag"
					themeKey="iabConsentBannerTag"
					data-testid="iab-consent-banner-branding"
				/>
				<div
					class={noStyle ? '' : styles.card}
					data-testid="iab-consent-banner-card"
					role={shouldTrapFocus ? 'dialog' : 'region'}
					aria-modal={shouldTrapFocus ? 'true' : undefined}
					aria-label={iabT.banner.title}
					use:focusTrap={shouldTrapFocus}
				>
					<!-- Header -->
					<div
						class={noStyle ? '' : styles.header}
						data-testid="iab-consent-banner-header"
					>
						<h2 class={noStyle ? '' : styles.title}>{iabT.banner.title}</h2>
						<p class={noStyle ? '' : styles.description}>
							{descriptionParts[0]}
							<button
								type="button"
								class={noStyle ? '' : styles.partnersLink}
								data-testid="iab-consent-banner-partners-link"
								onclick={handleViewVendors}
							>
								{partnersLinkText}
							</button>{descriptionParts[1] ?? ''}
						</p>
						<ul class={noStyle ? '' : styles.purposeList}>
							{#each displayItems.displayed as name (name)}
								<li>{name}</li>
							{/each}
							{#if displayItems.remainingCount > 0}
								<li class={noStyle ? '' : styles.purposeMore}>
									{iabT.banner.andMore.replace(
										'{count}',
										String(displayItems.remainingCount)
									)}
								</li>
							{/if}
						</ul>
						<p class={noStyle ? '' : styles.legitimateInterestNotice}>
							{iabT.banner.legitimateInterestNotice}
							{scopeNotice}
						</p>
					</div>

					<!-- Footer with buttons -->
					<div
						class={noStyle ? '' : `${styles.footer} ${actionStyles.actionRoot}`}
						data-testid="iab-consent-banner-footer"
						data-direction="row"
						data-split="true"
					>
						<div
							class={noStyle ? '' : actionStyles.actionGroup}
							data-direction="row"
						>
							<button
								type="button"
								class={noStyle ? '' : buttonStyles.button}
								{...actionButtonAttrs('reject')}
								onclick={handleRejectAll}
								data-action="reject"
								data-testid="iab-consent-banner-reject-button"
							>
								{iabT.common.rejectAll}
							</button>
							<button
								type="button"
								class={noStyle ? '' : buttonStyles.button}
								{...actionButtonAttrs('accept')}
								onclick={handleAcceptAll}
								data-action="accept"
								data-testid="iab-consent-banner-accept-button"
							>
								{iabT.common.acceptAll}
							</button>
						</div>
						<div
							class={noStyle ? '' : actionStyles.actionGroup}
							data-direction="row"
						>
							<button
								type="button"
								class={noStyle ? '' : buttonStyles.button}
								{...actionButtonAttrs('customize')}
								onclick={handleCustomize}
								data-action="customize"
								data-testid="iab-consent-banner-customize-button"
							>
								{iabT.common.customize}
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{/if}
