// packages/vue/src/runtime/components/iab-consent-dialog.vue
<script setup lang="ts">
import type { PresentationAction } from '@c15t/core';
import { resolveIABDialogDisplayModel } from '@c15t/iab/headless';
import type {
	HeadlessIABDisplayRow,
	HeadlessIABDisplayStackRow,
} from '@c15t/iab/headless';
import { isDialogDismissKey } from '@c15t/ui/primitives/dialog';
import dialogStyles from '@c15t/ui/styles/components/iab-consent-dialog';
import { getTextDirection } from '@c15t/ui/utils';
import { computed, ref, Teleport, Transition, toValue, watch } from 'vue';

import {
	createDefaultIabSelection,
	useConsentActiveUI,
	useConsentConfig,
	useConsentIabSave,
	useConsentIabSelection,
	useConsentInit,
	useIabTranslations,
} from '#c15t/composables';
import type { ConsentIabSelection } from '#c15t/composables';

import { useConsentSnapshot, useHasConsentUi } from '../composables/kernel';
import { useConsentPolicyActions } from '../composables/use-consent-policy-actions';
import { useConsentScrollLock } from '../composables/use-consent-scroll-lock';
import { TabsContent, TabsList, TabsRoot, TabsTrigger } from '../primitives';
import { useFocusTrap } from '../primitives/use-focus-trap';
import ConsentActions from './consent-actions.vue';
import ConsentDialogTrigger from './consent-dialog-trigger.vue';
import ConsentTag from './consent-tag.vue';
import type { IabVendorId } from './iab-purpose-item.vue';
import IabPurposeItem from './iab-purpose-item.vue';
import IabStackItem from './iab-stack-item.vue';
import IabVendorList from './iab-vendor-list.vue';

const IAB_DIALOG_LAYOUT: (PresentationAction | PresentationAction[])[] = [
	['reject', 'accept'],
	'save',
];

/**
 * The React and Svelte IAB dialog footers carry `data-action` and no
 * test-id, so an empty map keeps Vue's buttons on the same contract —
 * `ConsentActions` only falls back to its own ids when a surface names
 * none at all.
 */
const IAB_DIALOG_ACTION_TEST_IDS: Partial<Record<PresentationAction, string>> =
	{};

const activeUI = useConsentActiveUI();
const config = useConsentConfig();
const init = useConsentInit();
const snapshot = useConsentSnapshot();
const iabSelection = useConsentIabSelection();
const save = useConsentIabSave();

const initValue = computed(() => toValue(init));
const textDirection = computed(() =>
	getTextDirection(initValue.value?.translations?.language)
);

// "Close" is core copy, not IAB copy — reading it off `iab.common` left the
// button with no accessible name.
const coreCommon = computed(
	() =>
		(
			initValue.value?.translations?.translations as
				| { common?: { close?: string } }
				| undefined
		)?.common
);
const gvl = computed(() => initValue.value?.gvl ?? null);
const customVendors = computed(() => initValue.value?.customVendors ?? []);
const draftIab = ref<ConsentIabSelection>(createDefaultIabSelection());

const hasConsentUi = useHasConsentUi();
const isOpen = computed(() => {
	if (!hasConsentUi.value) {
		return false;
	}
	const models = config.value.iabDialogModels;
	const { model } = snapshot.value.policyRule;
	const matchesModel =
		!models?.length || (model !== undefined && model !== 'none' && models.includes(model));
	return (
		activeUI.value === 'manager' &&
		snapshot.value.policyRule.model === 'iab' &&
		Boolean(gvl.value) &&
		matchesModel
	);
});
const disableAnimation = computed(() =>
	Boolean(toValue(config).disableAnimation)
);

const showDialog = computed(() => isOpen.value && Boolean(gvl.value));

const props = withDefaults(
	defineProps<{
		/**
		 * Which tab the preference centre opens on. Lets a "N partners"
		 * link land on the vendor list instead of purposes.
		 */
		initialTab?: 'purposes' | 'vendors';
	}>(),
	{ initialTab: undefined }
);

const activeTab = ref<'purposes' | 'vendors'>(props.initialTab ?? 'purposes');
const selectedVendorId = ref<IabVendorId | null>(null);
const specialPurposesExpanded = ref(false);

const iabT = useIabTranslations();

const labels = computed(() => ({
	accept: iabT.value?.common?.acceptAll ?? 'Accept all',
	reject: iabT.value?.common?.rejectAll ?? 'Reject all',
	save: iabT.value?.common?.saveSettings ?? 'Save settings',
}));

// Which rows this surface renders, and in what order, comes from the
// shared display model in `@c15t/iab/headless` — the same one React,
// Svelte and the Astro server render read.
const display = computed(() =>
	resolveIABDialogDisplayModel(
		gvl.value ? { customVendors: customVendors.value, gvl: gvl.value } : null
	)
);

const isStackRow = function isStackRow(
	row: HeadlessIABDisplayRow | HeadlessIABDisplayStackRow
): row is HeadlessIABDisplayStackRow {
	return row.kind === 'stack';
};

const isLoading = computed(() => !gvl.value);

// The footer *is* the action root, the way it is in React.
const footerAttrs = computed(() => ({
	...((config.value.components?.['iab-dialog']?.footer as object | undefined) ??
		{}),
	...((config.value.components?.['iab-dialog']?.actions as
		| object
		| undefined) ?? {}),
}));

const totalVendors = computed(() => display.value.vendorTabCount);

const purposeTabCount = computed(() => display.value.purposeTabCount);

const essentialPartnerCount = computed(
	() => display.value.essentialPartnerCount
);

const setPurposeConsent = function setPurposeConsent(
	purposeId: number,
	value: boolean
) {
	draftIab.value.purposeConsents = {
		...draftIab.value.purposeConsents,
		[purposeId]: value,
	};
};

const setPurposeLegitimateInterest = function setPurposeLegitimateInterest(
	purposeId: number,
	value: boolean
) {
	draftIab.value.purposeLegitimateInterests = {
		...draftIab.value.purposeLegitimateInterests,
		[purposeId]: value,
	};
};

const setVendorConsent = function setVendorConsent(
	vendorId: IabVendorId,
	value: boolean
) {
	draftIab.value.vendorConsents = {
		...draftIab.value.vendorConsents,
		[String(vendorId)]: value,
	};
};

const setVendorLegitimateInterest = function setVendorLegitimateInterest(
	vendorId: IabVendorId,
	value: boolean
) {
	draftIab.value.vendorLegitimateInterests = {
		...draftIab.value.vendorLegitimateInterests,
		[String(vendorId)]: value,
	};
};

const setSpecialFeatureOptIn = function setSpecialFeatureOptIn(
	featureId: number,
	value: boolean
) {
	draftIab.value.specialFeatureOptIns = {
		...draftIab.value.specialFeatureOptIns,
		[featureId]: value,
	};
};

const syncDraftFromSelection = function syncDraftFromSelection() {
	draftIab.value = structuredClone(iabSelection.value);
};

watch(
	isOpen,
	(open) => {
		if (!open) {
			return;
		}

		syncDraftFromSelection();
		// A caller-supplied tab outranks the remembered one, so a "N
		// partners" deep link lands on the vendor list.
		activeTab.value = props.initialTab ?? draftIab.value.preferenceCenterTab;
	},
	{ immediate: true }
);

watch(
	() => iabSelection.value.preferenceCenterTab,
	(tab) => {
		if (isOpen.value) {
			activeTab.value = tab;
			draftIab.value.preferenceCenterTab = tab;
		}
	}
);

// The tabs primitive owns `activeTab`; this mirrors it back into the
// draft and the shared selection so a reopened dialog lands where the
// visitor left it.
watch(activeTab, (tab) => {
	draftIab.value.preferenceCenterTab = tab;
	iabSelection.value.preferenceCenterTab = tab;
});

const closeDialog = function closeDialog() {
	activeUI.value = null;
};

const onDialogKeydown = function onDialogKeydown(event: KeyboardEvent) {
	if (isDialogDismissKey(event.key)) {
		event.preventDefault();
		closeDialog();
	}
};

const onAction = function onAction(action: PresentationAction) {
	if (action === 'save') {
		save(
			{
				...structuredClone(draftIab.value),
				preferenceCenterTab: activeTab.value,
			},
			activeTab.value
		);
		return;
	}
	if (action === 'accept') {
		save('all', activeTab.value);
		return;
	}
	if (action === 'reject') {
		save('none', activeTab.value);
	}
};

const handleVendorClick = function handleVendorClick(vendorId: IabVendorId) {
	selectedVendorId.value = vendorId;
	activeTab.value = 'vendors';
};

const { presentation } = useConsentPolicyActions('preferences', {
	layout: IAB_DIALOG_LAYOUT,
});
const scrollLock = computed(() => presentation.value.scrollLock);

useConsentScrollLock(computed(() => Boolean(isOpen.value && scrollLock.value)));

const shouldTrapFocus = computed(() =>
	Boolean(isOpen.value && (toValue(config).trapFocus ?? true))
);
const card = ref<HTMLElement | null>(null);
useFocusTrap(card, () => shouldTrapFocus.value);
</script>

<template>
	<ConsentDialogTrigger v-if="config.iabDialogShowTrigger" />
	<Teleport to="body">
		<Transition
			:css="!disableAnimation"
			:enter-from-class="dialogStyles.overlayHidden"
			:enter-active-class="dialogStyles.overlayVisible"
			:enter-to-class="dialogStyles.overlayVisible"
			:leave-from-class="dialogStyles.overlayVisible"
			:leave-active-class="dialogStyles.overlayHidden"
			:leave-to-class="dialogStyles.overlayHidden"
		>
			<div
				v-if="showDialog && scrollLock"
				v-bind="config.components?.['iab-dialog']?.overlay"
				aria-hidden="true"
				data-testid="iab-consent-dialog-overlay"
				:class="[dialogStyles.overlay, dialogStyles.overlayVisible]"
			/>
		</Transition>
		<Transition
			:css="!disableAnimation"
			:enter-from-class="dialogStyles.dialogHidden"
			:enter-active-class="dialogStyles.dialogVisible"
			:enter-to-class="dialogStyles.dialogVisible"
			:leave-from-class="dialogStyles.dialogVisible"
			:leave-active-class="dialogStyles.dialogHidden"
			:leave-to-class="dialogStyles.dialogHidden"
		>
			<div
				v-if="showDialog"
				v-bind="config.components?.['iab-dialog']?.root"
				data-testid="iab-consent-dialog-root"
				:dir="textDirection"
				:class="[dialogStyles.root, dialogStyles.dialogVisible]"
			>
				<Transition
					:css="!disableAnimation"
					:enter-from-class="dialogStyles.contentHidden"
					:enter-active-class="dialogStyles.contentVisible"
					:enter-to-class="dialogStyles.contentVisible"
					:leave-from-class="dialogStyles.contentVisible"
					:leave-active-class="dialogStyles.contentHidden"
					:leave-to-class="dialogStyles.contentHidden"
				>
					<div
						v-if="showDialog"
						ref="card"
						v-bind="config.components?.['iab-dialog']?.card"
						data-testid="iab-consent-dialog-card"
						:class="[dialogStyles.card, dialogStyles.contentVisible]"
						:role="shouldTrapFocus ? 'dialog' : undefined"
						:aria-modal="shouldTrapFocus ? 'true' : undefined"
						:aria-label="iabT?.preferenceCenter?.title"
						tabindex="-1"
						@keydown="onDialogKeydown"
					>
						<div
							v-bind="config.components?.['iab-dialog']?.header"
							:class="dialogStyles.header"
						>
							<div
								v-bind="config.components?.['iab-dialog']?.headerContent"
								:class="dialogStyles.headerContent"
							>
								<h2
									v-bind="config.components?.['iab-dialog']?.title"
									:class="dialogStyles.title"
								>
									{{ iabT?.preferenceCenter?.title }}
								</h2>
								<p
									v-bind="config.components?.['iab-dialog']?.description"
									:class="dialogStyles.description"
								>
									{{ iabT?.preferenceCenter?.description }}
								</p>
							</div>
							<button
								v-bind="config.components?.['iab-dialog']?.closeButton"
								type="button"
								:class="dialogStyles.closeButton"
								:aria-label="coreCommon?.close"
								data-testid="iab-consent-dialog-close"
								@click="closeDialog"
							>
								<svg
									aria-hidden="true"
									style="width: 1rem; height: 1rem"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									stroke-width="2"
								>
									<line
										x1="18"
										y1="6"
										x2="6"
										y2="18"
									/>
									<line
										x1="6"
										y1="6"
										x2="18"
										y2="18"
									/>
								</svg>
							</button>
						</div>

						<TabsRoot
							v-model:value="activeTab"
							v-bind="config.components?.['iab-dialog']?.body"
							:class="dialogStyles.body"
						>
							<div
								v-bind="config.components?.['iab-dialog']?.tabs"
								:class="dialogStyles.tabsContainer"
							>
								<TabsList
									v-bind="config.components?.['iab-dialog']?.tabsList"
									:class="dialogStyles.tabsList"
								>
									<TabsTrigger
										v-bind="config.components?.['iab-dialog']?.tabTrigger"
										:class="dialogStyles.tabButton"
										value="purposes"
									>
										{{ iabT?.preferenceCenter?.tabs?.purposes }}
										<template v-if="!isLoading">
											{{ ` (${purposeTabCount})` }}
										</template>
									</TabsTrigger>
									<TabsTrigger
										v-bind="config.components?.['iab-dialog']?.tabTrigger"
										:class="dialogStyles.tabButton"
										value="vendors"
									>
										{{ iabT?.preferenceCenter?.tabs?.vendors }}
										<template v-if="!isLoading">
											{{ ` (${totalVendors})` }}
										</template>
									</TabsTrigger>
									<div
										v-bind="config.components?.['iab-dialog']?.tabIndicator"
										aria-hidden="true"
										:class="dialogStyles.tabIndicator"
										:data-active-tab="activeTab"
									/>
								</TabsList>
							</div>

							<div
								v-bind="config.components?.['iab-dialog']?.content"
								:class="dialogStyles.content"
							>
								<div
									v-if="isLoading"
									v-bind="config.components?.['iab-dialog']?.loading"
									:class="dialogStyles.loadingContainer"
								>
									<div :class="dialogStyles.loadingSpinner" />
									<p :class="dialogStyles.loadingText">
										{{ iabT?.common?.loading }}
									</p>
								</div>
								<template v-else>
									<TabsContent
										v-bind="config.components?.['iab-dialog']?.tabPanel"
										:class="dialogStyles.tabPanel"
										force-mount
										value="purposes"
									>
										<template
											v-for="row in display.consentRows"
											:key="row.testId"
										>
											<IabStackItem
												v-if="isStackRow(row)"
												:stack="row"
												:consents="draftIab.purposeConsents"
												:vendor-consents="draftIab.vendorConsents"
												:vendor-legitimate-interests="
													draftIab.vendorLegitimateInterests
												"
												:purpose-legitimate-interests="
													draftIab.purposeLegitimateInterests
												"
												@toggle="
													(purposeId, value) =>
														setPurposeConsent(purposeId, value)
												"
												@vendor-toggle="
													(vendorId, value) => setVendorConsent(vendorId, value)
												"
												@vendor-click="handleVendorClick"
												@vendor-legitimate-interest-toggle="
													(vendorId, value) =>
														setVendorLegitimateInterest(vendorId, value)
												"
												@purpose-legitimate-interest-toggle="
													(purposeId, value) =>
														setPurposeLegitimateInterest(purposeId, value)
												"
											/>
											<IabPurposeItem
												v-else-if="row.toggle === 'special-feature'"
												:purpose="row"
												:test-id="row.testId"
												:is-enabled="
													draftIab.specialFeatureOptIns[row.id] ?? false
												"
												:vendor-consents="draftIab.vendorConsents"
												:vendor-legitimate-interests="
													draftIab.vendorLegitimateInterests
												"
												@toggle="
													(value) => setSpecialFeatureOptIn(row.id, value)
												"
												@vendor-toggle="
													(vendorId, value) => setVendorConsent(vendorId, value)
												"
												@vendor-click="handleVendorClick"
												@vendor-legitimate-interest-toggle="
													(vendorId, value) =>
														setVendorLegitimateInterest(vendorId, value)
												"
											/>
											<IabPurposeItem
												v-else
												:purpose="row"
												:test-id="row.testId"
												:is-enabled="draftIab.purposeConsents[row.id] ?? false"
												:vendor-consents="draftIab.vendorConsents"
												:vendor-legitimate-interests="
													draftIab.vendorLegitimateInterests
												"
												:purpose-legitimate-interests="
													draftIab.purposeLegitimateInterests
												"
												@toggle="(value) => setPurposeConsent(row.id, value)"
												@vendor-toggle="
													(vendorId, value) => setVendorConsent(vendorId, value)
												"
												@vendor-click="handleVendorClick"
												@vendor-legitimate-interest-toggle="
													(vendorId, value) =>
														setVendorLegitimateInterest(vendorId, value)
												"
												@purpose-legitimate-interest-toggle="
													(value) => setPurposeLegitimateInterest(row.id, value)
												"
											/>
										</template>
										<div
											v-if="display.essentialRows.length > 0"
											v-bind="
												config.components?.['iab-dialog']?.specialPurposes
											"
											:class="dialogStyles.specialPurposesSection"
										>
											<div :class="dialogStyles.specialPurposesHeader">
												<button
													type="button"
													:aria-expanded="specialPurposesExpanded"
													:class="dialogStyles.purposeTrigger"
													@click="
														specialPurposesExpanded = !specialPurposesExpanded
													"
												>
													<svg
														aria-hidden="true"
														:class="dialogStyles.purposeArrow"
														viewBox="0 0 24 24"
														fill="none"
														stroke="currentColor"
														stroke-width="2"
													>
														<path
															v-if="specialPurposesExpanded"
															d="M19 9l-7 7-7-7"
														/>
														<path
															v-else
															d="M9 5l7 7-7 7"
														/>
													</svg>
													<div :class="dialogStyles.purposeInfo">
														<h3 :class="dialogStyles.specialPurposesTitle">
															{{
																iabT?.preferenceCenter?.specialPurposes?.title
															}}
															<svg
																aria-hidden="true"
																:class="dialogStyles.lockIcon"
																viewBox="0 0 24 24"
																fill="none"
																stroke="currentColor"
																stroke-width="2"
															>
																<rect
																	x="3"
																	y="11"
																	width="18"
																	height="11"
																	rx="2"
																	ry="2"
																/>
																<path d="M7 11V7a5 5 0 0 1 10 0v4" />
															</svg>
														</h3>
														<p :class="dialogStyles.purposeMeta">
															{{ essentialPartnerCount }}
															{{
																essentialPartnerCount === 1
																	? iabT?.preferenceCenter?.vendorList
																			?.partnerSingular
																	: iabT?.preferenceCenter?.vendorList
																			?.partnerPlural
															}}
														</p>
													</div>
												</button>
												<div style="position: relative">
													<svg
														:aria-label="
															iabT?.preferenceCenter?.specialPurposes?.tooltip
														"
														:class="dialogStyles.infoIcon"
														viewBox="0 0 24 24"
														fill="none"
														stroke="currentColor"
														stroke-width="2"
													>
														<circle
															cx="12"
															cy="12"
															r="10"
														/>
														<line
															x1="12"
															y1="16"
															x2="12"
															y2="12"
														/>
														<line
															x1="12"
															y1="8"
															x2="12.01"
															y2="8"
														/>
													</svg>
												</div>
											</div>

											<div
												v-if="specialPurposesExpanded"
												style="padding: 0.75rem"
											>
												<IabPurposeItem
													v-for="row in display.essentialRows"
													:key="row.testId"
													:purpose="row"
													:test-id="row.testId"
													:is-enabled="true"
													is-locked
													:vendor-consents="draftIab.vendorConsents"
													@vendor-toggle="
														(vendorId, value) =>
															setVendorConsent(vendorId, value)
													"
													@vendor-click="handleVendorClick"
													@vendor-legitimate-interest-toggle="
														(vendorId, value) =>
															setVendorLegitimateInterest(vendorId, value)
													"
												/>
											</div>
										</div>

										<div
											v-bind="config.components?.['iab-dialog']?.consentNotice"
											:class="dialogStyles.consentNotice"
										>
											<p :class="dialogStyles.consentNoticeText">
												{{ iabT?.preferenceCenter?.footer?.consentStorage }}
											</p>
										</div>
									</TabsContent>

									<TabsContent
										v-bind="config.components?.['iab-dialog']?.tabPanel"
										:class="dialogStyles.tabPanel"
										force-mount
										value="vendors"
									>
										<IabVendorList
											:vendor-data="gvl"
											:purposes="display.data.purposes"
											:vendor-consents="draftIab.vendorConsents"
											:selected-vendor-id="selectedVendorId"
											:custom-vendors="customVendors"
											:vendor-legitimate-interests="
												draftIab.vendorLegitimateInterests
											"
											@vendor-toggle="
												(vendorId, value) => setVendorConsent(vendorId, value)
											"
											@clear-selection="selectedVendorId = null"
										/>
									</TabsContent>
								</template>
							</div>
						</TabsRoot>

						<ConsentActions
							:action-groups="presentation.actionGroups"
							:direction="presentation.direction"
							:primary-actions="presentation.primaryActions"
							:labels="labels"
							:test-ids="IAB_DIALOG_ACTION_TEST_IDS"
							primary-mode="filled"
							secondary-mode="stroke"
							:disabled="isLoading"
							:root-test-id="null"
							:root-class="dialogStyles.footer"
							:root-attrs="footerAttrs"
							:group-attrs="
								config.components?.['iab-dialog']?.actionGroup as
									object | undefined
							"
							@action="onAction"
						/>

						<ConsentTag
							v-if="!config.iabDialogHideBranding"
							context="iab-dialog"
						/>
					</div>
				</Transition>
			</div>
		</Transition>
	</Teleport>
</template>

// packages/svelte/src/lib/components/iab-consent-dialog.svelte
<script lang="ts">
	import { defaultTranslationConfig } from '@c15t/core';
	import type { Model } from '@c15t/core';
	import { isDialogDismissKey } from '@c15t/ui/primitives/dialog';
	import actionStyles from '@c15t/ui/styles/components/consent-actions';
	import styles from '@c15t/ui/styles/components/iab-consent-dialog';
	import { buttonVariants } from '@c15t/ui/styles/primitives';
	import { getTextDirection, resolveTranslations } from '@c15t/ui/utils';

	import { focusTrap } from '../actions/focus-trap';
	import { portal } from '../actions/portal';
	import { scrollLock } from '../actions/scroll-lock';
	import { getConsentContext, getThemeContext } from '../context.svelte';
	import { getIABTranslations } from '../iab-translations';
	import { resolveIABDialogDisplayModel } from '../iab-types';
	import type { VendorId } from '../iab-types';
	import { Tabs } from '../primitives';
	import Branding from './branding.svelte';
	import IABPurposeItem from './iab-purpose-item.svelte';
	import IABStackItem from './iab-stack-item.svelte';
	import IABVendorList from './iab-vendor-list.svelte';
	import ChevronRightIcon from './icons/chevron-right-icon.svelte';
	import CloseIcon from './icons/close-icon.svelte';
	import InfoIcon from './icons/info-icon.svelte';
	import LockIcon from './icons/lock-icon.svelte';
	import Overlay from './overlay.svelte';

	let {
		open: openProp,
		noStyle: localNoStyle,
		hideBranding,
		initialTab,
		models = ['iab'] as Model[],
		class: className,
	}: {
		open?: boolean;
		noStyle?: boolean;
		hideBranding?: boolean;
		/**
		 * Which tab the preference centre opens on. Lets a "N partners"
		 * link land on the vendor list instead of purposes.
		 */
		initialTab?: 'purposes' | 'vendors';
		models?: Model[];
		class?: string;
	} = $props();

	const consent = getConsentContext();
	const theme = getThemeContext();

	const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);

	// IAB state
	const iabState = $derived(consent.state.iab);

	// Translations
	const iabT = $derived(getIABTranslations(consent.state.translationConfig));
	const coreTranslations = $derived(
		resolveTranslations(
			consent.state.translationConfig,
			defaultTranslationConfig
		)
	);
	const textDirection = $derived(
		getTextDirection(consent.state.translationConfig?.defaultLanguage)
	);

	// Open state
	const isOpen = $derived(
		models.includes(consent.state.model) &&
			(openProp ?? consent.state.activeUI === 'dialog') &&
			iabState?.config.enabled === true
	);

	// Tab state
	let activeTab = $state<string | null>('purposes');
	let selectedVendorId = $state<VendorId | null>(null);
	let specialPurposesExpanded = $state(false);

	// Sync tab from iabState when dialog opens
	$effect(() => {
		if (isOpen && iabState?.preferenceCenterTab) {
			activeTab = iabState.preferenceCenterTab;
		}
	});

	// A caller-supplied tab outranks the provider's remembered one, which
	// is what makes a "N partners" deep link land on the vendor list. It
	// goes through the provider rather than straight into `activeTab` so
	// the effect above stays the single writer.
	$effect(() => {
		if (initialTab) {
			iabState?.setPreferenceCenterTab(initialTab);
		}
	});

	const handleClose = function handleClose() {
		consent.state.setActiveUI('none');
	};

	const handleDialogKeydown = function handleDialogKeydown(
		event: KeyboardEvent
	) {
		if (isDialogDismissKey(event.key)) {
			event.preventDefault();
			handleClose();
		}
	};

	$effect(() => {
		if (activeTab === 'purposes' || activeTab === 'vendors') {
			iabState?.setPreferenceCenterTab(activeTab);
		}
	});

	// The rows this surface renders, from the shared display model.
	const display = $derived(
		resolveIABDialogDisplayModel(
			iabState
				? {
						customVendors: iabState.nonIABVendors ?? [],
						gvl: iabState.gvl,
						isLoadingGVL: iabState.isLoadingGVL,
					}
				: null
		)
	);

	const isLoading = $derived(iabState?.isLoadingGVL || !iabState?.gvl);

	const handlePurposeToggle = function handlePurposeToggle(
		purposeId: number,
		value: boolean
	) {
		iabState?.setPurposeConsent(purposeId, value);
	};

	const handleSpecialFeatureToggle = function handleSpecialFeatureToggle(
		featureId: number,
		value: boolean
	) {
		iabState?.setSpecialFeatureOptIn(featureId, value);
	};

	const handleVendorToggle = function handleVendorToggle(
		vendorId: VendorId,
		value: boolean
	) {
		iabState?.setVendorConsent(vendorId, value);
	};

	const handleVendorLegitimateInterestToggle =
		function handleVendorLegitimateInterestToggle(
			vendorId: VendorId,
			value: boolean
		) {
			iabState?.setVendorLegitimateInterest(vendorId, value);
		};

	const handlePurposeLegitimateInterestToggle =
		function handlePurposeLegitimateInterestToggle(
			purposeId: number,
			value: boolean
		) {
			iabState?.setPurposeLegitimateInterest(purposeId, value);
		};

	const handleAcceptAll = function handleAcceptAll() {
		iabState?.acceptAll();
		iabState?.save();
		consent.state.setActiveUI('none');
	};

	const handleRejectAll = function handleRejectAll() {
		iabState?.rejectAll();
		iabState?.save();
		consent.state.setActiveUI('none');
	};

	const handleSave = function handleSave() {
		iabState?.save();
		consent.state.setActiveUI('none');
	};

	const handleVendorClick = function handleVendorClick(vendorId: VendorId) {
		selectedVendorId = vendorId;
		activeTab = 'vendors';
		iabState?.setPreferenceCenterTab('vendors');
	};

	const secondaryButtonClass = buttonVariants({
		mode: 'stroke',
		size: 'small',
		variant: 'neutral',
	}).root();
	const primaryButtonClass = buttonVariants({
		mode: 'filled',
		size: 'small',
		variant: 'primary',
	}).root();
</script>

<!--
	Plain elements, not the Ark dialog: React's IAB preference centre is
	hand-rolled, and a primitive library's `data-slot`/`data-state`
	bookkeeping is exactly the kind of difference the cross-framework gate
	is there to catch. The behaviour the primitive provided — portal, focus
	trap, scroll lock, Escape to close — comes from the same actions the
	IAB banner uses.
-->
{#if isOpen}
	<div use:portal>
		<Overlay
			variant="iab-dialog"
			visible={isOpen}
		/>
		<div
			class={noStyle
				? ''
				: `${styles.root || ''} ${styles.dialogVisible || ''}`}
			data-testid="iab-consent-dialog-root"
			dir={textDirection}
		>
			<!-- A `div`, not a `dialog`: the user agent's dialog padding is
			     1em, which the card sets for itself. -->
			<div
				class={noStyle
					? className || ''
					: `${styles.card || ''} ${className || ''} ${styles.contentVisible || ''}`}
				data-testid="iab-consent-dialog-card"
				role="dialog"
				aria-modal="true"
				aria-label={iabT.preferenceCenter.title}
				tabindex="-1"
				use:focusTrap={true}
				use:scrollLock={true}
				onkeydown={handleDialogKeydown}
			>
				<!-- Header -->
				<div class={noStyle ? '' : styles.header || ''}>
					<div class={noStyle ? '' : styles.headerContent || ''}>
						<h2 class={noStyle ? '' : styles.title || ''}>
							{iabT.preferenceCenter.title}
						</h2>
						<p class={noStyle ? '' : styles.description || ''}>
							{iabT.preferenceCenter.description}
						</p>
					</div>
					<button
						type="button"
						class={noStyle ? '' : styles.closeButton || ''}
						aria-label={coreTranslations.common.close}
						data-testid="iab-consent-dialog-close"
						onclick={handleClose}
					>
						<CloseIcon
							style="height:1rem;width:1rem"
							aria-hidden={true}
						/>
					</button>
				</div>

				<Tabs.Root
					bind:value={activeTab}
					class={noStyle ? '' : styles.body || ''}
				>
					<div class={noStyle ? '' : styles.tabsContainer || ''}>
						<Tabs.List class={noStyle ? '' : styles.tabsList || ''}>
							<Tabs.Trigger
								value="purposes"
								class={noStyle ? '' : styles.tabButton || ''}
							>
								{iabT.preferenceCenter.tabs.purposes}
								{#if !isLoading}
									({display.purposeTabCount})
								{/if}
							</Tabs.Trigger>
							<Tabs.Trigger
								value="vendors"
								class={noStyle ? '' : styles.tabButton || ''}
							>
								{iabT.preferenceCenter.tabs.vendors}
								{#if !isLoading}
									({display.vendorTabCount})
								{/if}
							</Tabs.Trigger>
							<div
								aria-hidden="true"
								class={noStyle ? '' : styles.tabIndicator || ''}
								data-active-tab={activeTab}
							></div>
						</Tabs.List>
					</div>

					<div class={noStyle ? '' : styles.content || ''}>
						<Tabs.Content
							value="purposes"
							forceMount
							class={noStyle ? '' : styles.tabPanel || ''}
						>
							{#if isLoading}
								<div class={noStyle ? '' : styles.loadingContainer || ''}>
									<div class={noStyle ? '' : styles.loadingSpinner || ''}></div>
									<p class={noStyle ? '' : styles.loadingText || ''}>
										{iabT.common.loading}
									</p>
								</div>
							{:else if display.isReady && iabState}
								<!-- Purposes, stacks and special features, from the
								     shared display model so every adapter lists the
								     same rows in the same order. -->
								{#each display.consentRows as row (row.testId)}
									{#if row.kind === 'stack'}
										<IABStackItem
											stack={row}
											consents={iabState.purposeConsents}
											onToggle={handlePurposeToggle}
											vendorConsents={iabState.vendorConsents}
											onVendorToggle={handleVendorToggle}
											onVendorClick={handleVendorClick}
											vendorLegitimateInterests={iabState.vendorLegitimateInterests}
											onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
											purposeLegitimateInterests={iabState.purposeLegitimateInterests}
											onPurposeLegitimateInterestToggle={handlePurposeLegitimateInterestToggle}
											{noStyle}
											{iabT}
										/>
									{:else if row.toggle === 'special-feature'}
										<IABPurposeItem
											purpose={row}
											testId={row.testId}
											isEnabled={iabState.specialFeatureOptIns[row.id] ?? false}
											onToggle={(value) =>
												handleSpecialFeatureToggle(row.id, value)}
											vendorConsents={iabState.vendorConsents}
											onVendorToggle={handleVendorToggle}
											onVendorClick={handleVendorClick}
											vendorLegitimateInterests={iabState.vendorLegitimateInterests}
											onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
											{noStyle}
											{iabT}
										/>
									{:else}
										<IABPurposeItem
											purpose={row}
											testId={row.testId}
											isEnabled={iabState.purposeConsents[row.id] ?? false}
											onToggle={(value) => handlePurposeToggle(row.id, value)}
											vendorConsents={iabState.vendorConsents}
											onVendorToggle={handleVendorToggle}
											onVendorClick={handleVendorClick}
											vendorLegitimateInterests={iabState.vendorLegitimateInterests}
											onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
											purposeLegitimateInterests={iabState.purposeLegitimateInterests}
											onPurposeLegitimateInterestToggle={handlePurposeLegitimateInterestToggle}
											{noStyle}
											{iabT}
										/>
									{/if}
								{/each}

								<!-- Essential Functions: Special Purposes + Features (locked) -->
								{#if display.essentialRows.length > 0}
									<div
										class={noStyle ? '' : styles.specialPurposesSection || ''}
									>
										<div
											class={noStyle ? '' : styles.specialPurposesHeader || ''}
										>
											<button
												type="button"
												class={noStyle ? '' : styles.purposeTrigger || ''}
												onclick={() =>
													(specialPurposesExpanded = !specialPurposesExpanded)}
											>
												<ChevronRightIcon
													class={noStyle ? '' : styles.purposeArrow || ''}
													aria-hidden={true}
													expanded={specialPurposesExpanded}
												/>
												<div class={noStyle ? '' : styles.purposeInfo || ''}>
													<h3
														class={noStyle
															? ''
															: styles.specialPurposesTitle || ''}
													>
														{iabT.preferenceCenter.specialPurposes.title}
														<LockIcon
															class={noStyle ? '' : styles.lockIcon || ''}
															aria-hidden={true}
														/>
													</h3>
													<p class={noStyle ? '' : styles.purposeMeta || ''}>
														{display.essentialPartnerCount}
														{display.essentialPartnerCount === 1
															? iabT.preferenceCenter.vendorList.partnerSingular
															: iabT.preferenceCenter.vendorList.partnerPlural}
													</p>
												</div>
											</button>
											<div style="position:relative">
												<InfoIcon
													class={noStyle ? '' : styles.infoIcon || ''}
													aria-label={iabT.preferenceCenter.specialPurposes
														.tooltip}
												/>
											</div>
										</div>

										{#if specialPurposesExpanded}
											<div style="padding:0.75rem">
												{#each display.essentialRows as row (row.testId)}
													<IABPurposeItem
														purpose={row}
														testId={row.testId}
														isEnabled={true}
														onToggle={() => {}}
														vendorConsents={iabState.vendorConsents}
														onVendorToggle={handleVendorToggle}
														onVendorClick={handleVendorClick}
														isLocked={true}
														{noStyle}
														{iabT}
													/>
												{/each}
											</div>
										{/if}
									</div>
								{/if}

								<!-- Consent storage notice -->
								<div class={noStyle ? '' : styles.consentNotice || ''}>
									<p class={noStyle ? '' : styles.consentNoticeText || ''}>
										{iabT.preferenceCenter.footer.consentStorage}
									</p>
								</div>
							{/if}
						</Tabs.Content>

						<Tabs.Content
							value="vendors"
							forceMount
							class={noStyle ? '' : styles.tabPanel || ''}
						>
							{#if iabState}
								<IABVendorList
									vendorData={iabState.gvl}
									purposes={display.data.purposes}
									vendorConsents={iabState.vendorConsents}
									onVendorToggle={handleVendorToggle}
									{selectedVendorId}
									onClearSelection={() => (selectedVendorId = null)}
									customVendors={iabState.nonIABVendors}
									vendorLegitimateInterests={iabState.vendorLegitimateInterests}
									onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
									{noStyle}
									{iabT}
								/>
							{/if}
						</Tabs.Content>
					</div>
				</Tabs.Root>

				<!-- Footer -->
				<div
					class={noStyle ? '' : `${styles.footer} ${actionStyles.actionRoot}`}
					data-direction="row"
					data-split
				>
					<div
						class={noStyle ? '' : actionStyles.actionGroup}
						data-direction="row"
					>
						<button
							type="button"
							class={noStyle ? '' : secondaryButtonClass}
							onclick={handleRejectAll}
							disabled={isLoading}
							data-action="reject"
						>
							{iabT.common.rejectAll}
						</button>
						<button
							type="button"
							class={noStyle ? '' : secondaryButtonClass}
							onclick={handleAcceptAll}
							disabled={isLoading}
							data-action="accept"
						>
							{iabT.common.acceptAll}
						</button>
					</div>
					<div
						class={noStyle ? '' : actionStyles.actionGroup}
						data-direction="row"
					>
						<button
							type="button"
							class={noStyle ? '' : primaryButtonClass}
							onclick={handleSave}
							disabled={isLoading}
							data-action="customize"
						>
							{iabT.common.saveSettings}
						</button>
					</div>
				</div>
				<Branding
					{hideBranding}
					{noStyle}
					variant="dialog-tag"
					themeKey="iabConsentDialogTag"
					data-testid="iab-consent-dialog-branding"
				/>
			</div>
		</div>
	</div>
{/if}
