// packages/react/src/components/iab-prompt/atoms/overlay.tsx
'use client';

import styles from '@c15t/ui/styles/components/iab-consent-banner';
import { forwardRef as createForwardRef } from 'react';
import type { HTMLAttributes } from 'react';

import { useActiveUI } from '~/hooks';
import { useLateEntry } from '~/hooks/use-late-entry';
import { useScrollLock } from '~/hooks/use-scroll-lock';
import { useTheme } from '~/hooks/use-theme';
import { useUIConfig } from '~/ui-config-context';
import { cnExt as cn } from '~/utils/cn';
import { mergeSlotProps } from '~/utils/merge-slot-props';

interface OverlayProps extends HTMLAttributes<HTMLDivElement> {
	noStyle?: boolean;
}

const IABConsentBannerOverlay = createForwardRef<HTMLDivElement, OverlayProps>(
	({ className, style, noStyle, ...props }, ref) => {
		const activeUI = useActiveUI();
		const {
			disableAnimation,
			noStyle: contextNoStyle,
			scrollLock,
		} = useTheme();
		const { components } = useUIConfig();

		// Show when banner is active (model filtering is handled by the root component)
		const shouldShow = activeUI === 'banner';

		const theme = mergeSlotProps(components?.['iab-banner']?.overlay, {
			baseClassName: styles.overlay,
			className,
			noStyle: contextNoStyle || noStyle,
			style,
			...props,
		});

		const shouldApplyAnimation =
			!(contextNoStyle || noStyle) && !disableAnimation;

		// The overlay shows on its first frame; `overlayEntering` marks the
		// mount, and with `data-entry="late"` the stylesheet fades it in.
		const animationClass = shouldApplyAnimation
			? `${styles.overlayVisible} ${styles.overlayEntering}`
			: undefined;

		const finalClassName = cn(theme.className, animationClass);

		useScrollLock(!!(shouldShow && scrollLock));
		const lateEntry =
			useLateEntry(!!(shouldShow && scrollLock)) && !disableAnimation;

		if (!shouldShow || !scrollLock) {
			return null;
		}

		return (
			<div
				ref={ref}
				{...theme}
				aria-hidden="true"
				className={finalClassName}
				data-entry={lateEntry ? 'late' : undefined}
				data-testid="iab-consent-banner-overlay"
			/>
		);
	}
);

IABConsentBannerOverlay.displayName = 'IABConsentBannerOverlay';

export { IABConsentBannerOverlay };

// packages/svelte/src/lib/components/overlay.svelte
<script lang="ts">
	import { getThemeContext } from '../context.svelte';
	import { resolveComponentStyles, toStyleAttribute } from '../utils';

	/**
	 * The overlay class names from the caller's own style map. The overlay
	 * imports none itself, so a page with only the banner does not ship the
	 * dialog or IAB class maps (and, where a class map imports its CSS, their
	 * stylesheets).
	 */
	interface OverlayStyles {
		overlay?: string;
		overlayVisible?: string;
		overlayEntering?: string;
		overlayHidden?: string;
	}

	let {
		entering,
		lateEntry = false,
		styles,
		variant = 'banner',
		visible = true,
	}: {
		/**
		 * Add the entering class on a visible overlay, which the dialog's
		 * stylesheet fades in from the first frame and the banner's fades in
		 * only with `lateEntry`. Defaults to the theme's animation
		 * setting, so a caller only passes it to override that.
		 */
		entering?: boolean;
		/**
		 * Mark the mount `data-entry="late"`, for a banner that arrives
		 * after the page has painted. The stylesheet fades it in.
		 */
		lateEntry?: boolean;
		styles: OverlayStyles;
		variant?: 'banner' | 'dialog' | 'iab-banner' | 'iab-dialog';
		visible?: boolean;
	} = $props();

	const theme = getThemeContext();
	const shouldEnter = $derived(entering ?? !(theme.disableAnimation ?? false));

	const themeKey = $derived.by(() => {
		if (variant === 'dialog') {
			return 'consentDialogOverlay' as const;
		}
		if (variant === 'iab-dialog') {
			return 'iabConsentDialogOverlay' as const;
		}
		return variant === 'iab-banner'
			? ('iabConsentBannerOverlay' as const)
			: ('consentBannerOverlay' as const);
	});

	const testId = $derived.by(() => {
		if (variant === 'dialog') {
			return 'consent-dialog-overlay';
		}
		if (variant === 'iab-dialog') {
			return 'iab-consent-dialog-overlay';
		}
		return variant === 'iab-banner'
			? 'iab-consent-banner-overlay'
			: 'consent-banner-overlay';
	});

	const themeStyle = $derived(
		resolveComponentStyles(
			themeKey,
			theme.theme,
			{ baseClassName: styles.overlay },
			theme.noStyle
		)
	);

	const className = $derived(
		theme.noStyle
			? themeStyle.className || ''
			: `${themeStyle.className || ''} ${visible ? `${styles.overlayVisible}${shouldEnter && styles.overlayEntering ? ` ${styles.overlayEntering}` : ''}` : styles.overlayHidden}`
	);
</script>

<div
	class={className}
	style={toStyleAttribute(themeStyle.style)}
	data-entry={lateEntry ? 'late' : undefined}
	data-testid={testId}
	aria-hidden="true"
></div>
