// packages/vue/src/runtime/components/prompt.vue
<script setup lang="ts">
import type {
	PresentationAction,
	PromptPosition,
	PromptVariant,
} from '@c15t/core';
import type { PolicyRight } from '@c15t/schema/types';
import type { CompleteTranslations } from '@c15t/translations';
import bannerStyles from '@c15t/ui/styles/components/consent-banner';

import '@c15t/ui/styles/components/consent-banner.css';
import { getTextDirection } from '@c15t/ui/utils';
import { computed, mergeProps, ref, Teleport, Transition } from 'vue';

import {
	useConsentActiveUI,
	useConsentConfig,
	useConsentInit,
	useConsentSave,
	useConsentKernel,
	useConsentSnapshot,
	useHasConsentUi,
} from '../composables';
import { useConsentPolicyActions } from '../composables/use-consent-policy-actions';
import { useConsentScrollLock } from '../composables/use-consent-scroll-lock';
import { useLateEntry } from '../composables/use-late-entry';
import { useMounted } from '../composables/use-mounted';
import { useFocusTrap } from '../primitives/use-focus-trap';
import { slotAttrs } from '../utils/slot-attrs';
import ConsentActions from './actions.vue';
import DescriptionContent from './description-content.vue';
import ConsentTag from './tag.vue';

/**
 * Local overrides for the surface shape. Each one beats the host
 * `presentation.prompt` value; leave them unset to follow the policy
 * defaults (every prompt renders as a floating card unless the host
 * chooses otherwise).
 * `blocking` defaults to `undefined` on purpose: Vue would otherwise cast
 * an absent boolean prop to `false` and override the host value.
 */
const props = withDefaults(
	defineProps<{
		/** Surface shape: `floating`, `bar`, `widget` or `wall`. */
		variant?: PromptVariant;
		/** Position, validated against the resolved variant. */
		position?: PromptPosition;
		/** Backdrop, scroll lock, focus trap and no outside dismissal. */
		blocking?: boolean;
		/** Skip the enter and exit animations. Defaults to the config's. */
		disableAnimation?: boolean;
	}>(),
	{
		blocking: undefined,
		disableAnimation: undefined,
		position: undefined,
		variant: undefined,
	}
);

const mounted = useMounted();
const activeUI = useConsentActiveUI();
const config = useConsentConfig();
const init = useConsentInit();
const textDirection = computed(() =>
	getTextDirection(init.value?.translations?.language)
);
const save = useConsentSave();
const kernel = useConsentKernel();
const snapshot = useConsentSnapshot();

const transitionStyles = bannerStyles as Record<string, string>;

const {
	presentation: surface,
	actionGroups,
	blocking,
	direction,
	position,
	positionSource,
	primaryActions: resolvedPrimaryActions,
	shouldFillActions,
	preferenceControls,
	variant,
} = useConsentPolicyActions('prompt', () => ({
	blocking: props.blocking,
	position: props.position,
	variant: props.variant,
}));

/**
 * The wire type lags the translations package, so the newer keys (notice
 * copy, dismiss, rights) are read through the package's own type.
 */
const bundle = computed(
	() =>
		init.value?.translations?.translations as
			| Partial<CompleteTranslations>
			| undefined
);

const promptKind = computed(() => snapshot.value.policyRule.prompt);
const isNotice = computed(() => promptKind.value === 'notice');

/**
 * A notice offers dismiss alone. The resolver's default primary is
 * customize, which a notice never has, so the one action takes the
 * primary treatment instead of rendering every control as neutral.
 */
const primaryActions = computed(() => {
	if (resolvedPrimaryActions.value.length > 0) {
		return resolvedPrimaryActions.value;
	}
	const ordered = actionGroups.value.flat();
	return ordered.length === 1 && ordered[0] === 'dismiss' ? ordered : [];
});

const hasConsentUi = useHasConsentUi();
const isOpen = computed(() => {
	if (!hasConsentUi.value) {
		return false;
	}
	const { model } = snapshot.value.policyRule;
	const models = config.value.bannerModels ?? config.value.models;
	const matchesModel =
		!models?.length ||
		(model !== undefined && model !== 'none' && models.includes(model));
	return (
		activeUI.value === 'banner' &&
		matchesModel &&
		!snapshot.value.policyPending &&
		snapshot.value.promptRequirement.kind !== 'none'
	);
});

const disableAnimation = computed(() =>
	Boolean(props.disableAnimation ?? config.value.disableAnimation)
);

const scrollLock = computed(() => surface.value.scrollLock);
// A banner that opens after the page painted fades in.
const lateEntry = useLateEntry(isOpen);
const entryAttribute = computed(() =>
	lateEntry.value && !disableAnimation.value ? 'late' : undefined
);
useConsentScrollLock(computed(() => isOpen.value && scrollLock.value));

const shouldTrapFocus = computed(() =>
	Boolean(isOpen.value && surface.value.trapFocus)
);
const card = ref<HTMLElement | null>(null);
useFocusTrap(card, () => shouldTrapFocus.value);

const bannerTitle = computed(() => {
	const cookieBanner = bundle.value?.cookieBanner;
	if (isNotice.value) {
		return cookieBanner?.noticeTitle ?? cookieBanner?.title ?? 'Privacy notice';
	}
	return cookieBanner?.title ?? 'Cookie choices';
});

/**
 * A defaulted corner mirrors for right-to-left text so the card sits at
 * the reading start. A host-chosen position is kept as written.
 */
const resolvedPosition = computed(() => {
	const { value } = position;
	if (
		positionSource.value === 'host' ||
		textDirection.value !== 'rtl' ||
		(variant.value !== 'floating' && variant.value !== 'widget')
	) {
		return value;
	}
	if (value.endsWith('-left')) {
		return value.replace('-left', '-right') as PromptPosition;
	}
	if (value.endsWith('-right')) {
		return value.replace('-right', '-left') as PromptPosition;
	}
	return value;
});

/**
 * Notice acknowledgement leaves category choices and permissions unchanged.
 */
const labels = computed(() => {
	const common = bundle.value?.common;
	return {
		accept: common?.acceptAll ?? 'Accept all',
		customize: common?.customize ?? 'Customize',
		dismiss: common?.acknowledge ?? common?.dismiss ?? 'OK',
		reject: common?.rejectAll ?? 'Reject all',
	} as const;
});

const rightLabels = computed<Record<PolicyRight, string>>(() => {
	const rights = bundle.value?.rights;
	return {
		disclosure: '',
		'opt-out': rights?.optOut ?? 'Do not sell or share my data',
		preferences: rights?.preferences ?? 'Manage preferences',
	};
});

/** Additional buttons open preferences and use underlined text styling. */
const onRight = function onRight() {
	activeUI.value = 'manager';
};

const actionTestIds = {
	accept: 'consent-banner-accept-button',
	customize: 'consent-banner-customize-button',
	dismiss: 'consent-banner-dismiss-button',
	reject: 'consent-banner-reject-button',
} as const;

const onAction = function onAction(action: PresentationAction) {
	if (action === 'dismiss') {
		void kernel.commands.dismissNotice();
		return;
	}
	if (action === 'customize') {
		activeUI.value = 'manager';
		return;
	}
	if (action === 'accept') {
		save('all');
		return;
	}
	if (action === 'reject') {
		save('none');
	}
};
</script>

<template>
	<Teleport
		to="body"
		:disabled="!mounted"
	>
		<Transition
			:css="!disableAnimation"
			:enter-from-class="''"
			:enter-active-class="transitionStyles.overlayVisible"
			:enter-to-class="transitionStyles.overlayVisible"
			:leave-from-class="transitionStyles.overlayVisible"
			:leave-active-class="transitionStyles.overlayHidden"
			:leave-to-class="transitionStyles.overlayHidden"
		>
			<div
				v-if="isOpen && scrollLock"
				v-bind="
					slotAttrs(config.components?.banner?.overlay, [
						bannerStyles.overlay,
						disableAnimation ? undefined : bannerStyles.overlayVisible,
						disableAnimation ? undefined : bannerStyles.overlayEntering,
					])
				"
				aria-hidden="true"
				:data-entry="entryAttribute"
				data-testid="consent-banner-overlay"
			/>
		</Transition>
		<Transition
			:css="!disableAnimation"
			:enter-from-class="''"
			:enter-active-class="transitionStyles.bannerVisible"
			:enter-to-class="transitionStyles.bannerVisible"
			:leave-from-class="transitionStyles.bannerVisible"
			:leave-active-class="transitionStyles.bannerHidden"
			:leave-to-class="transitionStyles.bannerHidden"
		>
			<div
				v-if="isOpen"
				v-bind="
					slotAttrs(config.components?.banner?.root, [
						bannerStyles.root,
						bannerStyles.bannerVisible,
						disableAnimation ? undefined : bannerStyles.bannerEntering,
					])
				"
				data-testid="consent-banner-root"
				:data-entry="entryAttribute"
				:data-variant="variant"
				:data-position="resolvedPosition"
				:data-blocking="blocking ? 'true' : undefined"
				:data-prompt="promptKind"
				:data-model="snapshot.policyRule.model"
				:dir="textDirection"
			>
				<div
					v-bind="config.components?.banner?.cardShell"
					:class="bannerStyles.cardShell"
				>
					<ConsentTag
						v-if="!(config.bannerHideBranding ?? config.hideBranding)"
						context="banner"
					/>
					<div
						ref="card"
						v-bind="
							slotAttrs(config.components?.banner?.card, bannerStyles.card)
						"
						data-testid="consent-banner-card"
						:role="blocking ? 'dialog' : 'region'"
						:aria-modal="blocking ? 'true' : undefined"
						:aria-label="bannerTitle"
						tabindex="-1"
					>
						<div
							v-bind="
								slotAttrs(
									config.components?.banner?.header,
									bannerStyles.header
								)
							"
							data-testid="consent-banner-header"
						>
							<h2
								v-bind="
									slotAttrs(
										config.components?.banner?.title,
										bannerStyles.title
									)
								"
								data-testid="consent-banner-title"
							>
								{{ bannerTitle }}
							</h2>
							<DescriptionContent
								context="banner"
								:description-class="bannerStyles.description"
							/>
						</div>
						<ConsentActions
							data-testid="consent-banner-footer"
							:root-class="bannerStyles.footer"
							button-size="small"
							group-test-id="consent-banner-footer-sub-group"
							:action-groups="actionGroups"
							:direction="direction"
							:ui-profile="surface?.uiProfile"
							:primary-actions="primaryActions"
							:fill="shouldFillActions"
							:labels="labels"
							:test-ids="actionTestIds"
							:root-attrs="
								mergeProps(
									{ ...config.components?.banner?.footer },
									{ ...config.components?.banner?.actions }
								)
							"
							:group-attrs="{
								...config.components?.banner?.actionGroup,
							}"
							@action="onAction"
						>
							<template #leading>
								<div
									v-if="preferenceControls.length > 0"
									v-bind="
										slotAttrs(
											config.components?.banner?.rights,
											bannerStyles.rights
										)
									"
									data-testid="consent-banner-rights"
								>
									<button
										v-for="right in preferenceControls"
										:key="right"
										v-bind="
											slotAttrs(
												config.components?.banner?.rightLink,
												bannerStyles.rightLink
											)
										"
										type="button"
										data-action="right"
										:data-c15t-rights="snapshot.policyRule.rights.join(' ')"
										:data-right="right"
										:data-testid="`consent-banner-right-link-${right}`"
										@click="onRight"
									>
										{{ rightLabels[right] }}
									</button>
								</div>
							</template>
						</ConsentActions>
					</div>
				</div>
			</div>
		</Transition>
	</Teleport>
</template>

// packages/svelte/src/lib/components/prompt.svelte
<script lang="ts">
	import type {
		LegalLinks as LegalLinksType,
		Model,
		PromptPosition,
		PromptVariant,
	} from '@c15t/core';
	import {
		defaultTranslationConfig,
		resolveConsentPresentation,
	} from '@c15t/core';
	import type { PolicyRight } from '@c15t/schema/types';
	import styles from '@c15t/ui/styles/components/consent-banner';
	import { getTextDirection, resolveTranslations } from '@c15t/ui/utils';

	import { focusTrap } from '../actions/focus-trap';
	// Banner uses custom portal/focus-trap/scroll-lock actions (not Ark UI's built-in)
	// because the banner is not an Ark Dialog - it's a simpler container that
	// conditionally acts as a dialog. The ConsentDialog uses Ark's Dialog which
	// includes its own focus trap and scroll prevention. When transitioning from
	// banner to dialog, the banner unmounts (removing its focus trap) before
	// the dialog mounts (establishing Ark's focus trap), so they don't compete.
	import { portal } from '../actions/portal';
	import { scrollLock } from '../actions/scroll-lock';
	import { getConsentContext, getThemeContext } from '../context.svelte';
	import { useBannerVisibility } from '../use-banner-visibility.svelte';
	import {
		resolveComponentStyles,
		resolveConsentActionStyle,
		toStyleAttribute,
	} from '../utils';
	import ConsentButton from './action-button.svelte';
	import Branding from './branding.svelte';
	import InlineLegalLinks from './inline-legal-links.svelte';
	import Overlay from './overlay.svelte';
	import PolicyActionsRenderer from './policy-actions-renderer.svelte';

	/**
	 * Button identifiers for the consent banner layout.
	 */
	type ConsentBannerButton = 'reject' | 'accept' | 'customize' | 'dismiss';
	type ConsentBannerLayout = (ConsentBannerButton | ConsentBannerButton[])[];

	let {
		noStyle: localNoStyle,
		disableAnimation: localDisableAnimation,
		scrollLock: localScrollLock,
		trapFocus: localTrapFocus,
		title,
		description,
		rejectButtonText,
		customizeButtonText,
		acceptButtonText,
		dismissButtonText,
		hideBranding = false,
		legalLinks,
		layout,
		primaryButton,
		variant,
		position,
		blocking,
		models = ['opt-in', 'opt-out', 'iab'] as Model[],
		class: className,
	}: {
		noStyle?: boolean;
		disableAnimation?: boolean;
		scrollLock?: boolean;
		trapFocus?: boolean;
		title?: string;
		description?: string;
		rejectButtonText?: string;
		customizeButtonText?: string;
		acceptButtonText?: string;
		dismissButtonText?: string;
		hideBranding?: boolean;
		legalLinks?: (keyof LegalLinksType)[] | null;
		layout?: ConsentBannerLayout;
		primaryButton?: ConsentBannerButton | ConsentBannerButton[];
		/**
		 * Shape of the prompt. Overrides the host presentation.
		 * A notice defaults to `bar`, a choice prompt to `floating`.
		 */
		variant?: PromptVariant;
		/**
		 * Where the prompt sits. Must be valid for the resolved variant;
		 * an invalid value falls back to the variant default with a
		 * development diagnostic.
		 */
		position?: PromptPosition;
		/**
		 * Backdrop, scroll lock, focus trap, and no dismissal from outside,
		 * as one value. `wall` is always blocking; a notice never is.
		 */
		blocking?: boolean;
		models?: Model[];
		class?: string;
	} = $props();

	/** Corner mirror for right-to-left text when the host set no position. */
	const MIRRORED_POSITIONS: Partial<Record<PromptPosition, PromptPosition>> = {
		'bottom-left': 'bottom-right',
		'bottom-right': 'bottom-left',
		'top-left': 'top-right',
		'top-right': 'top-left',
	};

	const consent = getConsentContext();
	const theme = getThemeContext();

	const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);
	const disableAnimation = $derived(
		localDisableAnimation ?? theme.disableAnimation ?? false
	);

	// Translations
	const translations = $derived(
		resolveTranslations(
			consent.state.translationConfig,
			defaultTranslationConfig
		)
	);
	const textDirection = $derived(
		getTextDirection(consent.state.translationConfig?.defaultLanguage)
	);

	// Visibility logic
	const shouldShowBanner = $derived(
		consent.state.hasConsentUi &&
			consent.state.activeUI === 'banner' &&
			consent.snapshot.promptRequirement.kind !== 'none' &&
			models.includes(consent.state.model)
	);

	const visibility = useBannerVisibility(
		() => shouldShowBanner,
		() => disableAnimation
	);

	// Styling - per-element theme key resolution shared across framework adapters.
	const rootStyle = $derived(
		resolveComponentStyles(
			'consentBanner',
			theme.theme,
			{
				baseClassName: styles.root,
				className,
				noStyle,
			},
			noStyle
		)
	);

	const cardStyle = $derived(
		resolveComponentStyles(
			'consentBannerCard',
			theme.theme,
			{ baseClassName: styles.card, noStyle },
			noStyle
		)
	);

	const headerStyle = $derived(
		resolveComponentStyles(
			'consentBannerHeader',
			theme.theme,
			{ baseClassName: styles.header, noStyle },
			noStyle
		)
	);

	const titleStyle = $derived(
		resolveComponentStyles(
			'consentBannerTitle',
			theme.theme,
			{ baseClassName: styles.title, noStyle },
			noStyle
		)
	);

	const descriptionStyle = $derived(
		resolveComponentStyles(
			'consentBannerDescription',
			theme.theme,
			{ baseClassName: styles.description, noStyle },
			noStyle
		)
	);

	const footerStyle = $derived(
		resolveComponentStyles(
			'consentBannerFooter',
			theme.theme,
			{ baseClassName: styles.footer, noStyle },
			noStyle
		)
	);

	const footerSubGroupStyle = $derived(
		resolveComponentStyles(
			'consentBannerFooterSubGroup',
			theme.theme,
			{ noStyle },
			noStyle
		)
	);

	const rightsStyle = $derived(
		resolveComponentStyles(
			'consentBannerRights',
			theme.theme,
			{ baseClassName: styles.rights, noStyle },
			noStyle
		)
	);

	const rightLinkStyle = $derived(
		resolveComponentStyles(
			'consentBannerRightLink',
			theme.theme,
			{ baseClassName: styles.rightLink, noStyle },
			noStyle
		)
	);

	// A right control opens the preference center without recording a choice.
	const openPreferences = function openPreferences() {
		consent.state.setActiveUI('dialog');
	};

	const finalClassName = $derived(
		noStyle
			? rootStyle.className || ''
			: `${rootStyle.className || ''} ${visibility.isVisible ? `${styles.bannerVisible}${disableAnimation ? '' : ` ${styles.bannerEntering}`}` : styles.bannerHidden}`
	);

	const localPrimaryActions = $derived.by(() => {
		if (primaryButton === undefined) {
			return undefined;
		}
		return Array.isArray(primaryButton) ? primaryButton : [primaryButton];
	});
	// Button helpers
	const themedActions = $derived({
		accept: resolveConsentActionStyle(theme.theme, 'accept'),
		customize: resolveConsentActionStyle(theme.theme, 'customize'),
		dismiss: resolveConsentActionStyle(theme.theme, 'dismiss'),
		reject: resolveConsentActionStyle(theme.theme, 'reject'),
		save: resolveConsentActionStyle(theme.theme, 'save'),
	});
	const presentation = $derived(
		resolveConsentPresentation({
			actionAppearance: themedActions,
			override: {
				blocking,
				layout,
				position,
				primaryActions: localPrimaryActions,
				scrollLock: localScrollLock,
				trapFocus: localTrapFocus,
				variant,
			},
			policy: consent.snapshot.policyRule,
			presentation: {
				...consent.state.presentation,
				prompt: {
					scrollLock: theme.scrollLock,
					trapFocus: theme.trapFocus,
					...consent.state.presentation?.prompt,
				},
			},
			surface: 'prompt',
		})
	);
	const actionGroups = $derived(presentation.actionGroups);
	const primaryActions = $derived(presentation.primaryActions);
	// Additional buttons that open preferences, styled as underlined text.
	const preferenceControls = $derived(presentation.preferenceControls);
	// A notice offers dismiss alone; with no primary resolved it takes the lead.
	const dismissIsPrimary = $derived(
		primaryActions.length === 0 &&
			presentation.orderedActions.length === 1 &&
			presentation.orderedActions[0] === 'dismiss'
	);
	const promptKind = $derived(consent.snapshot.policyRule.prompt);
	const isNotice = $derived(promptKind === 'notice');
	const direction = $derived(presentation.direction);
	const shouldFillActions = $derived(presentation.shouldFillActions);
	const shouldTrapFocus = $derived(presentation.trapFocus);
	const shouldScrollLock = $derived(presentation.scrollLock);
	const resolvedVariant = $derived(presentation.variant);
	const isBlocking = $derived(presentation.blocking);
	// A defaulted corner follows the text direction; a host position is
	// physical and stays put.
	const resolvedPosition = $derived.by(() => {
		const { position: resolved, positionSource } = presentation;
		const corner =
			resolvedVariant === 'floating' || resolvedVariant === 'widget';
		if (textDirection === 'rtl' && positionSource === 'default' && corner) {
			return MIRRORED_POSITIONS[resolved] ?? resolved;
		}
		return resolved;
	});

	$effect(() => {
		if (
			typeof process === 'undefined' ||
			process.env?.NODE_ENV !== 'production'
		) {
			for (const diagnostic of presentation.diagnostics) {
				console.warn(diagnostic.message);
			}
		}
	});

	// Resolved texts. A notice has its own copy: it informs and points at
	// the opt-out instead of asking for permission.
	const englishTranslations = defaultTranslationConfig.translations.en;
	const resolvedTitle = $derived(
		title ??
			(isNotice
				? (translations.cookieBanner.noticeTitle ??
					englishTranslations?.cookieBanner?.noticeTitle)
				: translations.cookieBanner.title)
	);
	const resolvedDescription = $derived(
		description ??
			(isNotice
				? (translations.cookieBanner.noticeDescription ??
					englishTranslations?.cookieBanner?.noticeDescription)
				: translations.cookieBanner.description)
	);
	// Acknowledgement records no category choice.
	const resolvedDismissText = $derived(
		dismissButtonText ??
			translations.common.acknowledge ??
			translations.common.dismiss ??
			englishTranslations?.common?.acknowledge
	);
	const rightLabels = $derived<
		Partial<Record<PolicyRight, string | undefined>>
	>({
		'opt-out':
			translations.rights?.optOut ?? englishTranslations?.rights?.optOut,
		preferences:
			translations.rights?.preferences ??
			englishTranslations?.rights?.preferences,
	});
	const resolvedRejectText = $derived(
		rejectButtonText ?? translations.common.rejectAll
	);
	const resolvedAcceptText = $derived(
		acceptButtonText ?? translations.common.acceptAll
	);
	const resolvedCustomizeText = $derived(
		customizeButtonText ?? translations.common.customize
	);
</script>

{#if visibility.isMounted && visibility.shouldRender}
	<div use:portal>
		{#if shouldScrollLock}
			<Overlay
				{styles}
				entering={!disableAnimation}
				lateEntry={visibility.lateEntry && !disableAnimation}
				visible={visibility.isVisible}
			/>
		{/if}
		<div
			bind:this={visibility.bannerEl}
			class={finalClassName}
			style={toStyleAttribute(rootStyle.style)}
			dir={textDirection}
			data-variant={resolvedVariant}
			data-position={resolvedPosition}
			data-blocking={isBlocking ? 'true' : undefined}
			data-prompt={promptKind}
			data-model={consent.state.model}
			data-entry={visibility.lateEntry && !disableAnimation
				? 'late'
				: undefined}
			data-testid="consent-banner-root"
			use:scrollLock={shouldScrollLock}
		>
			<div class={noStyle ? '' : styles.cardShell || ''}>
				<Branding
					{hideBranding}
					{noStyle}
					variant="banner-tag"
					themeKey="consentBannerTag"
					data-testid="consent-banner-branding"
				/>
				<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
				<div
					class={cardStyle.className || ''}
					style={toStyleAttribute(cardStyle.style)}
					data-testid="consent-banner-card"
					tabindex="-1"
					role={isBlocking ? 'dialog' : 'region'}
					aria-modal={isBlocking ? 'true' : undefined}
					aria-label={resolvedTitle}
					use:focusTrap={shouldTrapFocus}
				>
					<div
						class={headerStyle.className || ''}
						style={toStyleAttribute(headerStyle.style)}
						data-testid="consent-banner-header"
					>
						<h2
							class={titleStyle.className || ''}
							style={toStyleAttribute(titleStyle.style)}
							data-testid="consent-banner-title"
						>
							{resolvedTitle}
						</h2>
						<div
							class={descriptionStyle.className || ''}
							style={toStyleAttribute(descriptionStyle.style)}
							data-context="banner"
							data-testid="consent-banner-description"
						>
							{resolvedDescription}
							<InlineLegalLinks
								links={legalLinks}
								testIdPrefix="consent-banner-legal-link"
							/>
						</div>
					</div>
					<PolicyActionsRenderer
						{actionGroups}
						{primaryActions}
						{shouldFillActions}
						{direction}
						{noStyle}
						footerClassName={footerStyle.className || ''}
						footerStyle={toStyleAttribute(footerStyle.style)}
						footerSubGroupClassName={footerSubGroupStyle.className || ''}
						footerSubGroupStyle={toStyleAttribute(footerSubGroupStyle.style)}
						footerTestId="consent-banner-footer"
						footerSubGroupTestId="consent-banner-footer-sub-group"
					>
						{#snippet leading()}
							{#if preferenceControls.length > 0}
								<div
									class={rightsStyle.className || ''}
									style={toStyleAttribute(rightsStyle.style)}
									data-testid="consent-banner-rights"
								>
									{#each preferenceControls as right (right)}
										<button
											type="button"
											class={rightLinkStyle.className || ''}
											style={toStyleAttribute(rightLinkStyle.style)}
											data-action="right"
											data-right={right}
											data-c15t-rights={consent.snapshot.policyRule.rights.join(
												' '
											)}
											data-testid={`consent-banner-right-link-${right}`}
											onclick={openPreferences}
										>
											{rightLabels[right] ?? right}
										</button>
									{/each}
								</div>
							{/if}
						{/snippet}
						{#snippet renderAction(action: string, isPrimary: boolean)}
							{#if action === 'reject'}
								<ConsentButton
									action="reject-consent"
									variant={themedActions.reject.variant ??
										(isPrimary ? 'primary' : 'neutral')}
									mode={themedActions.reject.mode ?? 'stroke'}
									closeConsentBanner
									data-action="reject"
									data-testid="consent-banner-reject-button"
								>
									{resolvedRejectText}
								</ConsentButton>
							{:else if action === 'accept'}
								<ConsentButton
									action="accept-consent"
									variant={themedActions.accept.variant ??
										(isPrimary ? 'primary' : 'neutral')}
									mode={themedActions.accept.mode ?? 'stroke'}
									closeConsentBanner
									data-action="accept"
									data-testid="consent-banner-accept-button"
								>
									{resolvedAcceptText}
								</ConsentButton>
							{:else if action === 'dismiss'}
								<ConsentButton
									action="dismiss-notice"
									variant={themedActions.dismiss.variant ??
										(isPrimary || dismissIsPrimary ? 'primary' : 'neutral')}
									mode={themedActions.dismiss.mode ?? 'stroke'}
									data-action="dismiss"
									data-testid="consent-banner-dismiss-button"
								>
									{resolvedDismissText}
								</ConsentButton>
							{:else if action === 'customize'}
								<ConsentButton
									action="open-consent-dialog"
									variant={themedActions.customize.variant ??
										(isPrimary ? 'primary' : 'neutral')}
									mode={themedActions.customize.mode ?? 'stroke'}
									data-action="customize"
									data-testid="consent-banner-customize-button"
								>
									{resolvedCustomizeText}
								</ConsentButton>
							{/if}
						{/snippet}
					</PolicyActionsRenderer>
				</div>
			</div>
		</div>
	</div>
{/if}
