// examples/demo/app/(ssr)/ssr/page.tsx
import { CTA } from '../../../components/cta';
import { Footer } from '../../../components/footer';
import { Header } from '../../../components/header';
import { Hero } from '../../../components/hero';
import { HowItWorks } from '../../../components/how-it-works';
import { Pricing } from '../../../components/pricing';
import { Stats } from '../../../components/stats';
import { Testimonials } from '../../../components/testimonials';
import { VideoDemo } from '../../../components/video-demo';

export default function Home() {
	return (
		<main className="min-h-screen">
			<Header />
			<Hero />
			<Stats />
			{/* <Features /> */}
			<VideoDemo />
			<HowItWorks />
			<Pricing />
			<Testimonials />
			<CTA />
			<Footer />
		</main>
	);
}

// examples/sveltekit-demo/src/routes/(showcase)/ssr/+page.svelte
<script lang="ts">
	import CTA from '$lib/components/CTA.svelte';
	import Footer from '$lib/components/Footer.svelte';
	import Header from '$lib/components/Header.svelte';
	import Hero from '$lib/components/Hero.svelte';
	import HowItWorks from '$lib/components/HowItWorks.svelte';
	import Pricing from '$lib/components/Pricing.svelte';
	import Stats from '$lib/components/Stats.svelte';
	import Testimonials from '$lib/components/Testimonials.svelte';
	import VideoDemo from '$lib/components/VideoDemo.svelte';
</script>

<main class="min-h-screen">
	<Header />
	<Hero />
	<Stats />
	<VideoDemo />
	<HowItWorks />
	<Pricing />
	<Testimonials />
	<CTA />
	<Footer />
</main>
