// examples/showcase-gated-embeds/components/site-footer.tsx
'use client';

import { ConsentDialogLink } from 'c15t/next';

export const SiteFooter = () => (
	<footer className="site-footer">
		<div className="site-footer-inner">
			<p>Northwind Coffee. Small-batch roasters in Portland, Oregon.</p>
			<ul className="footer-links">
				<li>
					<ConsentDialogLink className="footer-button">
						Privacy settings
					</ConsentDialogLink>
				</li>
			</ul>
		</div>
	</footer>
);

// examples/showcase-nuxt-theme/app/components/site-footer.vue
<template>
	<footer class="site-footer">
		<div class="shell">
			<p>Northwind Coffee Roasters. Roasted Tuesdays and Fridays.</p>
			<ul>
				<li><NuxtLink to="/privacy">Privacy policy</NuxtLink></li>
				<li>
					<ConsentDialogLink class="footer-link">
						Privacy settings
					</ConsentDialogLink>
				</li>
			</ul>
		</div>
	</footer>
</template>
