// packages/astro/src/components/islands/consent-dialog-surface.svelte
<!--
	The on-demand dialog island.

	Mounted with Svelte 5's `mount()` the first time something opens a
	dialog — never with `client:load` — so a visitor who never opens the
	preference centre downloads no framework code at all.

	The provider renders against the page's runtime rather than building one
	of its own: Astro islands cannot see each other's context, so the kernel
	has to be owned outside the component tree. The provider borrows it and
	leaves `start()`/`dispose()` to the owner.
-->
<script lang="ts">
	import type { ConsentRuntime } from '@c15t/core/runtime';
	import { ConsentDialog, ConsentManagerProvider } from '@c15t/svelte';
	import type { Component } from 'svelte';

	let {
		options,
		runtime,
		kind = 'preferences',
		tab,
	}: {
		options: Record<string, unknown>;
		runtime: ConsentRuntime;
		kind?: 'preferences' | 'iab';
		/** Which IAB preference-centre tab to open on. */
		tab?: 'purposes' | 'vendors';
	} = $props();

	// The TCF surface is the larger half of this island and only an IAB site
	// ever opens it, so it arrives on its own chunk.
	let IABDialog = $state<Component | null>(null);

	$effect(() => {
		if (kind !== 'iab' || IABDialog) {
			return;
		}
		void (async () => {
			const module = await import('./iab-dialog-surface.svelte');
			IABDialog = module.default as Component;
		})();
	});
</script>

<ConsentManagerProvider
	{runtime}
	options={options as never}
>
	{#if kind === 'iab'}
		{#if IABDialog}
			<IABDialog {tab} />
		{/if}
	{:else}
		<ConsentDialog />
	{/if}
</ConsentManagerProvider>

// packages/astro/src/components/islands/consent-dialog-surface.vue
<!--
	The on-demand Vue dialog island.

	Mounted as its own Vue app the first time something opens a dialog —
	never with `client:load` — so a visitor who never opens the preference
	centre downloads no consent UI at all.

	The adapter installs `c15tVue` with the page's runtime before mounting
	this component: Astro islands cannot see each other's provides, so the
	kernel has to be owned outside the app. The plugin borrows it and leaves
	`start()`/`dispose()` to the owner.
-->
<script setup lang="ts">
import ConsentManager from '@c15t/vue/runtime/components/consent-manager.vue';
import { defineAsyncComponent } from 'vue';

withDefaults(
	defineProps<{
		kind?: 'preferences' | 'iab';
		/** Which IAB preference-centre tab to open on. */
		tab?: 'purposes' | 'vendors';
	}>(),
	{ kind: 'preferences', tab: undefined }
);

// The TCF surface is the larger half of this island and only an IAB site
// ever opens it, so it arrives on its own chunk.
const IABDialogSurface = defineAsyncComponent(
	() => import('./iab-dialog-surface.vue')
);
</script>

<template>
	<IABDialogSurface
		v-if="kind === 'iab'"
		:tab="tab"
	/>
	<ConsentManager v-else />
</template>
