// packages/astro/src/components/islands/panel-surface.tsx
/**
 * The on-demand React dialog island.
 *
 * Mounted with `createRoot()` the first time something opens a dialog —
 * never with `client:load` — so a visitor who never opens the preference
 * centre downloads no React from us at all.
 *
 * The provider renders against the page's runtime rather than building one
 * of its own: Astro islands cannot see each other's context, so the kernel
 * has to be owned outside the component tree. `<ConsentProvider runtime>`
 * borrows it and leaves `start()`/`dispose()` to the owner.
 *
 * `<ConsentDraftProvider>` is what makes Save work. `useConsentDraft()`
 * falls back to a draft per hook call when no provider is in scope, so the
 * category toggles and the Save button would each stage into their own
 * copy: the switch would flip, and the save would commit nothing.
 */

import type { LegalLinks } from '@c15t/core';
import type { ConsentRuntime } from '@c15t/core/runtime';
import {
	ConsentDialog,
	ConsentDraftProvider,
	ConsentProvider,
} from '@c15t/react';
import { useEffect, useState } from 'react';
import type { ComponentType } from 'react';

import type { DialogPresentationOptions } from '../../ui/provider-props';
import type { IABDialogSurfaceProps } from './iab-dialog-surface';

// The TCF surface is the larger half of this island and only an IAB site
// ever opens it, so it arrives on its own chunk.
let loadedIABSurface: ComponentType<IABDialogSurfaceProps> | undefined;
let iabSurfacePromise:
	| Promise<ComponentType<IABDialogSurfaceProps>>
	| undefined;
const loadIABSurface = () => {
	iabSurfacePromise ??= (async () => {
		const module = await import('./iab-dialog-surface');
		loadedIABSurface = module.default;
		return loadedIABSurface;
	})();
	return iabSurfacePromise;
};

// This island only mounts in the browser. Resolve its component through state
// so the first open does not wait for React's Suspense retry throttle.
const IABDialogSurface = (props: IABDialogSurfaceProps) => {
	const [loadedComponent, setLoadedComponent] = useState(
		() => loadedIABSurface
	);
	const [failure, setFailure] = useState<{ error: unknown }>();
	useEffect(() => {
		if (loadedComponent) {
			return;
		}
		let active = true;
		void (async () => {
			try {
				const loaded = await loadIABSurface();
				if (active) {
					setLoadedComponent(() => loaded);
				}
			} catch (error) {
				if (active) {
					setFailure({ error });
				}
			}
		})();
		return () => {
			active = false;
		};
	}, [loadedComponent]);
	if (failure) {
		throw failure.error;
	}
	const Component = loadedComponent;
	return Component ? <Component {...props} /> : null;
};

/** Props the React dialog adapter passes in. */
export interface ConsentDialogSurfaceProps {
	/** The page-level runtime. The provider borrows it, it does not own it. */
	runtime: ConsentRuntime;
	/** Presentation options forwarded to the provider. */
	options: DialogPresentationOptions;
	/** Which dialog to render. */
	kind?: 'preferences' | 'iab';
	/** Which IAB preference-centre tab to open on. */
	tab?: 'purposes' | 'vendors';
	/** Which legal links the preferences dialog shows. */
	legalLinks?: (keyof LegalLinks)[] | null;
}

const ConsentDialogSurface = ({
	runtime,
	options,
	kind = 'preferences',
	tab,
	legalLinks,
}: ConsentDialogSurfaceProps) => (
	<ConsentProvider
		runtime={runtime}
		options={options}
	>
		{kind === 'iab' ? (
			<IABDialogSurface tab={tab} />
		) : (
			<ConsentDraftProvider>
				<ConsentDialog legalLinks={legalLinks} />
			</ConsentDraftProvider>
		)}
	</ConsentProvider>
);

export default ConsentDialogSurface;

// packages/astro/src/components/islands/panel-surface.svelte
<!--
	The on-demand dialog island.

	Mounted with Svelte 5's `mount()` the first time something opens a
	dialog — never with `client:load` — so a visitor who never opens the
	preference centre downloads no framework code at all.

	The provider renders against the page's runtime rather than building one
	of its own: Astro islands cannot see each other's context, so the kernel
	has to be owned outside the component tree. The provider borrows it and
	leaves `start()`/`dispose()` to the owner.
-->
<script lang="ts">
	import type { LegalLinks } from '@c15t/core';
	import type { ConsentRuntime } from '@c15t/core/runtime';
	import { ConsentDialog, ConsentProvider } from '@c15t/svelte';
	import type { Component } from 'svelte';

	// The injected stylesheet covers the banner and the dialog. The Svelte
	// primitives the dialog renders need these rules too.
	import '@c15t/ui/styles/primitives.css';

	let {
		options,
		runtime,
		kind = 'preferences',
		tab,
		legalLinks,
	}: {
		options: Record<string, unknown>;
		runtime: ConsentRuntime;
		kind?: 'preferences' | 'iab';
		/** Which IAB preference-centre tab to open on. */
		tab?: 'purposes' | 'vendors';
		/** Which legal links the preferences dialog shows. */
		legalLinks?: (keyof LegalLinks)[] | null;
	} = $props();

	// The TCF surface is the larger half of this island and only an IAB site
	// ever opens it, so it arrives on its own chunk.
	let IABDialog = $state<Component | null>(null);

	$effect(() => {
		if (kind !== 'iab' || IABDialog) {
			return;
		}
		void (async () => {
			const module = await import('./iab-dialog-surface.svelte');
			IABDialog = module.default as Component;
		})();
	});
</script>

<ConsentProvider
	{runtime}
	options={options as never}
>
	{#if kind === 'iab'}
		{#if IABDialog}
			<IABDialog {tab} />
		{/if}
	{:else}
		<ConsentDialog {legalLinks} />
	{/if}
</ConsentProvider>
