// benchmarks/nuxt-browser-bench/app/components/benchmark-page.vue
<script
	setup
	lang="ts"
>
import { useConsentActiveUI } from '#c15t/composables';

defineProps<{
	scenario: 'ssr' | 'client' | 'repeat-visitor';
}>();

const activeUI = useConsentActiveUI();

function openPreferences() {
	activeUI.value = 'manager';
}
</script>

<template>
	<BenchmarkProbe :scenario="scenario" />
	<main style="padding: 2rem; font-family: system-ui, sans-serif">
		<h1>Nuxt Benchmark: {{ scenario }}</h1>
		<button
			id="open-preferences"
			type="button"
			@click="openPreferences"
		>
			Open Preferences
		</button>
	</main>
</template>

// benchmarks/sveltekit-browser-bench/src/lib/benchmark-page.svelte
<script lang="ts">
	/**
	 * Page body shared by the measured arms. `#open-preferences` is the
	 * repeat-visitor interaction target — the only consent surface a
	 * returning visitor can reach.
	 */
	import type { SvelteBenchScenario } from '$lib/benchmark-probe.svelte';
	import { getConsentKernel } from '@c15t/svelte';

	let { scenario }: { scenario: SvelteBenchScenario } = $props();

	const kernel = getConsentKernel();

	const openPreferences = function openPreferences() {
		kernel.set.activeUI('dialog');
	};
</script>

<main style="padding: 2rem; font-family: system-ui, sans-serif">
	<h1>SvelteKit Benchmark: {scenario}</h1>
	<button
		id="open-preferences"
		onclick={openPreferences}
		type="button"
	>
		Open Preferences
	</button>
</main>
