// benchmarks/nuxt-browser-bench/app/components/benchmark-probe.vue
<script setup lang="ts">
import { nextTick, onBeforeUpdate, onMounted, watch } from 'vue';

import {
	useConsentActiveUI,
	useConsentInit,
	useConsentSnapshot,
} from '#c15t/composables';

const props = defineProps<{
	scenario: NuxtBenchScenario;
}>();

type NuxtBenchScenario =
	| 'ssr'
	| 'ssr-manifest'
	| 'client'
	| 'client-manifest'
	| 'repeat-visitor';

interface NuxtBenchState {
	scenario: NuxtBenchScenario;
	startedAtMs: number;
	mountCount: number;
	renderCount: number;
	activeUI: string;
	overrides?: {
		country?: string;
		region?: string;
		language?: string;
		gpc?: boolean;
	};
	location?: {
		countryCode?: string | null;
		regionCode?: string | null;
	} | null;
	hasConsented?: boolean;
	onBannerFetchedMs?: number;
	cls?: number;
	bannerReadyMs?: number;
	bannerVisibleMs?: number;
	bannerPaintMs?: number | null;
	onBannerFetchedCount: number;
	onConsentSetCount: number;
	onErrorCount: number;
}

interface BenchmarkElementTimingEntry extends PerformanceEntry {
	identifier?: string;
	renderTime?: number;
	loadTime?: number;
}

declare global {
	interface Window {
		__c15tNuxtBench?: NuxtBenchState;
	}
}

const BANNER_ELEMENT_TIMING_NAME = 'c15t-consent-banner';

const activeUI = useConsentActiveUI();
const init = useConsentInit();
const snapshot = useConsentSnapshot();

function getBenchState(): NuxtBenchState | undefined {
	if (!import.meta.client) {
		return undefined;
	}

	if (
		!window.__c15tNuxtBench ||
		window.__c15tNuxtBench.scenario !== props.scenario
	) {
		window.__c15tNuxtBench = {
			scenario: props.scenario,
			startedAtMs: performance.now(),
			mountCount: 0,
			renderCount: 0,
			activeUI: 'none',
			onBannerFetchedCount: 0,
			onConsentSetCount: 0,
			onErrorCount: 0,
		};
	}

	return window.__c15tNuxtBench;
}

function normalizeActiveUI(value: unknown): string {
	if (value === 'manager') {
		return 'dialog';
	}
	if (value === null || value === undefined) {
		return 'none';
	}
	return String(value);
}

function updateSnapshotProbe(state: NuxtBenchState) {
	state.overrides = { ...snapshot.value.overrides };
	state.location = snapshot.value.location
		? {
				countryCode: snapshot.value.location.countryCode,
				regionCode: snapshot.value.location.regionCode,
			}
		: null;
	state.hasConsented = snapshot.value.hasConsented;
}

function isElementVisible(element: Element): boolean {
	if (!(element instanceof HTMLElement)) {
		return false;
	}

	const rect = element.getBoundingClientRect();
	if (rect.width <= 0 || rect.height <= 0) {
		return false;
	}

	const style = window.getComputedStyle(element);
	return (
		style.display !== 'none' &&
		style.visibility !== 'hidden' &&
		Number(style.opacity) >= 0.99
	);
}

function hasRunningAnimations(element: Element): boolean {
	if (
		!(element instanceof HTMLElement) ||
		typeof element.getAnimations !== 'function'
	) {
		return false;
	}

	return element
		.getAnimations()
		.some((animation) => animation.playState === 'running');
}

function readBannerPaintMs(): number | null {
	const entries = performance
		.getEntriesByType('element')
		.filter(
			(entry): entry is BenchmarkElementTimingEntry =>
				(entry as BenchmarkElementTimingEntry).identifier ===
				BANNER_ELEMENT_TIMING_NAME
		);
	const entry = entries.at(-1);
	if (!entry) return null;
	for (const value of [entry.renderTime, entry.loadTime, entry.startTime]) {
		if (typeof value === 'number' && Number.isFinite(value) && value > 0) {
			return value;
		}
	}
	return null;
}

function markRepeatVisitorReady() {
	const state = getBenchState();
	if (!state || props.scenario !== 'repeat-visitor') {
		return;
	}
	if (
		snapshot.value.hasConsented &&
		normalizeActiveUI(activeUI.value) === 'none'
	) {
		state.bannerReadyMs = state.bannerReadyMs ?? 0;
		state.bannerVisibleMs = state.bannerVisibleMs ?? 0;
		state.bannerPaintMs = state.bannerPaintMs ?? null;
	}
}

function watchBannerVisibility() {
	const state = getBenchState();
	if (
		!state ||
		state.bannerVisibleMs !== undefined ||
		normalizeActiveUI(activeUI.value) !== 'banner'
	) {
		markRepeatVisitorReady();
		return;
	}

	let frameId = 0;
	const check = () => {
		const latest = getBenchState();
		if (!latest || latest.bannerVisibleMs !== undefined) {
			return;
		}

		const bannerRoot = document.querySelector(
			'[data-testid="consent-banner-root"]'
		);
		if (bannerRoot instanceof HTMLElement) {
			bannerRoot.setAttribute('elementtiming', BANNER_ELEMENT_TIMING_NAME);
		}
		const acceptButton = document.querySelector(
			'[data-testid="consent-banner-accept-button"]'
		);

		const ready =
			!!bannerRoot &&
			!!acceptButton &&
			isElementVisible(bannerRoot) &&
			isElementVisible(acceptButton);

		if (ready && latest.bannerReadyMs === undefined) {
			latest.bannerReadyMs = performance.now();
		}

		const visible =
			ready &&
			!hasRunningAnimations(bannerRoot) &&
			!hasRunningAnimations(acceptButton);

		if (visible) {
			latest.bannerVisibleMs = performance.now();
			latest.bannerPaintMs = readBannerPaintMs();
			return;
		}

		frameId = window.requestAnimationFrame(check);
	};

	frameId = window.requestAnimationFrame(check);
	return () => window.cancelAnimationFrame(frameId);
}

if (import.meta.client) {
	const state = getBenchState();
	if (state) {
		state.renderCount += 1;
		updateSnapshotProbe(state);
	}
}

onBeforeUpdate(() => {
	const state = getBenchState();
	if (state) {
		state.renderCount += 1;
		updateSnapshotProbe(state);
	}
});

onMounted(() => {
	const state = getBenchState();
	if (state) {
		state.mountCount += 1;
	}
});

watch(
	init,
	(value) => {
		const state = getBenchState();
		if (state && value) {
			state.onBannerFetchedCount += 1;
			state.onBannerFetchedMs = state.onBannerFetchedMs ?? performance.now();
		}
	},
	{ immediate: true }
);

watch(
	() => snapshot.value.hasConsented,
	(hasConsented, hadConsented) => {
		const state = getBenchState();
		if (state && hasConsented && !hadConsented) {
			state.onConsentSetCount += 1;
		}
		void (async () => {
			await nextTick();
			markRepeatVisitorReady();
		})();
	},
	{ immediate: true }
);

watch(
	snapshot,
	() => {
		const state = getBenchState();
		if (state) {
			updateSnapshotProbe(state);
		}
	},
	{ immediate: true }
);

watch(
	activeUI,
	(value) => {
		const state = getBenchState();
		if (state) {
			state.activeUI = normalizeActiveUI(value);
		}
		void (async () => {
			await nextTick();
			watchBannerVisibility();
		})();
	},
	{ immediate: true }
);
</script>

<template>
	<span hidden>{{ activeUI }}</span>
</template>

// benchmarks/sveltekit-browser-bench/src/lib/benchmark-probe.svelte
<script
	lang="ts"
	module
>
	/**
	 * In-page probe for the SvelteKit browser bench.
	 *
	 * Publishes one object on `window.__c15tSvelteBench` that the Playwright
	 * runner polls. `bannerReadyMs` / `bannerVisibleMs` use the same
	 * rAF-settled definition as the Nuxt probe — banner root *and* accept
	 * button laid out, painted and not animating — so the two suites'
	 * numbers mean the same thing.
	 */
	import type { ConsentSnapshot } from '@c15t/svelte';

	/** Scenario names the SvelteKit bench app implements. */
	export type SvelteBenchScenario =
		| 'ssr'
		| 'ssr-manifest'
		| 'client'
		| 'client-manifest'
		| 'repeat-visitor';

	/** The shape the runner reads out of the page. */
	export interface SvelteBenchState {
		scenario: string;
		startedAtMs: number;
		mountCount: number;
		renderCount: number;
		activeUI: string;
		overrides: {
			country?: string;
			region?: string;
			language?: string;
			gpc?: boolean;
		};
		location: {
			countryCode?: string | null;
			regionCode?: string | null;
		} | null;
		hasConsented: boolean;
		bannerReadyMs?: number;
		bannerVisibleMs?: number;
		bannerPaintMs?: number | null;
		onBannerFetchedMs?: number;
		onBannerFetchedCount: number;
		onConsentSetCount: number;
		onErrorCount: number;
	}

	interface BenchmarkElementTimingEntry extends PerformanceEntry {
		identifier?: string;
		renderTime?: number;
		loadTime?: number;
	}

	declare global {
		interface Window {
			__c15tSvelteBench?: SvelteBenchState;
		}
	}

	const BANNER_ELEMENT_TIMING_NAME = 'c15t-consent-banner';

	const isElementVisible = function isElementVisible(
		element: Element
	): boolean {
		if (!(element instanceof HTMLElement)) {
			return false;
		}
		const rect = element.getBoundingClientRect();
		if (rect.width <= 0 || rect.height <= 0) {
			return false;
		}
		const style = window.getComputedStyle(element);
		return (
			style.display !== 'none' &&
			style.visibility !== 'hidden' &&
			Number(style.opacity) >= 0.99
		);
	};

	const hasRunningAnimations = function hasRunningAnimations(
		element: Element
	): boolean {
		if (
			!(element instanceof HTMLElement) ||
			typeof element.getAnimations !== 'function'
		) {
			return false;
		}
		return element
			.getAnimations()
			.some((animation) => animation.playState === 'running');
	};

	const readBannerPaintMs = function readBannerPaintMs(): number | null {
		const entries = performance
			.getEntriesByType('element')
			.filter(
				(entry): entry is BenchmarkElementTimingEntry =>
					(entry as BenchmarkElementTimingEntry).identifier ===
					BANNER_ELEMENT_TIMING_NAME
			);
		const entry = entries.at(-1);
		if (!entry) {
			return null;
		}
		for (const value of [entry.renderTime, entry.loadTime, entry.startTime]) {
			if (typeof value === 'number' && Number.isFinite(value) && value > 0) {
				return value;
			}
		}
		return null;
	};
</script>

<script lang="ts">
	import { getConsentKernel } from '@c15t/svelte';
	import { onMount } from 'svelte';

	let { scenario }: { scenario: SvelteBenchScenario } = $props();

	const kernel = getConsentKernel();

	const getState = function getState(): SvelteBenchState {
		if (
			!window.__c15tSvelteBench ||
			window.__c15tSvelteBench.scenario !== scenario
		) {
			window.__c15tSvelteBench = {
				activeUI: 'none',
				hasConsented: false,
				location: null,
				mountCount: 0,
				onBannerFetchedCount: 0,
				onConsentSetCount: 0,
				onErrorCount: 0,
				overrides: {},
				renderCount: 0,
				scenario,
				startedAtMs: performance.now(),
			};
		}
		return window.__c15tSvelteBench;
	};

	/**
	 * Repeat visitors never see a banner, so "ready" is "the kernel resolved
	 * with stored consent and decided to show nothing". Recorded as `0` for
	 * the same reason the Nuxt probe does: there is no banner to wait for.
	 */
	const markRepeatVisitorReady = function markRepeatVisitorReady(
		state: SvelteBenchState,
		snapshot: ConsentSnapshot
	): void {
		if (scenario !== 'repeat-visitor') {
			return;
		}
		if (snapshot.hasConsented && (snapshot.activeUI ?? 'none') === 'none') {
			state.bannerReadyMs ??= 0;
			state.bannerVisibleMs ??= 0;
			state.bannerPaintMs ??= null;
		}
	};

	const watchBannerVisibility = function watchBannerVisibility(): void {
		const state = getState();
		if (state.bannerVisibleMs !== undefined || state.activeUI !== 'banner') {
			return;
		}

		const check = () => {
			const latest = getState();
			if (latest.bannerVisibleMs !== undefined) {
				return;
			}

			const bannerRoot = document.querySelector(
				'[data-testid="consent-banner-root"]'
			);
			if (bannerRoot instanceof HTMLElement) {
				bannerRoot.setAttribute('elementtiming', BANNER_ELEMENT_TIMING_NAME);
			}
			const acceptButton = document.querySelector(
				'[data-testid="consent-banner-accept-button"]'
			);

			const ready =
				!!bannerRoot &&
				!!acceptButton &&
				isElementVisible(bannerRoot) &&
				isElementVisible(acceptButton);

			if (ready && latest.bannerReadyMs === undefined) {
				latest.bannerReadyMs = performance.now();
			}

			if (
				ready &&
				!hasRunningAnimations(bannerRoot) &&
				!hasRunningAnimations(acceptButton)
			) {
				latest.bannerVisibleMs = performance.now();
				latest.bannerPaintMs = readBannerPaintMs();
				return;
			}

			window.requestAnimationFrame(check);
		};

		window.requestAnimationFrame(check);
	};

	const publish = function publish(snapshot: ConsentSnapshot): void {
		const state = getState();
		state.renderCount += 1;
		const nextActiveUI = snapshot.activeUI ?? 'none';
		if (snapshot.hasConsented && !state.hasConsented) {
			state.onConsentSetCount += 1;
		}
		if (snapshot.policy && state.onBannerFetchedMs === undefined) {
			state.onBannerFetchedCount += 1;
			state.onBannerFetchedMs = performance.now();
		}
		state.activeUI = nextActiveUI;
		state.hasConsented = snapshot.hasConsented;
		state.location = snapshot.location
			? {
					countryCode: snapshot.location.countryCode,
					regionCode: snapshot.location.regionCode,
				}
			: null;
		state.overrides = { ...snapshot.overrides };
		markRepeatVisitorReady(state, snapshot);
		watchBannerVisibility();
	};

	onMount(() => {
		getState().mountCount += 1;
		publish(kernel.getSnapshot());
		return kernel.subscribe(publish);
	});
</script>
