// packages/vue/src/runtime/primitives/tabs/tabs-list.vue
<script setup lang="ts">
import { getDataDisabled } from '@c15t/ui/primitives';
import { computed } from 'vue';

import { useTabsRootContext } from './context';

const props = withDefaults(defineProps<{ class?: string }>(), {
	class: undefined,
});

const root = useTabsRootContext();
const dataDisabled = computed(() => getDataDisabled(root.disabled.value));
</script>

<template>
	<div
		role="tablist"
		:aria-orientation="root.orientation.value"
		:class="props.class"
		data-slot="tabs-list"
		:data-orientation="root.orientation.value"
		:data-disabled="dataDisabled"
	>
		<slot />
	</div>
</template>

// packages/svelte/src/lib/primitives/tabs/tabs-list.svelte
<script lang="ts">
	import { getDataDisabled } from '@c15t/ui/primitives';
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';

	import { getTabsRootContext } from './context';

	const root = getTabsRootContext();

	const disabled = $derived(root.disabled);
	const rootOrientation = $derived(root.orientation);
	const dataDisabled = $derived(getDataDisabled(disabled));

	let {
		children,
		class: className,
		orientation: orientationProp,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & {
		children?: Snippet;
		class?: string;
		orientation?: 'horizontal' | 'vertical';
	} = $props();

	const orientation = $derived(orientationProp ?? rootOrientation);
</script>

<div
	role="tablist"
	aria-orientation={orientation}
	class={className}
	data-slot="tabs-list"
	data-orientation={orientation}
	data-disabled={dataDisabled}
	{...restProps}
>
	{@render children?.()}
</div>
