// packages/vue/src/runtime/primitives/tabs/tabs-content.vue
<script setup lang="ts">
import { getTabPanelState } from '@c15t/ui/primitives';
import { computed } from 'vue';

import { useTabsRootContext } from './context';

const props = withDefaults(
	defineProps<{ class?: string; forceMount?: boolean; value: string }>(),
	{ class: undefined, forceMount: false }
);

const root = useTabsRootContext();

const isSelected = computed(() => root.value.value === props.value);
const dataState = computed(() => getTabPanelState(isSelected.value));
const contentId = computed(() => `${root.baseId}-content-${props.value}`);
const triggerId = computed(() => `${root.baseId}-trigger-${props.value}`);
</script>

<template>
	<div
		v-if="props.forceMount || isSelected"
		:id="contentId"
		role="tabpanel"
		:tabindex="0"
		:hidden="!isSelected"
		:aria-labelledby="triggerId"
		:class="props.class"
		data-slot="tabs-content"
		:data-state="dataState"
	>
		<slot />
	</div>
</template>

// packages/svelte/src/lib/primitives/tabs/tabs-content.svelte
<script lang="ts">
	import { getTabPanelState } from '@c15t/ui/primitives';
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';
	import { getTabsRootContext } from './context';

	const root = getTabsRootContext();

	let {
		children,
		class: className,
		forceMount = false,
		value,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & {
		children?: Snippet;
		class?: string;
		forceMount?: boolean;
		value: string;
	} = $props();

	const baseId = $derived(root.baseId);
	const selectedValue = $derived(root.value);
	const isSelected = $derived(selectedValue === value);
	const dataState = $derived(getTabPanelState(isSelected));
	const contentId = $derived(`${baseId}-content-${value}`);
	const triggerId = $derived(`${baseId}-trigger-${value}`);
</script>

{#if forceMount || isSelected}
	<div
		id={contentId}
		role="tabpanel"
		tabindex={0}
		hidden={!isSelected}
		aria-labelledby={triggerId}
		class={className}
		data-slot="tabs-content"
		data-state={dataState}
		{...restProps}
	>
		{@render children?.()}
	</div>
{/if}
