// internals/fixtures/nuxt/app/components/ExperimentReadout.vue
<script setup lang="ts">
/**
 * Demo only: the banner-shape experiment readout. `C15T_NUXT_EXPERIMENT=1`
 * puts the experiment in the module config (see nuxt.config.ts) and the arm
 * comes from `useExperiment()`. Module config is serializable, so it takes
 * no callbacks; this component listens to the kernel's events instead, lists
 * each impression and choice made under the arm and pushes them to
 * `window.dataLayer`.
 */
import { onMounted, onUnmounted, ref } from 'vue';

const experimentConfigured = Boolean(useConsentConfig().value.experiment);
const experiment = useExperiment();
const kernel = useConsentKernel();
const experimentEvents = ref<
	{
		name: 'c15t_surface_shown' | 'c15t_choice_recorded';
		arm: string;
		detail: string;
	}[]
>([]);

const pushToDataLayer = (event: Record<string, unknown>) => {
	const page = window as Window & { dataLayer?: unknown[] };
	page.dataLayer ??= [];
	page.dataLayer.push(event);
};

let stopReporting: (() => void)[] = [];
onMounted(() => {
	if (!experimentConfigured) {
		return;
	}
	stopReporting = [
		kernel.events.on('surface:shown', (event) => {
			if (!event.experiment) {
				return;
			}
			pushToDataLayer({
				arm: event.experiment.arm,
				event: 'c15t_surface_shown',
				experiment_id: event.experiment.id,
				surface: event.surface,
			});
			experimentEvents.value.push({
				arm: event.experiment.arm,
				detail: event.surface,
				name: 'c15t_surface_shown',
			});
		}),
		kernel.events.on('choice:recorded', (event) => {
			if (!event.experiment) {
				return;
			}
			pushToDataLayer({
				arm: event.experiment.arm,
				consent_action: event.consentAction,
				event: 'c15t_choice_recorded',
				experiment_id: event.experiment.id,
			});
			experimentEvents.value.push({
				arm: event.experiment.arm,
				detail: event.consentAction,
				name: 'c15t_choice_recorded',
			});
		}),
	];
});
onUnmounted(() => {
	for (const stop of stopReporting) {
		stop();
	}
});
</script>

<template>
	<section
		v-if="experimentConfigured"
		data-testid="experiment"
	>
		<h2>Banner experiment</h2>
		<p>
			Arm:
			<code data-testid="experiment-arm">{{
				experiment
					? `${experiment.id} · ${experiment.arm} · ${experiment.assignedBy}`
					: 'assigning…'
			}}</code>
		</p>
		<ul>
			<li
				v-for="(event, index) in experimentEvents"
				:key="index"
			>
				<code>{{ event.name }}</code> · {{ event.arm }} · {{ event.detail }}
			</li>
		</ul>
		<p>
			The same events are pushed to <code>window.dataLayer</code>. Build with
			<code>C15T_NUXT_EXPERIMENT_ARM=wall</code> to run the wall arm the way a
			flag provider would.
		</p>
	</section>
</template>

// examples/react/src/experiment-readout.tsx
import type { OnChoiceRecordedPayload, OnSurfaceShownPayload } from 'c15t';
import { useExperiment } from 'c15t/react';
import { useMemo, useState } from 'react';

/** One experiment event the page lists. */
export interface ExperimentLogEntry {
	name: 'c15t_surface_shown' | 'c15t_choice_recorded';
	arm: string;
	/** The surface shown, or the consent action recorded. */
	detail: string;
}

const pushToDataLayer = function pushToDataLayer(
	event: Record<string, unknown>
): void {
	const page = window as Window & { dataLayer?: unknown[] };
	page.dataLayer ??= [];
	page.dataLayer.push(event);
};

/**
 * Provider callbacks that log each impression and choice made under an
 * experiment arm, and push them to `window.dataLayer` for GTM.
 */
export const useExperimentLog = function useExperimentLog() {
	const [events, setEvents] = useState<ExperimentLogEntry[]>([]);
	const callbacks = useMemo(
		() => ({
			onChoiceRecorded: ({
				consentAction,
				experiment,
			}: OnChoiceRecordedPayload) => {
				if (!experiment) {
					return;
				}
				pushToDataLayer({
					arm: experiment.arm,
					consent_action: consentAction,
					event: 'c15t_choice_recorded',
					experiment_id: experiment.id,
				});
				setEvents((previous) => [
					...previous,
					{
						arm: experiment.arm,
						detail: consentAction,
						name: 'c15t_choice_recorded',
					},
				]);
			},
			onSurfaceShown: ({ experiment, surface }: OnSurfaceShownPayload) => {
				if (!experiment) {
					return;
				}
				pushToDataLayer({
					arm: experiment.arm,
					event: 'c15t_surface_shown',
					experiment_id: experiment.id,
					surface,
				});
				setEvents((previous) => [
					...previous,
					{ arm: experiment.arm, detail: surface, name: 'c15t_surface_shown' },
				]);
			},
		}),
		[]
	);
	return { callbacks, events };
};

/** The assigned arm and the events logged so far. */
export const ExperimentReadout = ({
	events,
}: {
	events: readonly ExperimentLogEntry[];
}) => {
	const assignment = useExperiment();
	return (
		<section
			className="card"
			data-testid="experiment"
		>
			<h2>Banner experiment</h2>
			<p>
				Arm:{' '}
				<code data-testid="experiment-arm">
					{assignment
						? `${assignment.id} · ${assignment.arm} · ${assignment.assignedBy}`
						: 'assigning…'}
				</code>
			</p>
			<ul className="statuses">
				{events.map((event, index) => (
					<li
						// oxlint-disable-next-line react/no-array-index-key -- append-only log
						key={index}
					>
						<code>{event.name}</code> · {event.arm} · {event.detail}
					</li>
				))}
			</ul>
			<p>
				The same events are pushed to <code>window.dataLayer</code>.
			</p>
		</section>
	);
};
