// benchmarks/sveltekit-browser-bench/src/routes/+page.svelte
<main style="padding: 2rem; font-family: system-ui, sans-serif">
	<h1>SvelteKit Browser Bench</h1>
	<ul>
		<li><a href="/baseline">baseline</a></li>
		<li><a href="/baseline-client">baseline-client</a></li>
		<li><a href="/ssr">ssr</a></li>
		<li><a href="/ssr-manifest">ssr-manifest</a></li>
		<li><a href="/client">client</a></li>
		<li><a href="/client-manifest">client-manifest</a></li>
		<li><a href="/repeat-visitor">repeat-visitor</a></li>
	</ul>
</main>

// benchmarks/tanstack-start-browser-bench/src/routes/index.tsx
import { createFileRoute, Link } from '@tanstack/react-router';

const HomePage = () => (
	<main style={{ fontFamily: 'system-ui', padding: '2rem' }}>
		<h1>@c15t/tanstack-start Browser Bench</h1>
		<ul>
			<li>
				<Link to="/baseline">/baseline</Link>
			</li>
			<li>
				<Link to="/client">/client</Link>
			</li>
			<li>
				<Link to="/manifest-client">/manifest-client</Link>
			</li>
			<li>
				<Link to="/ssr">/ssr</Link>
			</li>
			<li>
				<Link to="/manifest-ssr">/manifest-ssr</Link>
			</li>
			<li>
				<Link to="/manifest-ssr-proxy">/manifest-ssr-proxy</Link>
			</li>
		</ul>
	</main>
);

export const Route = createFileRoute('/')({
	component: HomePage,
});
