// packages/svelte/src/lib/components/branding.svelte
<script lang="ts">
import styles from '@c15t/ui/styles/components/consent-dialog.module.js';
import { resolveTranslations } from '@c15t/ui/utils';
import { defaultTranslationConfig } from 'c15t';
import { getConsentContext, getThemeContext } from '../context.svelte';
import { resolveComponentStyles } from '../utils';
import C15TIconOnly from './icons/c15-t-icon-only.svelte';
import InthLogo from './icons/inth-logo.svelte';

type ResolvedBranding = 'c15t' | 'inth' | 'none';
type BrandingVariant = 'footer' | 'dialog-tag' | 'banner-tag';
type BrandingThemeKey =
	| 'consentBannerTag'
	| 'consentDialogTag'
	| 'consentWidgetTag'
	| 'iabConsentBannerTag'
	| 'iabConsentDialogTag';

let {
	hideBranding = false,
	noStyle: localNoStyle,
	variant = 'footer',
	themeKey,
	class: className,
	'data-testid': testId,
}: {
	hideBranding?: boolean;
	noStyle?: boolean;
	variant?: BrandingVariant;
	themeKey?: BrandingThemeKey;
	class?: string;
	'data-testid'?: string;
} = $props();

const consent = getConsentContext();
const theme = getThemeContext();

const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);
const branding = $derived(consent.state.branding);
const translations = $derived(
	resolveTranslations(consent.state.translationConfig, defaultTranslationConfig)
);

function resolveBranding(value: string): ResolvedBranding {
	if (value === 'none') {
		return 'none';
	}

	if (value === 'inth' || value === 'consent') {
		return 'inth';
	}

	return 'c15t';
}

const resolvedBranding = $derived(resolveBranding(branding));
const showBranding = $derived(!hideBranding && resolvedBranding !== 'none');
const brandingHref = $derived.by(() => {
	const refParam =
		typeof window !== 'undefined' ? `?ref=${window.location.hostname}` : '';
	return resolvedBranding === 'inth'
		? `https://inth.com${refParam}`
		: `https://c15t.com${refParam}`;
});

const baseClassName = $derived(
	[
		styles.branding,
		variant !== 'footer' ? styles.brandingTag : '',
		variant === 'dialog-tag' ? styles.brandingTagDialog : '',
		variant === 'banner-tag' ? styles.brandingTagBanner : '',
	]
		.filter(Boolean)
		.join(' ')
);

const brandingStyle = $derived(
	resolveComponentStyles(
		themeKey ?? 'consentDialogTag',
		theme.theme,
		{
			baseClassName,
			className,
		},
		noStyle
	)
);
</script>

{#if showBranding}
	<a
		dir="ltr"
		class={brandingStyle.className || ''}
		href={brandingHref}
		data-branding={resolvedBranding}
		data-variant={variant}
		data-testid={testId}
	>
		<span class={styles.brandingCopy || ''}>
			<span class={styles.brandingText || ''}
				>{translations.common.securedBy}</span
			>
		</span>
		{#if resolvedBranding === 'inth'}
			<span
				dir="ltr"
				class={`${styles.brandingWordmark || ''} ${styles.brandingInth || ''}`}
			>
				<InthLogo aria-hidden={true} />
			</span>
		{:else}
			<span
				dir="ltr"
				class={`${styles.brandingWordmark || ''} ${styles.brandingC15T || ''}`}
			>
				<span class={styles.brandingC15TMark || ''}>
					<C15TIconOnly aria-hidden={true} />
				</span>
				<span class={styles.brandingWordmarkLabel || ''}>c15t</span>
			</span>
		{/if}
	</a>
{/if}

// packages/react/src/v3/components/shared/ui/branding.tsx
import styles from '@c15t/ui/styles/components/consent-dialog.module.js';
import { resolveStyles, sanitizeDOMStyleProps } from '@c15t/ui/utils';
import type { Branding } from 'c15t';
import type { SVGProps } from 'react';
import { useMemo } from 'react';
import { useTranslations } from '~/v3/component-hooks/use-translations';
import { useBranding } from '~/v3/hooks';
import { useTheme } from '~/v3/hooks/use-theme';
import type {
	AllThemeKeys,
	ClassNameStyle,
	CSSPropertiesWithVars,
} from '~/v3/types/theme';
import { cnExt as cn } from '~/v3/utils/cn';
import { mergeStyles } from '~/v3/utils/merge-styles';
import { C15TIconOnly, InthIconOnly, InthLogo } from './logo';

export type ResolvedBranding = 'c15t' | 'inth' | 'none';
export type BrandingVariant = 'footer' | 'dialog-tag' | 'banner-tag';
export type BrandingThemeKey =
	| 'consentBannerTag'
	| 'consentDialogTag'
	| 'consentWidgetTag'
	| 'iabConsentBannerTag'
	| 'iabConsentDialogTag';

type BrandingProps = {
	hideBranding: boolean;
	variant?: BrandingVariant;
	themeKey?: BrandingThemeKey;
	className?: string;
	style?: CSSPropertiesWithVars;
	'data-testid'?: string;
};

type BrandingFullLogoProps = {
	branding: Branding | string;
	className?: string;
};

type BrandingCompactLogoProps = SVGProps<SVGSVGElement> & {
	branding: Branding | string;
};

export function resolveBranding(branding: Branding | string): ResolvedBranding {
	if (branding === 'none') {
		return 'none';
	}

	if (branding === 'inth' || branding === 'consent') {
		return 'inth';
	}

	return 'c15t';
}

export function getBrandingHref(
	branding: Branding | string,
	refParam = ''
): string {
	return resolveBranding(branding) === 'inth'
		? `https://inth.com${refParam}`
		: `https://c15t.com${refParam}`;
}

export function BrandingFullLogo({
	branding,
	className,
}: BrandingFullLogoProps) {
	if (resolveBranding(branding) === 'inth') {
		return (
			<span
				dir="ltr"
				className={cn(styles.brandingWordmark, className)}
			>
				<InthLogo aria-hidden="true" />
			</span>
		);
	}

	return (
		<span
			dir="ltr"
			className={cn(styles.brandingWordmark, className)}
		>
			<span className={styles.brandingC15TMark}>
				<C15TIconOnly aria-hidden="true" />
			</span>
			<span className={styles.brandingWordmarkLabel}>c15t</span>
		</span>
	);
}

export function BrandingCompactLogo({
	branding,
	...props
}: BrandingCompactLogoProps) {
	const Logo =
		resolveBranding(branding) === 'inth' ? InthIconOnly : C15TIconOnly;
	return <Logo {...props} />;
}

export function BrandingLink({
	hideBranding,
	variant = 'footer',
	themeKey,
	className,
	style,
	'data-testid': testId,
}: BrandingProps) {
	const branding = useBranding() ?? 'c15t';
	const { noStyle: contextNoStyle, theme } = useTheme();
	const { common } = useTranslations();
	const resolvedBranding = resolveBranding(branding);
	const refParam =
		typeof window !== 'undefined' ? `?ref=${window.location.hostname}` : '';
	const brandingStyle = useMemo(() => {
		const componentStyle: ClassNameStyle = {
			baseClassName: cn(
				styles.branding,
				variant !== 'footer' && styles.brandingTag,
				variant === 'dialog-tag' && styles.brandingTagDialog,
				variant === 'banner-tag' && styles.brandingTagBanner
			),
			className,
			style,
		};
		if (themeKey && theme?.slots && themeKey in theme.slots) {
			return resolveStyles(
				themeKey as AllThemeKeys,
				theme,
				componentStyle,
				contextNoStyle
			);
		}

		return mergeStyles({}, componentStyle);
	}, [className, contextNoStyle, style, theme, themeKey, variant]);
	const domStyleProps = sanitizeDOMStyleProps(brandingStyle);

	if (resolvedBranding === 'none' || hideBranding) {
		return null;
	}

	return (
		<a
			{...domStyleProps}
			href={getBrandingHref(branding, refParam)}
			data-branding={resolvedBranding}
			data-variant={variant}
			data-testid={testId}
		>
			<span className={styles.brandingCopy}>
				<span className={styles.brandingText}>{common.securedBy}</span>
			</span>
			<BrandingFullLogo
				branding={branding}
				className={
					resolvedBranding === 'inth'
						? styles.brandingInth
						: styles.brandingC15T
				}
			/>
		</a>
	);
}
