// examples/react/src/experiment-readout.tsx
import type { ExperimentReportEvent, ExperimentReporter } from 'c15t';
import { useExperiment } from 'c15t/react';
import { useCallback, useState } from 'react';

/** Collects the events the experiment reports so the page can list them. */
export const useExperimentLog = function useExperimentLog() {
	const [events, setEvents] = useState<ExperimentReportEvent[]>([]);
	const report = useCallback<ExperimentReporter>((event) => {
		setEvents((previous) => [...previous, event]);
	}, []);
	return { events, report };
};

/** The assigned arm and the events reported so far. */
export const ExperimentReadout = ({
	events,
}: {
	events: readonly ExperimentReportEvent[];
}) => {
	const assignment = useExperiment();
	return (
		<section
			className="card"
			data-testid="experiment"
		>
			<h2>Banner experiment</h2>
			<p>
				Arm:{' '}
				<code data-testid="experiment-arm">
					{assignment
						? `${assignment.id} · ${assignment.variant} · ${assignment.assignedBy}`
						: 'assigning…'}
				</code>
			</p>
			<ul className="statuses">
				{events.map((event, index) => (
					<li
						// oxlint-disable-next-line react/no-array-index-key -- append-only log
						key={index}
					>
						<code>{event.name}</code> · {event.variant} · {event.surface}
						{event.name === 'c15t_choice_recorded'
							? ` · ${event.consentAction}`
							: ''}
						{event.name !== 'c15t_surface_shown' &&
						event.timeToDecisionMs !== undefined
							? ` · ${event.timeToDecisionMs} ms`
							: ''}
					</li>
				))}
			</ul>
			<p>
				The same events are pushed to <code>window.dataLayer</code>.
			</p>
		</section>
	);
};

// examples/sveltekit-demo/src/lib/experiment-readout.svelte
<script lang="ts">
	import { getConsentManager } from '@c15t/svelte/headless';

	import { experimentEvents } from './experiment.svelte';

	const consent = getConsentManager();
</script>

<section data-testid="experiment">
	<h2>Banner experiment</h2>
	<p>
		Arm: <code data-testid="experiment-arm"
			>{consent.experiment
				? `${consent.experiment.id} · ${consent.experiment.variant} · ${consent.experiment.assignedBy}`
				: 'assigning…'}</code
		>
	</p>
	<ul>
		{#each experimentEvents as event, index (index)}
			<li>
				<code>{event.name}</code> · {event.variant} · {event.surface}
				{#if event.name === 'c15t_choice_recorded'}
					· {event.consentAction}
				{/if}
				{#if event.name !== 'c15t_surface_shown' && event.timeToDecisionMs !== undefined}
					· {event.timeToDecisionMs} ms
				{/if}
			</li>
		{/each}
	</ul>
	<p>The same events are pushed to <code>window.dataLayer</code>.</p>
</section>
