// benchmarks/tanstack-start-browser-bench/src/routes/baseline.tsx
/**
 * Zero-consent baseline page (Start host): identical app shell, no c15t.
 * Measures the page floor so `consentTaxMs = bannerVisible − pageFloor`
 * can be derived. Probe stub mirrors the real probe's settle semantics.
 */
import { createFileRoute } from '@tanstack/react-router';
import { useEffect } from 'react';

import { getState } from '../bench/state';

const BaselineProbe = () => {
	useEffect(() => {
		const state = getState('baseline');
		if (!state) {
			return;
		}
		requestAnimationFrame(() => {
			requestAnimationFrame(() => {
				const now = performance.now();
				if (state.bannerReadyMs === undefined) {
					state.bannerReadyMs = now;
					state.bannerVisibleMs = now;
				}
				state.activeUI = 'none';
			});
		});
	}, []);
	return null;
};

const BaselinePage = () => (
	<main style={{ fontFamily: 'system-ui', padding: '2rem' }}>
		<BaselineProbe />
		<h1>Zero-consent baseline</h1>
		<p>Identical app shell, no consent library.</p>
		<button
			id="baseline-noop"
			type="button"
		>
			No-op interaction target
		</button>
	</main>
);

export const Route = createFileRoute('/baseline')({
	component: BaselinePage,
});

// benchmarks/sveltekit-browser-bench/src/routes/baseline/+page.svelte
<script lang="ts">
	/**
	 * Zero-consent baseline: the same SvelteKit shell, server-rendered, with
	 * no c15t anywhere in the route's module graph. Gives the floor that
	 * `consentTax = bannerVisible − floor` subtracts.
	 */
	import { publishBaselineProbe } from '$lib/baseline-probe';
	import { onMount } from 'svelte';

	onMount(() => publishBaselineProbe('baseline'));
</script>

<main style="padding: 2rem; font-family: system-ui, sans-serif">
	<h1>Zero-consent baseline</h1>
	<p>Identical app shell, no consent library. Measures the page floor.</p>
	<button
		id="baseline-noop"
		type="button"
	>
		No-op interaction target
	</button>
</main>
