// examples/showcase-nuxt-theme/app/components/site-footer.vue
<template>
	<footer class="site-footer">
		<div class="shell">
			<p>Northwind Coffee Roasters. Roasted Tuesdays and Fridays.</p>
			<ul>
				<li><NuxtLink to="/privacy">Privacy policy</NuxtLink></li>
				<li>
					<ConsentDialogLink class="footer-link">
						Privacy settings
					</ConsentDialogLink>
				</li>
			</ul>
		</div>
	</footer>
</template>

// examples/showcase-custom-banner/components/site-footer.tsx
import { PrivacySettingsLink } from './privacy-settings-link';

import styles from './site-chrome.module.css';

export const SiteFooter = () => (
	<footer className={styles.footer}>
		<div className={styles.footerInner}>
			<p className={styles.footerNote}>
				Northwind Coffee Roasters. Roasted Tuesdays and Fridays, shipped within
				two days.
			</p>
			<ul className={styles.footerLinks}>
				<li>
					<a href="/">Shipping</a>
				</li>
				<li>
					<a href="/">Wholesale</a>
				</li>
				<li>
					<a href="/">Contact</a>
				</li>
				<li>
					<PrivacySettingsLink />
				</li>
			</ul>
		</div>
	</footer>
);
