// examples/sveltekit-demo/src/lib/components/CTA.svelte
<section class="py-20 px-4 sm:px-6 lg:px-8">
	<div class="container mx-auto max-w-4xl">
		<div
			class="bg-primary text-primary-foreground rounded-2xl p-12 text-center space-y-6"
		>
			<h2 class="text-3xl sm:text-4xl lg:text-5xl font-bold text-balance">
				Ready to revolutionize your deliveries?
			</h2>
			<p class="text-lg opacity-90 max-w-2xl mx-auto text-pretty">
				Join thousands of London businesses already using PigeonPost for fast,
				reliable, and eco-friendly delivery.
			</p>
			<div
				class="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4"
			>
				<a
					href="#pricing"
					class="inline-flex items-center justify-center rounded-md text-base font-medium h-11 px-8 bg-secondary text-secondary-foreground hover:bg-secondary/80"
				>
					Start Free Trial
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="16"
						height="16"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="ml-2"><path d="M5 12h14" /><path d="m12 5 7 7-7 7" /></svg
					>
				</a>
				<a
					href="#video-demo"
					class="inline-flex items-center justify-center rounded-md text-base font-medium h-11 px-8 border border-primary-foreground bg-transparent text-primary-foreground hover:bg-primary-foreground hover:text-primary"
				>
					Schedule Demo
				</a>
			</div>
		</div>
	</div>
</section>

// examples/demo/components/cta.tsx
import { ArrowRight } from 'lucide-react';
import { Button } from './ui/button';

export function CTA() {
	return (
		<section className="py-20 px-4 sm:px-6 lg:px-8">
			<div className="container mx-auto max-w-4xl">
				<div className="bg-primary text-primary-foreground rounded-2xl p-12 text-center space-y-6">
					<h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-balance">
						Ready to revolutionize your deliveries?
					</h2>
					<p className="text-lg opacity-90 max-w-2xl mx-auto text-pretty">
						Join thousands of London businesses already using PigeonPost for
						fast, reliable, and eco-friendly delivery.
					</p>
					<div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
						<Button size="lg" variant="secondary" className="text-base" asChild>
							<a href="#pricing">
								Start Free Trial
								<ArrowRight className="ml-2 h-4 w-4" />
							</a>
						</Button>
						<Button
							size="lg"
							variant="outline"
							className="text-base bg-transparent border-primary-foreground text-primary-foreground hover:bg-primary-foreground hover:text-primary"
							asChild
						>
							<a href="#video-demo">Schedule Demo</a>
						</Button>
					</div>
				</div>
			</div>
		</section>
	);
}
