// packages/svelte/src/lib/primitives/tabs/tabs-trigger.svelte
<script lang="ts">
	import {
		getDataDisabled,
		getNextTabValue,
		getTabState,
	} from '@c15t/ui/primitives';
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';

	import { getTabsRootContext } from './context';

	const root = getTabsRootContext();

	let {
		children,
		class: className,
		onclick,
		onkeydown,
		type = 'button',
		value,
		...restProps
	}: HTMLAttributes<HTMLButtonElement> & {
		children?: Snippet;
		class?: string;
		type?: 'button' | 'submit' | 'reset';
		value: string;
	} = $props();

	const baseId = $derived(root.baseId);
	const disabled = $derived(root.disabled);
	const selectedValue = $derived(root.value);
	const isSelected = $derived(selectedValue === value);
	const dataState = $derived(getTabState(isSelected));
	const dataDisabled = $derived(getDataDisabled(disabled));
	const triggerId = $derived(`${baseId}-trigger-${value}`);
	const contentId = $derived(`${baseId}-content-${value}`);

	const moveFocus = function moveFocus(nextValue: string) {
		root.setValue(nextValue);

		if (typeof document === 'undefined') {
			return;
		}

		const nextButton = document.getElementById(
			`${baseId}-trigger-${nextValue}`
		);

		if (nextButton instanceof HTMLButtonElement) {
			nextButton.focus();
		}
	};

	const handleKeyDown = function handleKeyDown(
		event: KeyboardEvent & { currentTarget: EventTarget & HTMLButtonElement }
	) {
		if (typeof document === 'undefined') {
			onkeydown?.(event);
			return;
		}

		const triggerValues = Array.from(
			document.querySelectorAll<HTMLButtonElement>(
				`[data-slot="tabs-trigger"][id^="${baseId}-trigger-"]`
			)
		).map((button) => button.id.replace(`${baseId}-trigger-`, ''));

		const nextValue = getNextTabValue({
			currentValue: value,
			key: event.key,
			loop: root.loop,
			orientation: root.orientation,
			triggerValues,
		});

		if (nextValue !== value || event.key === 'Home' || event.key === 'End') {
			event.preventDefault();
			moveFocus(nextValue);
		}
		onkeydown?.(event);
	};

	const handleClick = function handleClick(
		event: MouseEvent & { currentTarget: EventTarget & HTMLButtonElement }
	) {
		root.setValue(value);
		onclick?.(event);
	};
</script>

<button
	{type}
	id={triggerId}
	role="tab"
	tabindex={isSelected ? 0 : -1}
	aria-controls={contentId}
	aria-selected={isSelected}
	class={className}
	data-slot="tabs-trigger"
	data-state={dataState}
	data-disabled={dataDisabled}
	{disabled}
	{...restProps}
	onclick={handleClick}
	onkeydown={handleKeyDown}
>
	{@render children?.()}
</button>

// packages/vue/src/runtime/primitives/tabs/tabs-trigger.vue
<script setup lang="ts">
import {
	getDataDisabled,
	getNextTabValue,
	getTabState,
} from '@c15t/ui/primitives';
import { computed } from 'vue';

import { useTabsRootContext } from './context';

const props = withDefaults(defineProps<{ class?: string; value: string }>(), {
	class: undefined,
});

const root = useTabsRootContext();

const isSelected = computed(() => root.value.value === props.value);
const dataState = computed(() => getTabState(isSelected.value));
const dataDisabled = computed(() => getDataDisabled(root.disabled.value));
const triggerId = computed(() => `${root.baseId}-trigger-${props.value}`);
const contentId = computed(() => `${root.baseId}-content-${props.value}`);

const moveFocus = function moveFocus(nextValue: string) {
	root.setValue(nextValue);
	if (typeof document === 'undefined') {
		return;
	}
	document.getElementById(`${root.baseId}-trigger-${nextValue}`)?.focus();
};

const onKeydown = function onKeydown(event: KeyboardEvent) {
	if (typeof document === 'undefined') {
		return;
	}
	const triggerValues = Array.from(
		document.querySelectorAll<HTMLButtonElement>(
			`[data-slot="tabs-trigger"][id^="${root.baseId}-trigger-"]`
		)
	).map((button) => button.id.replace(`${root.baseId}-trigger-`, ''));

	const nextValue = getNextTabValue({
		currentValue: props.value,
		key: event.key,
		loop: root.loop.value,
		orientation: root.orientation.value,
		triggerValues,
	});

	if (
		nextValue !== props.value ||
		event.key === 'Home' ||
		event.key === 'End'
	) {
		event.preventDefault();
		moveFocus(nextValue);
	}
};
</script>

<template>
	<button
		:id="triggerId"
		type="button"
		role="tab"
		:tabindex="isSelected ? 0 : -1"
		:aria-controls="contentId"
		:aria-selected="isSelected"
		:class="props.class"
		data-slot="tabs-trigger"
		:data-state="dataState"
		:data-disabled="dataDisabled"
		:disabled="root.disabled.value"
		@click="root.setValue(props.value)"
		@keydown="onKeydown"
	>
		<slot />
	</button>
</template>
