// examples/demo/components/video-demo.tsx
'use client';

import { Frame } from '@c15t/react';

export function VideoDemo() {
	return (
		<section id="video-demo" className="py-24 bg-background">
			<div className="container mx-auto px-4">
				<div className="max-w-4xl mx-auto">
					<div className="text-center mb-12">
						<h2 className="text-4xl font-bold mb-4 text-balance">
							Policy-Gated Iframe Demo
						</h2>
						<p className="text-xl text-muted-foreground text-balance">
							The first iframe is in-policy for restricted JP
							(necessary+measurement). The second requires experience and stays
							blocked when that purpose is out of policy.
						</p>
					</div>

					<div className="grid gap-10">
						<div>
							<h3 className="font-semibold mb-3">Measurement Category</h3>
							<Frame
								category="measurement"
								className="relative w-full aspect-video"
							>
								<iframe
									src="https://www.youtube.com/embed/gwqYfNWVPpk?si=eEtKAUke_JUXTMfl&amp;start=36"
									title="Measurement Policy-Gated Video"
									allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
									allowFullScreen
									className="inset-0 w-full h-full"
								/>
							</Frame>
						</div>

						<div>
							<h3 className="font-semibold mb-3">Experience Category</h3>
							<Frame
								category="experience"
								className="relative w-full aspect-video"
							>
								<iframe
									src="https://www.youtube.com/embed/gwqYfNWVPpk?si=eEtKAUke_JUXTMfl&amp;start=36"
									title="Experience Policy-Gated Video"
									allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
									allowFullScreen
									className="inset-0 w-full h-full"
								/>
							</Frame>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}

// examples/sveltekit-demo/src/lib/components/VideoDemo.svelte
<script lang="ts">
	import { Frame } from '@c15t/svelte';
</script>

<section
	id="video-demo"
	class="bg-background py-24"
>
	<div class="container mx-auto px-4">
		<div class="mx-auto max-w-4xl">
			<div class="mb-12 text-center">
				<h2 class="mb-4 text-4xl font-bold text-balance">
					See PigeonPost in Action
				</h2>
				<p class="text-muted-foreground text-xl text-balance">
					Watch how our revolutionary pigeon-powered delivery system works
				</p>
			</div>

			<Frame
				category="experience"
				class="relative aspect-video w-full"
			>
				<iframe
					src="https://www.youtube.com/embed/gwqYfNWVPpk?si=eEtKAUke_JUXTMfl&start=36"
					title="PigeonPost Demo Video"
					allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
					allowfullscreen
					class="inset-0 h-full w-full"
				></iframe>
			</Frame>
		</div>
	</div>
</section>
