// packages/vue/src/runtime/primitives/preference-item/preference-item-title.vue
<script setup lang="ts">
import { PREFERENCE_ITEM_SLOTS } from '@c15t/ui/primitives';
import { preferenceItemVariants } from '@c15t/ui/styles/primitives';
import { computed } from 'vue';

import { usePreferenceItemContext } from './context';

const props = withDefaults(defineProps<{ class?: string }>(), {
	class: undefined,
});

const context = usePreferenceItemContext();
const variants = preferenceItemVariants();

const resolvedClass = computed(() =>
	context.noStyle.value ? props.class : variants.title({ class: props.class })
);
</script>

<template>
	<h3
		:class="resolvedClass"
		:data-slot="PREFERENCE_ITEM_SLOTS.title"
	>
		<slot />
	</h3>
</template>

// packages/svelte/src/lib/primitives/preference-item/preference-item-title.svelte
<script lang="ts">
import { PREFERENCE_ITEM_SLOTS } from '@c15t/ui/primitives';
import { preferenceItemVariants } from '@c15t/ui/styles/primitives';
import type { Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';
import { getPreferenceItemContext } from './context';

const context = getPreferenceItemContext();
const variants = preferenceItemVariants();

const noStyle = $derived(context.noStyle);
const className = $derived.by(() =>
	noStyle ? localClassName : variants.title({ class: localClassName })
);

let {
	children,
	class: localClassName,
	...restProps
}: HTMLAttributes<HTMLHeadingElement> & {
	children?: Snippet;
	class?: string;
} = $props();
</script>

<h3
	class={className}
	data-slot={PREFERENCE_ITEM_SLOTS.title}
	{...restProps}
>
	{@render children?.()}
</h3>
