// packages/vue/src/runtime/primitives/preference-item/preference-item-leading.vue
<script setup lang="ts">
import { PREFERENCE_ITEM_SLOTS } from '@c15t/ui/primitives';
import { preferenceItemVariants } from '@c15t/ui/styles/primitives';
import { computed } from 'vue';

import { usePreferenceItemContext } from './context';

const props = withDefaults(defineProps<{ class?: string }>(), {
	class: undefined,
});

const context = usePreferenceItemContext();
const variants = preferenceItemVariants();

const resolvedClass = computed(() =>
	context.noStyle.value ? props.class : variants.leading({ class: props.class })
);
</script>

<template>
	<div
		:class="resolvedClass"
		:data-slot="PREFERENCE_ITEM_SLOTS.leading"
	>
		<slot />
	</div>
</template>

// packages/svelte/src/lib/primitives/preference-item/preference-item-leading.svelte
<script lang="ts">
	import { PREFERENCE_ITEM_SLOTS } from '@c15t/ui/primitives';
	import { preferenceItemVariants } from '@c15t/ui/styles/primitives';
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';
	import { getPreferenceItemContext } from './context';

	const context = getPreferenceItemContext();
	const variants = preferenceItemVariants();

	const noStyle = $derived(context.noStyle);
	const className = $derived.by(() =>
		noStyle ? localClassName : variants.leading({ class: localClassName })
	);

	let {
		children,
		class: localClassName,
		...restProps
	}: HTMLAttributes<HTMLDivElement> & {
		children?: Snippet;
		class?: string;
	} = $props();
</script>

<div
	class={className}
	data-slot={PREFERENCE_ITEM_SLOTS.leading}
	{...restProps}
>
	{@render children?.()}
</div>
