// packages/vue/src/runtime/primitives/preference-item/preference-item-trigger.vue
<script setup lang="ts">
import {
	getDataDisabled,
	getPreferenceItemState,
	PREFERENCE_ITEM_SLOTS,
} from '@c15t/ui/primitives';
import { preferenceItemVariants } from '@c15t/ui/styles/primitives';
import { computed } from 'vue';

import { usePreferenceItemContext } from './context';

const props = withDefaults(defineProps<{ class?: string }>(), {
	class: undefined,
});

const context = usePreferenceItemContext();
const variants = preferenceItemVariants();

const triggerClass = computed(() =>
	context.noStyle.value ? props.class : variants.trigger({ class: props.class })
);
const dataState = computed(() => getPreferenceItemState(context.open.value));
const dataDisabled = computed(() => getDataDisabled(context.disabled.value));
</script>

<template>
	<button
		:id="context.triggerId"
		type="button"
		:aria-controls="context.contentId"
		:aria-disabled="context.disabled.value || undefined"
		:aria-expanded="context.open.value"
		:class="triggerClass"
		:data-slot="PREFERENCE_ITEM_SLOTS.trigger"
		:data-state="dataState"
		:data-disabled="dataDisabled"
		:disabled="context.disabled.value"
		@click="context.toggle()"
	>
		<slot />
	</button>
</template>

// packages/svelte/src/lib/primitives/preference-item/preference-item-trigger.svelte
<script lang="ts">
	import {
		getDataDisabled,
		getPreferenceItemState,
		PREFERENCE_ITEM_SLOTS,
	} from '@c15t/ui/primitives';
	import { preferenceItemVariants } from '@c15t/ui/styles/primitives';
	import type { Snippet } from 'svelte';
	import type { HTMLAttributes } from 'svelte/elements';

	import { getPreferenceItemContext } from './context';

	const context = getPreferenceItemContext();
	const variants = preferenceItemVariants();

	let {
		children,
		class: localClassName,
		onclick,
		type = 'button',
		...restProps
	}: HTMLAttributes<HTMLButtonElement> & {
		children?: Snippet;
		class?: string;
		type?: 'button' | 'submit' | 'reset';
	} = $props();

	const handleClick = function handleClick(
		event: MouseEvent & { currentTarget: EventTarget & HTMLButtonElement }
	) {
		context.toggle();
		onclick?.(event);
	};

	const open = $derived(context.open);
	const disabled = $derived(context.disabled);
	const noStyle = $derived(context.noStyle);
	const triggerId = $derived(context.triggerId);
	const contentId = $derived(context.contentId);
	const className = $derived.by(() =>
		noStyle ? localClassName : variants.trigger({ class: localClassName })
	);
	const dataState = $derived(getPreferenceItemState(open));
	const dataDisabled = $derived(getDataDisabled(disabled));
</script>

<button
	{type}
	id={triggerId}
	aria-controls={contentId}
	aria-disabled={disabled || undefined}
	aria-expanded={open}
	class={className}
	data-slot={PREFERENCE_ITEM_SLOTS.trigger}
	data-state={dataState}
	data-disabled={dataDisabled}
	{disabled}
	{...restProps}
	onclick={handleClick}
>
	{@render children?.()}
</button>
