// packages/svelte/src/lib/components/iab-consent-dialog.svelte
<script lang="ts">
	import { defaultTranslationConfig } from '@c15t/core';
	import type { Model } from '@c15t/core';
	import { isDialogDismissKey } from '@c15t/ui/primitives/dialog';
	import actionStyles from '@c15t/ui/styles/components/consent-actions';
	import styles from '@c15t/ui/styles/components/iab-consent-dialog';
	import { buttonVariants } from '@c15t/ui/styles/primitives';
	import { getTextDirection, resolveTranslations } from '@c15t/ui/utils';

	import { focusTrap } from '../actions/focus-trap';
	import { portal } from '../actions/portal';
	import { scrollLock } from '../actions/scroll-lock';
	import { getConsentContext, getThemeContext } from '../context.svelte';
	import { getIABTranslations } from '../iab-translations';
	import { resolveIABDialogDisplayModel } from '../iab-types';
	import type { VendorId } from '../iab-types';
	import { Tabs } from '../primitives';
	import Branding from './branding.svelte';
	import IABPurposeItem from './iab-purpose-item.svelte';
	import IABStackItem from './iab-stack-item.svelte';
	import IABVendorList from './iab-vendor-list.svelte';
	import ChevronRightIcon from './icons/chevron-right-icon.svelte';
	import CloseIcon from './icons/close-icon.svelte';
	import InfoIcon from './icons/info-icon.svelte';
	import LockIcon from './icons/lock-icon.svelte';
	import Overlay from './overlay.svelte';

	let {
		open: openProp,
		noStyle: localNoStyle,
		hideBranding,
		initialTab,
		models = ['iab'] as Model[],
		class: className,
	}: {
		open?: boolean;
		noStyle?: boolean;
		hideBranding?: boolean;
		/**
		 * Which tab the preference centre opens on. Lets a "N partners"
		 * link land on the vendor list instead of purposes.
		 */
		initialTab?: 'purposes' | 'vendors';
		models?: Model[];
		class?: string;
	} = $props();

	const consent = getConsentContext();
	const theme = getThemeContext();

	const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);

	// IAB state
	const iabState = $derived(consent.state.iab);

	// Translations
	const iabT = $derived(getIABTranslations(consent.state.translationConfig));
	const coreTranslations = $derived(
		resolveTranslations(
			consent.state.translationConfig,
			defaultTranslationConfig
		)
	);
	const textDirection = $derived(
		getTextDirection(consent.state.translationConfig?.defaultLanguage)
	);

	// Open state
	const isOpen = $derived(
		models.includes(consent.state.model) &&
			(openProp ?? consent.state.activeUI === 'dialog') &&
			iabState?.config.enabled === true
	);

	// Tab state
	let activeTab = $state<string | null>('purposes');
	let selectedVendorId = $state<VendorId | null>(null);
	let specialPurposesExpanded = $state(false);

	// Sync tab from iabState when dialog opens
	$effect(() => {
		if (isOpen && iabState?.preferenceCenterTab) {
			activeTab = iabState.preferenceCenterTab;
		}
	});

	// A caller-supplied tab outranks the provider's remembered one, which
	// is what makes a "N partners" deep link land on the vendor list. It
	// goes through the provider rather than straight into `activeTab` so
	// the effect above stays the single writer.
	$effect(() => {
		if (initialTab) {
			iabState?.setPreferenceCenterTab(initialTab);
		}
	});

	const handleClose = function handleClose() {
		consent.state.setActiveUI('none');
	};

	const handleDialogKeydown = function handleDialogKeydown(
		event: KeyboardEvent
	) {
		if (isDialogDismissKey(event.key)) {
			event.preventDefault();
			handleClose();
		}
	};

	$effect(() => {
		if (activeTab === 'purposes' || activeTab === 'vendors') {
			iabState?.setPreferenceCenterTab(activeTab);
		}
	});

	// The rows this surface renders, from the shared display model.
	const display = $derived(
		resolveIABDialogDisplayModel(
			iabState
				? {
						customVendors: iabState.nonIABVendors ?? [],
						gvl: iabState.gvl,
						isLoadingGVL: iabState.isLoadingGVL,
					}
				: null
		)
	);

	const isLoading = $derived(iabState?.isLoadingGVL || !iabState?.gvl);

	const handlePurposeToggle = function handlePurposeToggle(
		purposeId: number,
		value: boolean
	) {
		iabState?.setPurposeConsent(purposeId, value);
	};

	const handleSpecialFeatureToggle = function handleSpecialFeatureToggle(
		featureId: number,
		value: boolean
	) {
		iabState?.setSpecialFeatureOptIn(featureId, value);
	};

	const handleVendorToggle = function handleVendorToggle(
		vendorId: VendorId,
		value: boolean
	) {
		iabState?.setVendorConsent(vendorId, value);
	};

	const handleVendorLegitimateInterestToggle =
		function handleVendorLegitimateInterestToggle(
			vendorId: VendorId,
			value: boolean
		) {
			iabState?.setVendorLegitimateInterest(vendorId, value);
		};

	const handlePurposeLegitimateInterestToggle =
		function handlePurposeLegitimateInterestToggle(
			purposeId: number,
			value: boolean
		) {
			iabState?.setPurposeLegitimateInterest(purposeId, value);
		};

	const handleAcceptAll = function handleAcceptAll() {
		iabState?.acceptAll();
		iabState?.save();
		consent.state.setActiveUI('none');
	};

	const handleRejectAll = function handleRejectAll() {
		iabState?.rejectAll();
		iabState?.save();
		consent.state.setActiveUI('none');
	};

	const handleSave = function handleSave() {
		iabState?.save();
		consent.state.setActiveUI('none');
	};

	const handleVendorClick = function handleVendorClick(vendorId: VendorId) {
		selectedVendorId = vendorId;
		activeTab = 'vendors';
		iabState?.setPreferenceCenterTab('vendors');
	};

	const secondaryButtonClass = buttonVariants({
		mode: 'stroke',
		size: 'small',
		variant: 'neutral',
	}).root();
	const primaryButtonClass = buttonVariants({
		mode: 'filled',
		size: 'small',
		variant: 'primary',
	}).root();
</script>

<!--
	Plain elements, not the Ark dialog: React's IAB preference centre is
	hand-rolled, and a primitive library's `data-slot`/`data-state`
	bookkeeping is exactly the kind of difference the cross-framework gate
	is there to catch. The behaviour the primitive provided — portal, focus
	trap, scroll lock, Escape to close — comes from the same actions the
	IAB banner uses.
-->
{#if isOpen}
	<div use:portal>
		<Overlay
			variant="iab-dialog"
			visible={isOpen}
		/>
		<div
			class={noStyle
				? ''
				: `${styles.root || ''} ${styles.dialogVisible || ''}`}
			data-testid="iab-consent-dialog-root"
			dir={textDirection}
		>
			<!-- A `div`, not a `dialog`: the user agent's dialog padding is
			     1em, which the card sets for itself. -->
			<div
				class={noStyle
					? className || ''
					: `${styles.card || ''} ${className || ''} ${styles.contentVisible || ''}`}
				data-testid="iab-consent-dialog-card"
				role="dialog"
				aria-modal="true"
				aria-label={iabT.preferenceCenter.title}
				tabindex="-1"
				use:focusTrap={true}
				use:scrollLock={true}
				onkeydown={handleDialogKeydown}
			>
				<!-- Header -->
				<div class={noStyle ? '' : styles.header || ''}>
					<div class={noStyle ? '' : styles.headerContent || ''}>
						<h2 class={noStyle ? '' : styles.title || ''}>
							{iabT.preferenceCenter.title}
						</h2>
						<p class={noStyle ? '' : styles.description || ''}>
							{iabT.preferenceCenter.description}
						</p>
					</div>
					<button
						type="button"
						class={noStyle ? '' : styles.closeButton || ''}
						aria-label={coreTranslations.common.close}
						data-testid="iab-consent-dialog-close"
						onclick={handleClose}
					>
						<CloseIcon
							style="height:1rem;width:1rem"
							aria-hidden={true}
						/>
					</button>
				</div>

				<Tabs.Root
					bind:value={activeTab}
					class={noStyle ? '' : styles.body || ''}
				>
					<div class={noStyle ? '' : styles.tabsContainer || ''}>
						<Tabs.List class={noStyle ? '' : styles.tabsList || ''}>
							<Tabs.Trigger
								value="purposes"
								class={noStyle ? '' : styles.tabButton || ''}
							>
								{iabT.preferenceCenter.tabs.purposes}
								{#if !isLoading}
									({display.purposeTabCount})
								{/if}
							</Tabs.Trigger>
							<Tabs.Trigger
								value="vendors"
								class={noStyle ? '' : styles.tabButton || ''}
							>
								{iabT.preferenceCenter.tabs.vendors}
								{#if !isLoading}
									({display.vendorTabCount})
								{/if}
							</Tabs.Trigger>
							<div
								aria-hidden="true"
								class={noStyle ? '' : styles.tabIndicator || ''}
								data-active-tab={activeTab}
							></div>
						</Tabs.List>
					</div>

					<div class={noStyle ? '' : styles.content || ''}>
						<Tabs.Content
							value="purposes"
							forceMount
							class={noStyle ? '' : styles.tabPanel || ''}
						>
							{#if isLoading}
								<div class={noStyle ? '' : styles.loadingContainer || ''}>
									<div class={noStyle ? '' : styles.loadingSpinner || ''}></div>
									<p class={noStyle ? '' : styles.loadingText || ''}>
										{iabT.common.loading}
									</p>
								</div>
							{:else if display.isReady && iabState}
								<!-- Purposes, stacks and special features, from the
								     shared display model so every adapter lists the
								     same rows in the same order. -->
								{#each display.consentRows as row (row.testId)}
									{#if row.kind === 'stack'}
										<IABStackItem
											stack={row}
											consents={iabState.purposeConsents}
											onToggle={handlePurposeToggle}
											vendorConsents={iabState.vendorConsents}
											onVendorToggle={handleVendorToggle}
											onVendorClick={handleVendorClick}
											vendorLegitimateInterests={iabState.vendorLegitimateInterests}
											onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
											purposeLegitimateInterests={iabState.purposeLegitimateInterests}
											onPurposeLegitimateInterestToggle={handlePurposeLegitimateInterestToggle}
											{noStyle}
											{iabT}
										/>
									{:else if row.toggle === 'special-feature'}
										<IABPurposeItem
											purpose={row}
											testId={row.testId}
											isEnabled={iabState.specialFeatureOptIns[row.id] ?? false}
											onToggle={(value) =>
												handleSpecialFeatureToggle(row.id, value)}
											vendorConsents={iabState.vendorConsents}
											onVendorToggle={handleVendorToggle}
											onVendorClick={handleVendorClick}
											vendorLegitimateInterests={iabState.vendorLegitimateInterests}
											onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
											{noStyle}
											{iabT}
										/>
									{:else}
										<IABPurposeItem
											purpose={row}
											testId={row.testId}
											isEnabled={iabState.purposeConsents[row.id] ?? false}
											onToggle={(value) => handlePurposeToggle(row.id, value)}
											vendorConsents={iabState.vendorConsents}
											onVendorToggle={handleVendorToggle}
											onVendorClick={handleVendorClick}
											vendorLegitimateInterests={iabState.vendorLegitimateInterests}
											onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
											purposeLegitimateInterests={iabState.purposeLegitimateInterests}
											onPurposeLegitimateInterestToggle={handlePurposeLegitimateInterestToggle}
											{noStyle}
											{iabT}
										/>
									{/if}
								{/each}

								<!-- Essential Functions: Special Purposes + Features (locked) -->
								{#if display.essentialRows.length > 0}
									<div
										class={noStyle ? '' : styles.specialPurposesSection || ''}
									>
										<div
											class={noStyle ? '' : styles.specialPurposesHeader || ''}
										>
											<button
												type="button"
												class={noStyle ? '' : styles.purposeTrigger || ''}
												onclick={() =>
													(specialPurposesExpanded = !specialPurposesExpanded)}
											>
												<ChevronRightIcon
													class={noStyle ? '' : styles.purposeArrow || ''}
													aria-hidden={true}
													expanded={specialPurposesExpanded}
												/>
												<div class={noStyle ? '' : styles.purposeInfo || ''}>
													<h3
														class={noStyle
															? ''
															: styles.specialPurposesTitle || ''}
													>
														{iabT.preferenceCenter.specialPurposes.title}
														<LockIcon
															class={noStyle ? '' : styles.lockIcon || ''}
															aria-hidden={true}
														/>
													</h3>
													<p class={noStyle ? '' : styles.purposeMeta || ''}>
														{display.essentialPartnerCount}
														{display.essentialPartnerCount === 1
															? iabT.preferenceCenter.vendorList.partnerSingular
															: iabT.preferenceCenter.vendorList.partnerPlural}
													</p>
												</div>
											</button>
											<div style="position:relative">
												<InfoIcon
													class={noStyle ? '' : styles.infoIcon || ''}
													aria-label={iabT.preferenceCenter.specialPurposes
														.tooltip}
												/>
											</div>
										</div>

										{#if specialPurposesExpanded}
											<div style="padding:0.75rem">
												{#each display.essentialRows as row (row.testId)}
													<IABPurposeItem
														purpose={row}
														testId={row.testId}
														isEnabled={true}
														onToggle={() => {}}
														vendorConsents={iabState.vendorConsents}
														onVendorToggle={handleVendorToggle}
														onVendorClick={handleVendorClick}
														isLocked={true}
														{noStyle}
														{iabT}
													/>
												{/each}
											</div>
										{/if}
									</div>
								{/if}

								<!-- Consent storage notice -->
								<div class={noStyle ? '' : styles.consentNotice || ''}>
									<p class={noStyle ? '' : styles.consentNoticeText || ''}>
										{iabT.preferenceCenter.footer.consentStorage}
									</p>
								</div>
							{/if}
						</Tabs.Content>

						<Tabs.Content
							value="vendors"
							forceMount
							class={noStyle ? '' : styles.tabPanel || ''}
						>
							{#if iabState}
								<IABVendorList
									vendorData={iabState.gvl}
									purposes={display.data.purposes}
									vendorConsents={iabState.vendorConsents}
									onVendorToggle={handleVendorToggle}
									{selectedVendorId}
									onClearSelection={() => (selectedVendorId = null)}
									customVendors={iabState.nonIABVendors}
									vendorLegitimateInterests={iabState.vendorLegitimateInterests}
									onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
									{noStyle}
									{iabT}
								/>
							{/if}
						</Tabs.Content>
					</div>
				</Tabs.Root>

				<!-- Footer -->
				<div
					class={noStyle ? '' : `${styles.footer} ${actionStyles.actionRoot}`}
					data-direction="row"
					data-split
				>
					<div
						class={noStyle ? '' : actionStyles.actionGroup}
						data-direction="row"
					>
						<button
							type="button"
							class={noStyle ? '' : secondaryButtonClass}
							onclick={handleRejectAll}
							disabled={isLoading}
							data-action="reject"
						>
							{iabT.common.rejectAll}
						</button>
						<button
							type="button"
							class={noStyle ? '' : secondaryButtonClass}
							onclick={handleAcceptAll}
							disabled={isLoading}
							data-action="accept"
						>
							{iabT.common.acceptAll}
						</button>
					</div>
					<div
						class={noStyle ? '' : actionStyles.actionGroup}
						data-direction="row"
					>
						<button
							type="button"
							class={noStyle ? '' : primaryButtonClass}
							onclick={handleSave}
							disabled={isLoading}
							data-action="customize"
						>
							{iabT.common.saveSettings}
						</button>
					</div>
				</div>
				<Branding
					{hideBranding}
					{noStyle}
					variant="dialog-tag"
					themeKey="iabConsentDialogTag"
					data-testid="iab-consent-dialog-branding"
				/>
			</div>
		</div>
	</div>
{/if}

// packages/react/src/v3/components/iab-consent-dialog/iab-consent-dialog.tsx
'use client';

/**
 * @packageDocumentation
 * Provides the IAB TCF 2.3 compliant consent dialog component.
 * Implements an accessible, pre-built consent dialog following IAB requirements.
 */

import actionStyles from '@c15t/ui/styles/v3/consent-actions';
import styles from '@c15t/ui/styles/v3/iab-consent-dialog';
import {
	type FC,
	type RefObject,
	useCallback,
	useEffect,
	useLayoutEffect,
	useRef,
	useState,
} from 'react';
import { createPortal } from 'react-dom';
import { useHeadlessIABConsentUI } from '~/v3/component-hooks/use-headless-iab-consent-ui';
import { useTranslations } from '~/v3/component-hooks/use-translations';
import { Branding } from '~/v3/components/consent-dialog/atoms/card';
import {
	ConsentDialogTrigger,
	type ConsentDialogTriggerProps,
} from '~/v3/components/consent-dialog-trigger';
import * as Button from '~/v3/components/shared/ui/button';
import * as Tabs from '~/v3/components/shared/ui/tabs';
import { ConsentTrackingContext } from '~/v3/context/consent-tracking-context';
import { useComponentConfig } from '~/v3/hooks/use-component-config';
import { useFocusTrap } from '~/v3/hooks/use-focus-trap';
import { useIABConsentManager } from '~/v3/hooks/use-iab-consent-manager';
import { useScrollLock } from '~/v3/hooks/use-scroll-lock';
import { useTextDirection } from '~/v3/hooks/use-text-direction';
import { IABConsentDialogOverlay } from './atoms/overlay';
import { PurposeItem } from './atoms/purpose-item';
import { StackItem } from './atoms/stack-item';
import { VendorList } from './atoms/vendor-list';
import { useGVLData } from './hooks/use-gvl-data';
import type { VendorId } from './types';
import { useIABTranslations } from './use-iab-translations';

/**
 * Props for the IABConsentDialog component.
 * @public
 */
export interface IABConsentDialogProps {
	/**
	 * Control the open state. If omitted, follows activeUI === 'dialog' from context.
	 */
	open?: boolean;

	/**
	 * When true, removes all default styling.
	 * @default false
	 */
	noStyle?: boolean;

	/**
	 * When true, disables entrance/exit animations.
	 * @default false
	 */
	disableAnimation?: boolean;

	/**
	 * When true, locks page scroll when the dialog is visible.
	 * @default true
	 */
	scrollLock?: boolean;

	/**
	 * When true, traps keyboard focus within the dialog.
	 * @default true
	 */
	trapFocus?: boolean;

	/**
	 * When true, hides the branding in the footer.
	 * @default false
	 */
	hideBranding?: boolean;

	/**
	 * Show a floating trigger button to resurface the consent dialog.
	 * IAB TCF requires the consent dialog to be easily resurfaceable.
	 *
	 * - `true` - Show trigger with default settings
	 * - `false` - Hide trigger (default)
	 * - `ConsentDialogTriggerProps` - Show trigger with custom props
	 *
	 * @default false
	 */
	showTrigger?: boolean | ConsentDialogTriggerProps;

	/**
	 * Which consent models this dialog responds to.
	 * @default ['iab']
	 */
	models?: import('c15t').Model[];

	/**
	 * Override the UI source identifier sent with consent API calls.
	 * @default 'iab_dialog'
	 */
	uiSource?: string;
}

/**
 * IAB TCF 2.3 compliant consent dialog dialog.
 *
 * @remarks
 * This component implements the required IAB TCF 2.3 UI elements:
 * - Tabbed interface for Purposes and Vendors
 * - Purpose grouping with stacks
 * - Individual purpose and vendor consent toggles
 * - Special purposes and features
 * - Legitimate interest handling
 *
 * @public
 */
export const IABConsentDialog: FC<IABConsentDialogProps> = ({
	open,
	noStyle: localNoStyle,
	disableAnimation: localDisableAnimation,
	scrollLock: localScrollLock,
	trapFocus: localTrapFocus = true,
	hideBranding,
	showTrigger = false,
	models = ['iab'],
	uiSource: _uiSource,
}) => {
	const iabTranslations = useIABTranslations();
	const { common } = useTranslations();
	const {
		iab: iabState,
		activeUI,
		policyDialog,
		translationConfig,
		model,
	} = useIABConsentManager();
	const { closeUI, openDialog, performDialogAction } =
		useHeadlessIABConsentUI();
	const resolvedScrollLock = localScrollLock ?? policyDialog.scrollLock ?? true;

	const textDirection = useTextDirection(translationConfig.defaultLanguage);
	const cardRef = useRef<HTMLDivElement>(null);
	const contentRef = useRef<HTMLDivElement>(null);
	const previousHeightRef = useRef<number | null>(null);

	const [activeTab, setActiveTab] = useState<'purposes' | 'vendors'>(
		iabState?.preferenceCenterTab ?? 'purposes'
	);
	const [selectedVendorId, setSelectedVendorId] = useState<VendorId | null>(
		null
	);
	const [specialPurposesExpanded, setSpecialPurposesExpanded] = useState(false);
	const [isMounted, setIsMounted] = useState(false);
	const [isVisible, setIsVisible] = useState(false);

	const isOpen = open ?? (activeUI === 'dialog' && models.includes(model));

	// Merge local props with global theme context
	const config = useComponentConfig({
		noStyle: localNoStyle,
		disableAnimation: localDisableAnimation,
		scrollLock: resolvedScrollLock,
		trapFocus: localTrapFocus,
	});

	const {
		purposes,
		specialPurposes,
		specialFeatures,
		features,
		stacks,
		standalonePurposes,
		totalVendors,
	} = useGVLData();

	// Handlers
	const handlePurposeToggle = useCallback(
		(purposeId: number, value: boolean) => {
			iabState?.setPurposeConsent(purposeId, value);
		},
		[iabState]
	);

	const handleSpecialFeatureToggle = useCallback(
		(featureId: number, value: boolean) => {
			iabState?.setSpecialFeatureOptIn(featureId, value);
		},
		[iabState]
	);

	const handleVendorToggle = useCallback(
		(vendorId: VendorId, value: boolean) => {
			iabState?.setVendorConsent(vendorId, value);
		},
		[iabState]
	);

	const handleVendorLegitimateInterestToggle = useCallback(
		(vendorId: VendorId, value: boolean) => {
			iabState?.setVendorLegitimateInterest(vendorId, value);
		},
		[iabState]
	);

	const handlePurposeLegitimateInterestToggle = useCallback(
		(purposeId: number, value: boolean) => {
			iabState?.setPurposeLegitimateInterest(purposeId, value);
		},
		[iabState]
	);

	const handleAcceptAll = () => {
		void performDialogAction('accept');
	};

	const handleRejectAll = () => {
		void performDialogAction('reject');
	};

	const handleSave = () => {
		void performDialogAction('customize');
	};

	const handleClose = () => {
		closeUI();
	};

	const handleVendorClick = (vendorId: VendorId) => {
		setSelectedVendorId(vendorId);
		setActiveTab('vendors');
		openDialog({ tab: 'vendors' });
	};

	// Focus trap
	useFocusTrap(
		Boolean(isOpen && config.trapFocus),
		cardRef as RefObject<HTMLElement>
	);

	// Scroll lock
	useScrollLock(Boolean(isOpen && config.scrollLock));

	// Mount state for portal
	useEffect(() => {
		setIsMounted(true);
	}, []);

	// Visibility animation
	useEffect(() => {
		if (isOpen) {
			setIsVisible(true);
		} else if (config.disableAnimation) {
			setIsVisible(false);
		} else {
			const timer = setTimeout(() => {
				setIsVisible(false);
			}, 150);
			return () => clearTimeout(timer);
		}
	}, [isOpen, config.disableAnimation]);

	useEffect(() => {
		if (isOpen && iabState?.preferenceCenterTab) {
			setActiveTab(iabState.preferenceCenterTab);
		}
	}, [isOpen, iabState?.preferenceCenterTab]);

	// Smooth height animation when switching tabs
	// biome-ignore lint/correctness/useExhaustiveDependencies: activeTab is intentionally used as a trigger
	useLayoutEffect(() => {
		const content = contentRef.current;
		if (!content || previousHeightRef.current === null) {
			return;
		}

		const previousHeight = previousHeightRef.current;
		previousHeightRef.current = null;

		// Check for reduced motion preference
		const prefersReducedMotion = window.matchMedia(
			'(prefers-reduced-motion: reduce)'
		).matches;

		if (prefersReducedMotion) {
			return;
		}

		// Lock at previous height immediately
		content.style.height = `${previousHeight}px`;
		content.style.overflow = 'hidden';
		content.style.transition = 'none';

		// Use double-RAF to ensure browser has laid out new content
		let rafId1: number;
		let rafId2: number;

		rafId1 = requestAnimationFrame(() => {
			rafId2 = requestAnimationFrame(() => {
				if (!content) {
					return;
				}

				// Now measure the natural height of the new content
				content.style.height = 'auto';
				const newHeight = content.getBoundingClientRect().height;
				content.style.height = `${previousHeight}px`;

				// Skip animation if heights are the same
				if (Math.abs(previousHeight - newHeight) < 1) {
					content.style.height = '';
					content.style.overflow = '';
					content.style.transition = '';
					return;
				}

				// Force reflow before enabling transition
				content.offsetHeight;

				// Animate to new height
				content.style.transition =
					'height 180ms cubic-bezier(0.33, 1, 0.68, 1)';
				content.style.height = `${newHeight}px`;

				const handleTransitionEnd = (e: TransitionEvent) => {
					if (e.propertyName !== 'height') {
						return;
					}
					content.style.height = '';
					content.style.overflow = '';
					content.style.transition = '';
				};

				content.addEventListener('transitionend', handleTransitionEnd, {
					once: true,
				});
			});
		});

		return () => {
			cancelAnimationFrame(rafId1);
			cancelAnimationFrame(rafId2);
		};
	}, [activeTab]);

	// Capture height before tab change
	const handleTabChange = useCallback(
		(tab: 'purposes' | 'vendors') => {
			if (contentRef.current) {
				previousHeightRef.current = contentRef.current.offsetHeight;
			}
			setActiveTab(tab);
			openDialog({ tab });
		},
		[openDialog]
	);

	// Don't render if not mounted, no IAB state, or IAB is disabled (e.g., server returned null GVL)
	if (!isMounted || !iabState?.config.enabled) {
		return null;
	}

	const isLoading = iabState.isLoadingGVL || !iabState.gvl;

	const dialogContent = (
		<ConsentTrackingContext.Provider
			value={{ uiSource: _uiSource ?? 'iab_dialog' }}
		>
			<IABConsentDialogOverlay isOpen={isOpen} />
			<div
				className={`${styles.root} ${isVisible ? styles.dialogVisible : styles.dialogHidden}`}
				data-testid="iab-consent-dialog-root"
				dir={textDirection}
			>
				<div
					ref={cardRef}
					className={`${styles.card} ${isVisible ? styles.contentVisible : styles.contentHidden}`}
					role="dialog"
					aria-modal={config.trapFocus ? 'true' : undefined}
					aria-label={iabTranslations.preferenceCenter.title}
					tabIndex={0}
					data-testid="iab-consent-dialog-card"
				>
					{/* Header */}
					<div className={styles.header}>
						<div className={styles.headerContent}>
							<h2 className={styles.title}>
								{iabTranslations.preferenceCenter.title}
							</h2>
							<p className={styles.description}>
								{iabTranslations.preferenceCenter.description}
							</p>
						</div>
						<button
							type="button"
							onClick={handleClose}
							className={styles.closeButton}
							aria-label={common.close}
						>
							<svg
								style={{ width: '1rem', height: '1rem' }}
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								strokeWidth="2"
							>
								<line
									x1="18"
									y1="6"
									x2="6"
									y2="18"
								/>
								<line
									x1="6"
									y1="6"
									x2="18"
									y2="18"
								/>
							</svg>
						</button>
					</div>

					<Tabs.Root
						className={styles.body}
						noStyle
						onValueChange={(value) =>
							handleTabChange(value as 'purposes' | 'vendors')
						}
						value={activeTab}
					>
						{/* Segmented Control Tabs */}
						<div className={styles.tabsContainer}>
							<Tabs.List
								className={styles.tabsList}
								noStyle
							>
								<Tabs.Trigger
									className={styles.tabButton}
									noStyle
									value="purposes"
								>
									{iabTranslations.preferenceCenter.tabs.purposes}
									{!isLoading &&
										` (${purposes.length + specialPurposes.length + specialFeatures.length + features.length})`}
								</Tabs.Trigger>
								<Tabs.Trigger
									className={styles.tabButton}
									noStyle
									value="vendors"
								>
									{iabTranslations.preferenceCenter.tabs.vendors}
									{!isLoading && ` (${totalVendors})`}
								</Tabs.Trigger>
								<div
									aria-hidden="true"
									className={styles.tabIndicator}
									data-active-tab={activeTab}
								/>
							</Tabs.List>
						</div>

						<div
							ref={contentRef}
							className={styles.content}
						>
							{isLoading ? (
								<div className={styles.loadingContainer}>
									<div className={styles.loadingSpinner} />
									<p className={styles.loadingText}>
										{iabTranslations.common.loading}
									</p>
								</div>
							) : (
								<>
									<Tabs.Content
										className={styles.tabPanel}
										forceMount
										noStyle
										value="purposes"
									>
										{/* Standalone purposes */}
										{standalonePurposes.map((purpose) => (
											<PurposeItem
												key={purpose.id}
												purpose={purpose}
												isEnabled={
													iabState.purposeConsents[purpose.id] ?? false
												}
												onToggle={(value) =>
													handlePurposeToggle(purpose.id, value)
												}
												vendorConsents={iabState.vendorConsents}
												onVendorToggle={handleVendorToggle}
												onVendorClick={handleVendorClick}
												vendorLegitimateInterests={
													iabState.vendorLegitimateInterests
												}
												onVendorLegitimateInterestToggle={
													handleVendorLegitimateInterestToggle
												}
												purposeLegitimateInterests={
													iabState.purposeLegitimateInterests
												}
												onPurposeLegitimateInterestToggle={
													handlePurposeLegitimateInterestToggle
												}
											/>
										))}

										{/* Stacks */}
										{stacks.map((stack) => (
											<StackItem
												key={stack.id}
												stack={stack}
												consents={iabState.purposeConsents}
												onToggle={handlePurposeToggle}
												vendorConsents={iabState.vendorConsents}
												onVendorToggle={handleVendorToggle}
												onVendorClick={handleVendorClick}
												vendorLegitimateInterests={
													iabState.vendorLegitimateInterests
												}
												onVendorLegitimateInterestToggle={
													handleVendorLegitimateInterestToggle
												}
												purposeLegitimateInterests={
													iabState.purposeLegitimateInterests
												}
												onPurposeLegitimateInterestToggle={
													handlePurposeLegitimateInterestToggle
												}
											/>
										))}

										{/* Special Features */}
										{specialFeatures.map((feature) => (
											<PurposeItem
												key={`feature-${feature.id}`}
												purpose={{
													id: feature.id,
													name: feature.name,
													description: feature.description,
													illustrations: feature.illustrations,
													vendors: feature.vendors,
												}}
												isEnabled={
													iabState.specialFeatureOptIns[feature.id] ?? false
												}
												onToggle={(value) =>
													handleSpecialFeatureToggle(feature.id, value)
												}
												vendorConsents={iabState.vendorConsents}
												onVendorToggle={handleVendorToggle}
												onVendorClick={handleVendorClick}
												vendorLegitimateInterests={
													iabState.vendorLegitimateInterests
												}
												onVendorLegitimateInterestToggle={
													handleVendorLegitimateInterestToggle
												}
											/>
										))}

										{/* Essential Functions: Special Purposes + Features (locked) */}
										{(specialPurposes.length > 0 || features.length > 0) && (
											<div className={styles.specialPurposesSection}>
												<div className={styles.specialPurposesHeader}>
													<button
														type="button"
														onClick={() =>
															setSpecialPurposesExpanded(
																!specialPurposesExpanded
															)
														}
														className={styles.purposeTrigger}
													>
														<svg
															className={styles.purposeArrow}
															viewBox="0 0 24 24"
															fill="none"
															stroke="currentColor"
															strokeWidth="2"
														>
															{specialPurposesExpanded ? (
																<path d="M19 9l-7 7-7-7" />
															) : (
																<path d="M9 5l7 7-7 7" />
															)}
														</svg>
														<div className={styles.purposeInfo}>
															<h3 className={styles.specialPurposesTitle}>
																{
																	iabTranslations.preferenceCenter
																		.specialPurposes.title
																}
																<svg
																	className={styles.lockIcon}
																	viewBox="0 0 24 24"
																	fill="none"
																	stroke="currentColor"
																	strokeWidth="2"
																>
																	<rect
																		x="3"
																		y="11"
																		width="18"
																		height="11"
																		rx="2"
																		ry="2"
																	/>
																	<path d="M7 11V7a5 5 0 0 1 10 0v4" />
																</svg>
															</h3>
															<p className={styles.purposeMeta}>
																{
																	new Set([
																		...specialPurposes.flatMap((sp) =>
																			sp.vendors.map((v) => v.id)
																		),
																		...features.flatMap((f) =>
																			f.vendors.map((v) => v.id)
																		),
																	]).size
																}{' '}
																partners
															</p>
														</div>
													</button>
													<div style={{ position: 'relative' }}>
														<svg
															className={styles.infoIcon}
															viewBox="0 0 24 24"
															fill="none"
															stroke="currentColor"
															strokeWidth="2"
															aria-label={
																iabTranslations.preferenceCenter.specialPurposes
																	.tooltip
															}
														>
															<circle
																cx="12"
																cy="12"
																r="10"
															/>
															<line
																x1="12"
																y1="16"
																x2="12"
																y2="12"
															/>
															<line
																x1="12"
																y1="8"
																x2="12.01"
																y2="8"
															/>
														</svg>
													</div>
												</div>

												{specialPurposesExpanded && (
													<div style={{ padding: '0.75rem' }}>
														{/* Special Purposes */}
														{specialPurposes.map((purpose) => (
															<PurposeItem
																key={`special-${purpose.id}`}
																purpose={purpose}
																isEnabled={true}
																onToggle={() => {}}
																vendorConsents={iabState.vendorConsents}
																onVendorToggle={handleVendorToggle}
																onVendorClick={handleVendorClick}
																isLocked={true}
															/>
														))}

														{/* Features */}
														{features.map((feature) => (
															<PurposeItem
																key={`feature-${feature.id}`}
																purpose={{
																	id: feature.id,
																	name: feature.name,
																	description: feature.description,
																	illustrations: feature.illustrations,
																	vendors: feature.vendors,
																}}
																isEnabled={true}
																onToggle={() => {}}
																vendorConsents={iabState.vendorConsents}
																onVendorToggle={handleVendorToggle}
																onVendorClick={handleVendorClick}
																isLocked={true}
															/>
														))}
													</div>
												)}
											</div>
										)}

										{/* Consent storage notice */}
										<div className={styles.consentNotice}>
											<p className={styles.consentNoticeText}>
												{iabTranslations.preferenceCenter.footer.consentStorage}
											</p>
										</div>
									</Tabs.Content>
									<Tabs.Content
										className={styles.tabPanel}
										forceMount
										noStyle
										value="vendors"
									>
										<VendorList
											vendorData={iabState.gvl}
											purposes={purposes}
											vendorConsents={iabState.vendorConsents}
											onVendorToggle={handleVendorToggle}
											selectedVendorId={selectedVendorId}
											onClearSelection={() => setSelectedVendorId(null)}
											customVendors={iabState.nonIABVendors}
											vendorLegitimateInterests={
												iabState.vendorLegitimateInterests
											}
											onVendorLegitimateInterestToggle={
												handleVendorLegitimateInterestToggle
											}
										/>
									</Tabs.Content>
								</>
							)}
						</div>
					</Tabs.Root>

					{/* Footer */}
					<div className={`${styles.footer} ${actionStyles.actionRoot}`}>
						<div
							className={actionStyles.actionGroup}
							data-direction="row"
						>
							<Button.Root
								variant="neutral"
								mode="stroke"
								size="small"
								onClick={handleRejectAll}
								disabled={isLoading}
								data-action="reject"
							>
								{iabTranslations.common.rejectAll}
							</Button.Root>
							<Button.Root
								variant="neutral"
								mode="stroke"
								size="small"
								onClick={handleAcceptAll}
								disabled={isLoading}
								data-action="accept"
							>
								{iabTranslations.common.acceptAll}
							</Button.Root>
						</div>
						<Button.Root
							variant="primary"
							mode="filled"
							size="small"
							onClick={handleSave}
							disabled={isLoading}
							data-action="customize"
						>
							{iabTranslations.common.saveSettings}
						</Button.Root>
					</div>

					<Branding
						hideBranding={hideBranding ?? false}
						variant="dialog-tag"
						themeKey="iabConsentDialogTag"
						data-testid="iab-consent-dialog-branding"
					/>
				</div>
			</div>
		</ConsentTrackingContext.Provider>
	);

	// Resolve trigger props
	const triggerProps: ConsentDialogTriggerProps | null =
		showTrigger === true
			? {} // Use defaults
			: showTrigger === false
				? null
				: showTrigger;

	// Render trigger even when dialog is closed
	const triggerElement = triggerProps ? (
		<ConsentDialogTrigger {...triggerProps} />
	) : null;

	if (!isOpen && !isVisible) {
		return triggerElement;
	}

	return (
		<>
			{triggerElement}
			{createPortal(dialogContent, document.body)}
		</>
	);
};
